/*
 * This file was automatically generated by EvoSuite
 * Wed Jan 07 05:29:30 MSK 2015
 */

package fb.rt.waterprocess;

import static org.junit.Assert.*;
import org.junit.Test;
import fb.rt.waterprocess.FB_HeaterControl__Basic;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.EvoSuiteFile;
import org.junit.runner.RunWith;


public class FB_HeaterControl__Basic_Tr_ESTest {

  //Test case number: 0
  /*
   * 2 covered goals:
   * 1 fb.rt.waterprocess.FB_HeaterControl__Basic.transition_FB_HeaterControl_1()V: root-Branch
   * 2 fb.rt.waterprocess.FB_HeaterControl__Basic.transition_FB_HeaterControl_3()V: root-Branch
   */

  @Test
  public void test0()  throws Throwable  {
      FB_HeaterControl__Basic fB_HeaterControl__Basic0 = new FB_HeaterControl__Basic();
      fB_HeaterControl__Basic0.event_REQ(true, true);
  }

  //Test case number: 1
  /*
   * 2 covered goals:
   * 1 fb.rt.waterprocess.FB_HeaterControl__Basic.transition_FB_HeaterControl_0()V: root-Branch
   * 2 fb.rt.waterprocess.FB_HeaterControl__Basic.transition_FB_HeaterControl_2()V: root-Branch
   */

  @Test
  public void test1()  throws Throwable  {
      FB_HeaterControl__Basic fB_HeaterControl__Basic0 = new FB_HeaterControl__Basic();
      fB_HeaterControl__Basic0.event_INIT(false, false);
  }
}
