/*
 * This file was automatically generated by EvoSuite
 * Wed Jan 07 05:49:43 MSK 2015
 */

package fb.rt.waterprocess;

import static org.junit.Assert.*;
import org.junit.Test;
import fb.rt.waterprocess.FB_PIDControl__Basic;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.EvoSuiteFile;
import org.junit.runner.RunWith;


public class FB_PIDControl__Basic_Tr_ESTest {

  //Test case number: 0
  /*
   * 2 covered goals:
   * 1 fb.rt.waterprocess.FB_PIDControl__Basic.transition_FB_PIDControl_3()V: root-Branch
   * 2 fb.rt.waterprocess.FB_PIDControl__Basic.transition_FB_PIDControl_1()V: root-Branch
   */

  @Test
  public void test0()  throws Throwable  {
      FB_PIDControl__Basic fB_PIDControl__Basic0 = new FB_PIDControl__Basic();
      fB_PIDControl__Basic0.event_REQ(true, 27690.295F, 27690.295F, 27690.295F, 27690.295F, 27690.295F, 27690.295F);
  }

  //Test case number: 1
  /*
   * 2 covered goals:
   * 1 fb.rt.waterprocess.FB_PIDControl__Basic.transition_FB_PIDControl_0()V: root-Branch
   * 2 fb.rt.waterprocess.FB_PIDControl__Basic.transition_FB_PIDControl_2()V: root-Branch
   */

  @Test
  public void test1()  throws Throwable  {
      FB_PIDControl__Basic fB_PIDControl__Basic0 = new FB_PIDControl__Basic();
      fB_PIDControl__Basic0.event_INIT(false, 27690.295F, 27690.295F, 27690.295F, 27690.295F, 27690.295F, 27690.295F);
  }
}
