/*
 * This file was automatically generated by EvoSuite
 * Tue Jan 06 16:00:35 MSK 2015
 */

package fb.rt.waterprocess;

import static org.junit.Assert.*;
import org.junit.Test;
import fb.rt.waterprocess.FB_PumpControl__Basic;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.EvoSuiteFile;
import org.junit.runner.RunWith;


public class FB_PumpControl__Basic_ESTest {

  //Test case number: 0
  /*
   * 1 covered goal:
   * 1 fb.rt.waterprocess.FB_PumpControl__Basic$FB_PumpControl.alg_REQ()V: I39 Branch 8 IFEQ L163 - false
   */

  @Test
  public void test0()  throws Throwable  {
      FB_PumpControl__Basic fB_PumpControl__Basic0 = new FB_PumpControl__Basic();
      fB_PumpControl__Basic0.event_REQ((-2430.3464F), (-2430.3464F), true, true, (-2430.3464F));
  }

  //Test case number: 1
  /*
   * 2 covered goals:
   * 1 fb.rt.waterprocess.FB_PumpControl__Basic$FB_PumpControl.alg_REQ()V: I19 Branch 6 IFLT L163 - false
   * 2 fb.rt.waterprocess.FB_PumpControl__Basic$FB_PumpControl.alg_REQ()V: I32 Branch 7 IFGT L163 - true
   */

  @Test
  public void test1()  throws Throwable  {
      FB_PumpControl__Basic fB_PumpControl__Basic0 = new FB_PumpControl__Basic();
      fB_PumpControl__Basic0.event_REQ((-12.541395F), (-2430.3464F), true, true, (-12.541395F));
  }

  //Test case number: 2
  /*
   * 4 covered goals:
   * 1 fb.rt.waterprocess.FB_PumpControl__Basic$FB_PumpControl.alg_REQ()V: I9 Branch 5 IFEQ L162 - false
   * 2 fb.rt.waterprocess.FB_PumpControl__Basic$FB_PumpControl.alg_REQ()V: I19 Branch 6 IFLT L163 - true
   * 3 fb.rt.waterprocess.FB_PumpControl__Basic$FB_PumpControl.alg_REQ()V: I32 Branch 7 IFGT L163 - false
   * 4 fb.rt.waterprocess.FB_PumpControl__Basic$FB_PumpControl.alg_REQ()V: I39 Branch 8 IFEQ L163 - true
   */

  @Test
  public void test2()  throws Throwable  {
      FB_PumpControl__Basic fB_PumpControl__Basic0 = new FB_PumpControl__Basic();
      fB_PumpControl__Basic0.event_REQ((-12.541395F), (-12.541395F), true, true, (-2430.3464F));
  }

  //Test case number: 3
  /*
   * 7 covered goals:
   * 1 fb.rt.waterprocess.FB_PumpControl__Basic.transition_FB_PumpControl_2()V: root-Branch
   * 2 fb.rt.waterprocess.FB_PumpControl__Basic.transition_FB_PumpControl_0()V: root-Branch
   * 3 fb.rt.waterprocess.FB_PumpControl__Basic.event_INIT(FFZZF)V: root-Branch
   * 4 fb.rt.waterprocess.FB_PumpControl__Basic$FB_PumpControl.alg_INIT()V: root-Branch
   * 5 fb.rt.waterprocess.FB_PumpControl__Basic$FB_PumpControl.state_INIT()V: root-Branch
   * 6 fb.rt.waterprocess.FB_PumpControl__Basic$FB_PumpControl.service_INIT()V: I4 Branch 3 IFNE L135 - false
   * 7 fb.rt.waterprocess.FB_PumpControl__Basic$FB_PumpControl.serviceEvent(Lfb/rt/EventServer;)V: I5 Branch 1 IF_ACMPNE L129 - false
   */

  @Test
  public void test3()  throws Throwable  {
      FB_PumpControl__Basic fB_PumpControl__Basic0 = new FB_PumpControl__Basic();
      fB_PumpControl__Basic0.event_INIT((-1.0F), (-1.0F), false, false, (-1.0F));
  }

  //Test case number: 4
  /*
   * 11 covered goals:
   * 1 fb.rt.waterprocess.FB_PumpControl__Basic.transition_FB_PumpControl_1()V: root-Branch
   * 2 fb.rt.waterprocess.FB_PumpControl__Basic.<init>()V: root-Branch
   * 3 fb.rt.waterprocess.FB_PumpControl__Basic.event_REQ(FFZZF)V: root-Branch
   * 4 fb.rt.waterprocess.FB_PumpControl__Basic.transition_FB_PumpControl_3()V: root-Branch
   * 5 fb.rt.waterprocess.FB_PumpControl__Basic$FB_PumpControl.<init>(Lfb/rt/waterprocess/FB_PumpControl__Basic;)V: root-Branch
   * 6 fb.rt.waterprocess.FB_PumpControl__Basic$FB_PumpControl.state_START()V: root-Branch
   * 7 fb.rt.waterprocess.FB_PumpControl__Basic$FB_PumpControl.state_REQ()V: root-Branch
   * 8 fb.rt.waterprocess.FB_PumpControl__Basic$FB_PumpControl.alg_REQ()V: I9 Branch 5 IFEQ L162 - true
   * 9 fb.rt.waterprocess.FB_PumpControl__Basic$FB_PumpControl.service_REQ()V: I4 Branch 4 IFNE L143 - false
   * 10 fb.rt.waterprocess.FB_PumpControl__Basic$FB_PumpControl.serviceEvent(Lfb/rt/EventServer;)V: I5 Branch 1 IF_ACMPNE L129 - true
   * 11 fb.rt.waterprocess.FB_PumpControl__Basic$FB_PumpControl.serviceEvent(Lfb/rt/EventServer;)V: I14 Branch 2 IF_ACMPNE L130 - false
   */

  @Test
  public void test4()  throws Throwable  {
      FB_PumpControl__Basic fB_PumpControl__Basic0 = new FB_PumpControl__Basic();
      fB_PumpControl__Basic0.event_REQ((-1.0F), (-1.0F), false, false, (-1.0F));
  }
}
