/*
 * This file was automatically generated by EvoSuite
 * Tue Jan 06 16:20:48 MSK 2015
 */

package fb.rt.waterprocess;

import static org.junit.Assert.*;
import org.junit.Test;
import fb.rt.waterprocess.FB_TankControl__Basic;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.EvoSuiteFile;
import org.junit.runner.RunWith;


public class FB_TankControl__Basic_ESTest {

  //Test case number: 0
  /*
   * 8 covered goals:
   * 1 fb.rt.waterprocess.FB_TankControl__Basic$FB_TankControl.alg_REQ()V: I23 Branch 6 IFEQ L238 - false
   * 2 fb.rt.waterprocess.FB_TankControl__Basic$FB_TankControl.alg_REQ()V: I77 Branch 9 IFEQ L241 - true
   * 3 fb.rt.waterprocess.FB_TankControl__Basic$FB_TankControl.alg_REQ()V: I85 Branch 10 IFEQ L241 - false
   * 4 fb.rt.waterprocess.FB_TankControl__Basic$FB_TankControl.alg_REQ()V: I109 Branch 11 IFEQ L248 - false
   * 5 fb.rt.waterprocess.FB_TankControl__Basic$FB_TankControl.alg_REQ()V: I145 Branch 13 IFEQ L255 - false
   * 6 fb.rt.waterprocess.FB_TankControl__Basic$FB_TankControl.alg_REQ()V: I181 Branch 14 IFEQ L262 - true
   * 7 fb.rt.waterprocess.FB_TankControl__Basic$FB_TankControl.alg_REQ()V: I200 Branch 16 IFEQ L262 - false
   * 8 fb.rt.waterprocess.FB_TankControl__Basic$FB_TankControl.alg_REQ()V: I232 Branch 18 IFEQ L269 - false
   */

  @Test
  public void test0()  throws Throwable  {
      FB_TankControl__Basic fB_TankControl__Basic0 = new FB_TankControl__Basic();
      fB_TankControl__Basic0.event_REQ(true, true, true, true, true, true, true, false, false, true, true, true, false, true, false);
  }

  //Test case number: 1
  /*
   * 7 covered goals:
   * 1 fb.rt.waterprocess.FB_TankControl__Basic$FB_TankControl.alg_REQ()V: I8 Branch 5 IFEQ L237 - false
   * 2 fb.rt.waterprocess.FB_TankControl__Basic$FB_TankControl.alg_REQ()V: I41 Branch 7 IFEQ L239 - true
   * 3 fb.rt.waterprocess.FB_TankControl__Basic$FB_TankControl.alg_REQ()V: I59 Branch 8 IFEQ L240 - true
   * 4 fb.rt.waterprocess.FB_TankControl__Basic$FB_TankControl.alg_REQ()V: I120 Branch 12 IFEQ L248 - false
   * 5 fb.rt.waterprocess.FB_TankControl__Basic$FB_TankControl.alg_REQ()V: I191 Branch 15 IFEQ L262 - true
   * 6 fb.rt.waterprocess.FB_TankControl__Basic$FB_TankControl.alg_REQ()V: I208 Branch 17 IFEQ L262 - false
   * 7 fb.rt.waterprocess.FB_TankControl__Basic$FB_TankControl.alg_REQ()V: I243 Branch 19 IFEQ L269 - false
   */

  @Test
  public void test1()  throws Throwable  {
      FB_TankControl__Basic fB_TankControl__Basic0 = new FB_TankControl__Basic();
      fB_TankControl__Basic0.event_REQ(true, false, true, false, true, false, false, true, false, false, false, false, true, false, true);
  }

  //Test case number: 2
  /*
   * 7 covered goals:
   * 1 fb.rt.waterprocess.FB_TankControl__Basic.transition_FB_TankControl_2()V: root-Branch
   * 2 fb.rt.waterprocess.FB_TankControl__Basic.transition_FB_TankControl_0()V: root-Branch
   * 3 fb.rt.waterprocess.FB_TankControl__Basic.event_INIT(ZZZZZZZZZZZZZZZ)V: root-Branch
   * 4 fb.rt.waterprocess.FB_TankControl__Basic$FB_TankControl.alg_INIT()V: root-Branch
   * 5 fb.rt.waterprocess.FB_TankControl__Basic$FB_TankControl.state_INIT()V: root-Branch
   * 6 fb.rt.waterprocess.FB_TankControl__Basic$FB_TankControl.service_INIT()V: I4 Branch 3 IFNE L209 - false
   * 7 fb.rt.waterprocess.FB_TankControl__Basic$FB_TankControl.serviceEvent(Lfb/rt/EventServer;)V: I5 Branch 1 IF_ACMPNE L203 - false
   */

  @Test
  public void test2()  throws Throwable  {
      FB_TankControl__Basic fB_TankControl__Basic0 = new FB_TankControl__Basic();
      fB_TankControl__Basic0.event_INIT(false, true, false, false, false, false, true, true, true, false, false, false, true, false, true);
  }

  //Test case number: 3
  /*
   * 25 covered goals:
   * 1 fb.rt.waterprocess.FB_TankControl__Basic.event_REQ(ZZZZZZZZZZZZZZZ)V: root-Branch
   * 2 fb.rt.waterprocess.FB_TankControl__Basic.transition_FB_TankControl_1()V: root-Branch
   * 3 fb.rt.waterprocess.FB_TankControl__Basic.<init>()V: root-Branch
   * 4 fb.rt.waterprocess.FB_TankControl__Basic.transition_FB_TankControl_3()V: root-Branch
   * 5 fb.rt.waterprocess.FB_TankControl__Basic$FB_TankControl.state_START()V: root-Branch
   * 6 fb.rt.waterprocess.FB_TankControl__Basic$FB_TankControl.state_REQ()V: root-Branch
   * 7 fb.rt.waterprocess.FB_TankControl__Basic$FB_TankControl.<init>(Lfb/rt/waterprocess/FB_TankControl__Basic;)V: root-Branch
   * 8 fb.rt.waterprocess.FB_TankControl__Basic$FB_TankControl.alg_REQ()V: I8 Branch 5 IFEQ L237 - true
   * 9 fb.rt.waterprocess.FB_TankControl__Basic$FB_TankControl.alg_REQ()V: I23 Branch 6 IFEQ L238 - true
   * 10 fb.rt.waterprocess.FB_TankControl__Basic$FB_TankControl.alg_REQ()V: I41 Branch 7 IFEQ L239 - false
   * 11 fb.rt.waterprocess.FB_TankControl__Basic$FB_TankControl.alg_REQ()V: I59 Branch 8 IFEQ L240 - false
   * 12 fb.rt.waterprocess.FB_TankControl__Basic$FB_TankControl.alg_REQ()V: I77 Branch 9 IFEQ L241 - false
   * 13 fb.rt.waterprocess.FB_TankControl__Basic$FB_TankControl.alg_REQ()V: I85 Branch 10 IFEQ L241 - true
   * 14 fb.rt.waterprocess.FB_TankControl__Basic$FB_TankControl.alg_REQ()V: I109 Branch 11 IFEQ L248 - true
   * 15 fb.rt.waterprocess.FB_TankControl__Basic$FB_TankControl.alg_REQ()V: I120 Branch 12 IFEQ L248 - true
   * 16 fb.rt.waterprocess.FB_TankControl__Basic$FB_TankControl.alg_REQ()V: I145 Branch 13 IFEQ L255 - true
   * 17 fb.rt.waterprocess.FB_TankControl__Basic$FB_TankControl.alg_REQ()V: I181 Branch 14 IFEQ L262 - false
   * 18 fb.rt.waterprocess.FB_TankControl__Basic$FB_TankControl.alg_REQ()V: I191 Branch 15 IFEQ L262 - false
   * 19 fb.rt.waterprocess.FB_TankControl__Basic$FB_TankControl.alg_REQ()V: I200 Branch 16 IFEQ L262 - true
   * 20 fb.rt.waterprocess.FB_TankControl__Basic$FB_TankControl.alg_REQ()V: I208 Branch 17 IFEQ L262 - true
   * 21 fb.rt.waterprocess.FB_TankControl__Basic$FB_TankControl.alg_REQ()V: I232 Branch 18 IFEQ L269 - true
   * 22 fb.rt.waterprocess.FB_TankControl__Basic$FB_TankControl.alg_REQ()V: I243 Branch 19 IFEQ L269 - true
   * 23 fb.rt.waterprocess.FB_TankControl__Basic$FB_TankControl.service_REQ()V: I4 Branch 4 IFNE L217 - false
   * 24 fb.rt.waterprocess.FB_TankControl__Basic$FB_TankControl.serviceEvent(Lfb/rt/EventServer;)V: I5 Branch 1 IF_ACMPNE L203 - true
   * 25 fb.rt.waterprocess.FB_TankControl__Basic$FB_TankControl.serviceEvent(Lfb/rt/EventServer;)V: I14 Branch 2 IF_ACMPNE L204 - false
   */

  @Test
  public void test3()  throws Throwable  {
      FB_TankControl__Basic fB_TankControl__Basic0 = new FB_TankControl__Basic();
      fB_TankControl__Basic0.event_REQ(false, false, false, false, true, false, true, false, true, false, true, true, false, false, true);
  }
}
