/*
 * This file was automatically generated by EvoSuite
 * Wed Jan 07 06:30:08 MSK 2015
 */

package fb.rt.waterprocess;

import static org.junit.Assert.*;
import org.junit.Test;
import fb.rt.waterprocess.FB_ValveControl__Basic;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.EvoSuiteFile;
import org.junit.runner.RunWith;


public class FB_ValveControl__Basic_Tr_ESTest {

  //Test case number: 0
  /*
   * 2 covered goals:
   * 1 fb.rt.waterprocess.FB_ValveControl__Basic.transition_FB_ValveControl_1()V: root-Branch
   * 2 fb.rt.waterprocess.FB_ValveControl__Basic.transition_FB_ValveControl_3()V: root-Branch
   */

  @Test
  public void test0()  throws Throwable  {
      FB_ValveControl__Basic fB_ValveControl__Basic0 = new FB_ValveControl__Basic();
      fB_ValveControl__Basic0.event_REQ(false, 37.41026F, (-1440.9904F), false, false, 37.41026F);
  }

  //Test case number: 1
  /*
   * 2 covered goals:
   * 1 fb.rt.waterprocess.FB_ValveControl__Basic.transition_FB_ValveControl_0()V: root-Branch
   * 2 fb.rt.waterprocess.FB_ValveControl__Basic.transition_FB_ValveControl_2()V: root-Branch
   */

  @Test
  public void test1()  throws Throwable  {
      FB_ValveControl__Basic fB_ValveControl__Basic0 = new FB_ValveControl__Basic();
      fB_ValveControl__Basic0.event_INIT(true, (-1440.9904F), 31.153F, true, true, 31.153F);
  }
}
