/*
 * This file was automatically generated by EvoSuite
 * Tue Jan 06 16:30:55 MSK 2015
 */

package fb.rt.waterprocess;

import static org.junit.Assert.*;
import org.junit.Test;
import fb.rt.waterprocess.FB_ValveControl__Basic;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.EvoSuiteFile;
import org.junit.runner.RunWith;


public class FB_ValveControl__Basic_ESTest {

  //Test case number: 0
  /*
   * 1 covered goal:
   * 1 fb.rt.waterprocess.FB_ValveControl__Basic$FB_ValveControl.alg_REQ()V: I43 Branch 8 IFEQ L170 - false
   */

  @Test
  public void test0()  throws Throwable  {
      FB_ValveControl__Basic fB_ValveControl__Basic0 = new FB_ValveControl__Basic();
      fB_ValveControl__Basic0.event_REQ(true, (-1.60936F), (-1.60936F), true, true, (-1.60936F));
  }

  //Test case number: 1
  /*
   * 2 covered goals:
   * 1 fb.rt.waterprocess.FB_ValveControl__Basic$FB_ValveControl.alg_REQ()V: I23 Branch 6 IFLT L170 - true
   * 2 fb.rt.waterprocess.FB_ValveControl__Basic$FB_ValveControl.alg_REQ()V: I36 Branch 7 IFGT L170 - false
   */

  @Test
  public void test1()  throws Throwable  {
      FB_ValveControl__Basic fB_ValveControl__Basic0 = new FB_ValveControl__Basic();
      fB_ValveControl__Basic0.event_REQ(true, 0.0F, (-1.60936F), true, true, (-1.60936F));
  }

  //Test case number: 2
  /*
   * 1 covered goal:
   * 1 fb.rt.waterprocess.FB_ValveControl__Basic$FB_ValveControl.alg_REQ()V: I13 Branch 5 IFEQ L169 - true
   */

  @Test
  public void test2()  throws Throwable  {
      FB_ValveControl__Basic fB_ValveControl__Basic0 = new FB_ValveControl__Basic();
      fB_ValveControl__Basic0.event_REQ(false, 2.121237F, 2.121237F, true, true, (-1.8900468F));
  }

  //Test case number: 3
  /*
   * 11 covered goals:
   * 1 fb.rt.waterprocess.FB_ValveControl__Basic.transition_FB_ValveControl_1()V: root-Branch
   * 2 fb.rt.waterprocess.FB_ValveControl__Basic.event_REQ(ZFFZZF)V: root-Branch
   * 3 fb.rt.waterprocess.FB_ValveControl__Basic.transition_FB_ValveControl_3()V: root-Branch
   * 4 fb.rt.waterprocess.FB_ValveControl__Basic$FB_ValveControl.state_REQ()V: root-Branch
   * 5 fb.rt.waterprocess.FB_ValveControl__Basic$FB_ValveControl.alg_REQ()V: I13 Branch 5 IFEQ L169 - false
   * 6 fb.rt.waterprocess.FB_ValveControl__Basic$FB_ValveControl.alg_REQ()V: I23 Branch 6 IFLT L170 - false
   * 7 fb.rt.waterprocess.FB_ValveControl__Basic$FB_ValveControl.alg_REQ()V: I36 Branch 7 IFGT L170 - true
   * 8 fb.rt.waterprocess.FB_ValveControl__Basic$FB_ValveControl.alg_REQ()V: I43 Branch 8 IFEQ L170 - true
   * 9 fb.rt.waterprocess.FB_ValveControl__Basic$FB_ValveControl.service_REQ()V: I4 Branch 4 IFNE L150 - false
   * 10 fb.rt.waterprocess.FB_ValveControl__Basic$FB_ValveControl.serviceEvent(Lfb/rt/EventServer;)V: I5 Branch 1 IF_ACMPNE L136 - true
   * 11 fb.rt.waterprocess.FB_ValveControl__Basic$FB_ValveControl.serviceEvent(Lfb/rt/EventServer;)V: I14 Branch 2 IF_ACMPNE L137 - false
   */

  @Test
  public void test3()  throws Throwable  {
      FB_ValveControl__Basic fB_ValveControl__Basic0 = new FB_ValveControl__Basic();
      fB_ValveControl__Basic0.event_REQ(true, 2.121237F, (-1.8900468F), true, true, 2.121237F);
  }

  //Test case number: 4
  /*
   * 10 covered goals:
   * 1 fb.rt.waterprocess.FB_ValveControl__Basic.transition_FB_ValveControl_0()V: root-Branch
   * 2 fb.rt.waterprocess.FB_ValveControl__Basic.event_INIT(ZFFZZF)V: root-Branch
   * 3 fb.rt.waterprocess.FB_ValveControl__Basic.transition_FB_ValveControl_2()V: root-Branch
   * 4 fb.rt.waterprocess.FB_ValveControl__Basic.<init>()V: root-Branch
   * 5 fb.rt.waterprocess.FB_ValveControl__Basic$FB_ValveControl.state_START()V: root-Branch
   * 6 fb.rt.waterprocess.FB_ValveControl__Basic$FB_ValveControl.state_INIT()V: root-Branch
   * 7 fb.rt.waterprocess.FB_ValveControl__Basic$FB_ValveControl.alg_INIT()V: root-Branch
   * 8 fb.rt.waterprocess.FB_ValveControl__Basic$FB_ValveControl.<init>(Lfb/rt/waterprocess/FB_ValveControl__Basic;)V: root-Branch
   * 9 fb.rt.waterprocess.FB_ValveControl__Basic$FB_ValveControl.service_INIT()V: I4 Branch 3 IFNE L142 - false
   * 10 fb.rt.waterprocess.FB_ValveControl__Basic$FB_ValveControl.serviceEvent(Lfb/rt/EventServer;)V: I5 Branch 1 IF_ACMPNE L136 - false
   */

  @Test
  public void test4()  throws Throwable  {
      FB_ValveControl__Basic fB_ValveControl__Basic0 = new FB_ValveControl__Basic();
      fB_ValveControl__Basic0.event_INIT(true, (-1.8900468F), (-1.8900468F), true, false, (-1.8900468F));
  }
}
