/*
 * This file was automatically generated by EvoSuite
 * Tue Jan 06 16:41:01 MSK 2015
 */

package fb.rt.waterprocess;

import static org.junit.Assert.*;
import org.junit.Test;
import fb.rt.waterprocess.NOT10__Basic;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.EvoSuiteFile;
import org.junit.runner.RunWith;


public class NOT10__Basic_ESTest {

  //Test case number: 0
  /*
   * 10 covered goals:
   * 1 fb.rt.waterprocess.NOT10__Basic$NOT10.alg_REQ()V: I7 Branch 3 IFEQ L165 - false
   * 2 fb.rt.waterprocess.NOT10__Basic$NOT10.alg_REQ()V: I21 Branch 4 IFEQ L166 - false
   * 3 fb.rt.waterprocess.NOT10__Basic$NOT10.alg_REQ()V: I35 Branch 5 IFEQ L167 - false
   * 4 fb.rt.waterprocess.NOT10__Basic$NOT10.alg_REQ()V: I49 Branch 6 IFEQ L168 - false
   * 5 fb.rt.waterprocess.NOT10__Basic$NOT10.alg_REQ()V: I63 Branch 7 IFEQ L169 - false
   * 6 fb.rt.waterprocess.NOT10__Basic$NOT10.alg_REQ()V: I77 Branch 8 IFEQ L170 - false
   * 7 fb.rt.waterprocess.NOT10__Basic$NOT10.alg_REQ()V: I91 Branch 9 IFEQ L171 - true
   * 8 fb.rt.waterprocess.NOT10__Basic$NOT10.alg_REQ()V: I105 Branch 10 IFEQ L172 - true
   * 9 fb.rt.waterprocess.NOT10__Basic$NOT10.alg_REQ()V: I119 Branch 11 IFEQ L173 - true
   * 10 fb.rt.waterprocess.NOT10__Basic$NOT10.alg_REQ()V: I133 Branch 12 IFEQ L174 - false
   */

  @Test
  public void test0()  throws Throwable  {
      NOT10__Basic nOT10__Basic0 = new NOT10__Basic();
      nOT10__Basic0.event_REQ(true, true, true, true, true, true, false, false, false, true);
  }

  //Test case number: 1
  /*
   * 19 covered goals:
   * 1 fb.rt.waterprocess.NOT10__Basic.event_REQ(ZZZZZZZZZZ)V: root-Branch
   * 2 fb.rt.waterprocess.NOT10__Basic.transition_NOT10_0()V: root-Branch
   * 3 fb.rt.waterprocess.NOT10__Basic.transition_NOT10_1()V: root-Branch
   * 4 fb.rt.waterprocess.NOT10__Basic.<init>()V: root-Branch
   * 5 fb.rt.waterprocess.NOT10__Basic$NOT10.state_START()V: root-Branch
   * 6 fb.rt.waterprocess.NOT10__Basic$NOT10.state_REQ()V: root-Branch
   * 7 fb.rt.waterprocess.NOT10__Basic$NOT10.<init>(Lfb/rt/waterprocess/NOT10__Basic;)V: root-Branch
   * 8 fb.rt.waterprocess.NOT10__Basic$NOT10.alg_REQ()V: I7 Branch 3 IFEQ L165 - true
   * 9 fb.rt.waterprocess.NOT10__Basic$NOT10.alg_REQ()V: I21 Branch 4 IFEQ L166 - true
   * 10 fb.rt.waterprocess.NOT10__Basic$NOT10.alg_REQ()V: I35 Branch 5 IFEQ L167 - true
   * 11 fb.rt.waterprocess.NOT10__Basic$NOT10.alg_REQ()V: I49 Branch 6 IFEQ L168 - true
   * 12 fb.rt.waterprocess.NOT10__Basic$NOT10.alg_REQ()V: I63 Branch 7 IFEQ L169 - true
   * 13 fb.rt.waterprocess.NOT10__Basic$NOT10.alg_REQ()V: I77 Branch 8 IFEQ L170 - true
   * 14 fb.rt.waterprocess.NOT10__Basic$NOT10.alg_REQ()V: I91 Branch 9 IFEQ L171 - false
   * 15 fb.rt.waterprocess.NOT10__Basic$NOT10.alg_REQ()V: I105 Branch 10 IFEQ L172 - false
   * 16 fb.rt.waterprocess.NOT10__Basic$NOT10.alg_REQ()V: I119 Branch 11 IFEQ L173 - false
   * 17 fb.rt.waterprocess.NOT10__Basic$NOT10.alg_REQ()V: I133 Branch 12 IFEQ L174 - true
   * 18 fb.rt.waterprocess.NOT10__Basic$NOT10.service_REQ()V: I4 Branch 2 IFNE L157 - false
   * 19 fb.rt.waterprocess.NOT10__Basic$NOT10.serviceEvent(Lfb/rt/EventServer;)V: I5 Branch 1 IF_ACMPNE L152 - false
   */

  @Test
  public void test1()  throws Throwable  {
      NOT10__Basic nOT10__Basic0 = new NOT10__Basic();
      nOT10__Basic0.event_REQ(false, false, false, false, false, false, true, true, true, false);
  }
}
