/*
 * This file was automatically generated by EvoSuite
 * Tue Jan 06 16:51:07 MSK 2015
 */

package fb.rt.waterprocess;

import static org.junit.Assert.*;
import org.junit.Test;
import fb.rt.waterprocess.NOT16__Basic;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.EvoSuiteFile;
import org.junit.runner.RunWith;


public class NOT16__Basic_ESTest {

  //Test case number: 0
  /*
   * 8 covered goals:
   * 1 fb.rt.waterprocess.NOT16__Basic$NOT16.alg_REQ()V: I21 Branch 4 IFEQ L214 - false
   * 2 fb.rt.waterprocess.NOT16__Basic$NOT16.alg_REQ()V: I35 Branch 5 IFEQ L215 - true
   * 3 fb.rt.waterprocess.NOT16__Basic$NOT16.alg_REQ()V: I91 Branch 9 IFEQ L219 - true
   * 4 fb.rt.waterprocess.NOT16__Basic$NOT16.alg_REQ()V: I119 Branch 11 IFEQ L221 - false
   * 5 fb.rt.waterprocess.NOT16__Basic$NOT16.alg_REQ()V: I133 Branch 12 IFEQ L222 - false
   * 6 fb.rt.waterprocess.NOT16__Basic$NOT16.alg_REQ()V: I161 Branch 14 IFEQ L224 - false
   * 7 fb.rt.waterprocess.NOT16__Basic$NOT16.alg_REQ()V: I175 Branch 15 IFEQ L225 - false
   * 8 fb.rt.waterprocess.NOT16__Basic$NOT16.alg_REQ()V: I217 Branch 18 IFEQ L228 - false
   */

  @Test
  public void test0()  throws Throwable  {
      NOT16__Basic nOT16__Basic0 = new NOT16__Basic();
      nOT16__Basic0.event_REQ(true, true, false, false, true, false, false, false, true, true, true, true, true, true, false, true);
  }

  //Test case number: 1
  /*
   * 8 covered goals:
   * 1 fb.rt.waterprocess.NOT16__Basic$NOT16.alg_REQ()V: I7 Branch 3 IFEQ L213 - false
   * 2 fb.rt.waterprocess.NOT16__Basic$NOT16.alg_REQ()V: I49 Branch 6 IFEQ L216 - false
   * 3 fb.rt.waterprocess.NOT16__Basic$NOT16.alg_REQ()V: I63 Branch 7 IFEQ L217 - false
   * 4 fb.rt.waterprocess.NOT16__Basic$NOT16.alg_REQ()V: I77 Branch 8 IFEQ L218 - false
   * 5 fb.rt.waterprocess.NOT16__Basic$NOT16.alg_REQ()V: I105 Branch 10 IFEQ L220 - false
   * 6 fb.rt.waterprocess.NOT16__Basic$NOT16.alg_REQ()V: I147 Branch 13 IFEQ L223 - false
   * 7 fb.rt.waterprocess.NOT16__Basic$NOT16.alg_REQ()V: I189 Branch 16 IFEQ L226 - false
   * 8 fb.rt.waterprocess.NOT16__Basic$NOT16.alg_REQ()V: I203 Branch 17 IFEQ L227 - true
   */

  @Test
  public void test1()  throws Throwable  {
      NOT16__Basic nOT16__Basic0 = new NOT16__Basic();
      nOT16__Basic0.event_REQ(true, false, true, true, true, true, true, true, false, false, true, false, false, true, false, false);
  }

  //Test case number: 2
  /*
   * 25 covered goals:
   * 1 fb.rt.waterprocess.NOT16__Basic.event_REQ(ZZZZZZZZZZZZZZZZ)V: root-Branch
   * 2 fb.rt.waterprocess.NOT16__Basic.transition_NOT16_1()V: root-Branch
   * 3 fb.rt.waterprocess.NOT16__Basic.transition_NOT16_0()V: root-Branch
   * 4 fb.rt.waterprocess.NOT16__Basic.<init>()V: root-Branch
   * 5 fb.rt.waterprocess.NOT16__Basic$NOT16.state_START()V: root-Branch
   * 6 fb.rt.waterprocess.NOT16__Basic$NOT16.<init>(Lfb/rt/waterprocess/NOT16__Basic;)V: root-Branch
   * 7 fb.rt.waterprocess.NOT16__Basic$NOT16.state_REQ()V: root-Branch
   * 8 fb.rt.waterprocess.NOT16__Basic$NOT16.alg_REQ()V: I7 Branch 3 IFEQ L213 - true
   * 9 fb.rt.waterprocess.NOT16__Basic$NOT16.alg_REQ()V: I21 Branch 4 IFEQ L214 - true
   * 10 fb.rt.waterprocess.NOT16__Basic$NOT16.alg_REQ()V: I35 Branch 5 IFEQ L215 - false
   * 11 fb.rt.waterprocess.NOT16__Basic$NOT16.alg_REQ()V: I49 Branch 6 IFEQ L216 - true
   * 12 fb.rt.waterprocess.NOT16__Basic$NOT16.alg_REQ()V: I63 Branch 7 IFEQ L217 - true
   * 13 fb.rt.waterprocess.NOT16__Basic$NOT16.alg_REQ()V: I77 Branch 8 IFEQ L218 - true
   * 14 fb.rt.waterprocess.NOT16__Basic$NOT16.alg_REQ()V: I91 Branch 9 IFEQ L219 - false
   * 15 fb.rt.waterprocess.NOT16__Basic$NOT16.alg_REQ()V: I105 Branch 10 IFEQ L220 - true
   * 16 fb.rt.waterprocess.NOT16__Basic$NOT16.alg_REQ()V: I119 Branch 11 IFEQ L221 - true
   * 17 fb.rt.waterprocess.NOT16__Basic$NOT16.alg_REQ()V: I133 Branch 12 IFEQ L222 - true
   * 18 fb.rt.waterprocess.NOT16__Basic$NOT16.alg_REQ()V: I147 Branch 13 IFEQ L223 - true
   * 19 fb.rt.waterprocess.NOT16__Basic$NOT16.alg_REQ()V: I161 Branch 14 IFEQ L224 - true
   * 20 fb.rt.waterprocess.NOT16__Basic$NOT16.alg_REQ()V: I175 Branch 15 IFEQ L225 - true
   * 21 fb.rt.waterprocess.NOT16__Basic$NOT16.alg_REQ()V: I189 Branch 16 IFEQ L226 - true
   * 22 fb.rt.waterprocess.NOT16__Basic$NOT16.alg_REQ()V: I203 Branch 17 IFEQ L227 - false
   * 23 fb.rt.waterprocess.NOT16__Basic$NOT16.alg_REQ()V: I217 Branch 18 IFEQ L228 - true
   * 24 fb.rt.waterprocess.NOT16__Basic$NOT16.service_REQ()V: I4 Branch 2 IFNE L205 - false
   * 25 fb.rt.waterprocess.NOT16__Basic$NOT16.serviceEvent(Lfb/rt/EventServer;)V: I5 Branch 1 IF_ACMPNE L200 - false
   */

  @Test
  public void test2()  throws Throwable  {
      NOT16__Basic nOT16__Basic0 = new NOT16__Basic();
      nOT16__Basic0.event_REQ(false, false, true, false, false, false, true, false, false, false, false, false, false, false, true, false);
  }
}
