/*
 * This file was automatically generated by EvoSuite
 * Tue Jan 06 17:31:32 MSK 2015
 */

package fb.rt.waterprocess;

import static org.junit.Assert.*;
import org.junit.Test;
import fb.rt.waterprocess.Service_ADIMeasure__Basic;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.EvoSuiteFile;
import org.junit.runner.RunWith;


public class Service_ADIMeasure__Basic_ESTest {

  //Test case number: 0
  /*
   * 3 covered goals:
   * 1 fb.rt.waterprocess.Service_ADIMeasure__Basic$Service_ADIMeasure.alg_REQ()V: I238 Branch 17 IFGT L216 - true
   * 2 fb.rt.waterprocess.Service_ADIMeasure__Basic$Service_ADIMeasure.alg_REQ()V: I295 Branch 20 IFGT L222 - true
   * 3 fb.rt.waterprocess.Service_ADIMeasure__Basic$Service_ADIMeasure.alg_REQ()V: I305 Branch 21 IFEQ L222 - true
   */

  @Test
  public void test0()  throws Throwable  {
      Service_ADIMeasure__Basic service_ADIMeasure__Basic0 = new Service_ADIMeasure__Basic();
      service_ADIMeasure__Basic0.event_REQ((-67.51192F), false, false, (-56.108566F), (-56.108566F), (-484.22433F), (-484.22433F), (-67.51192F), (-56.108566F));
  }

  //Test case number: 1
  /*
   * 4 covered goals:
   * 1 fb.rt.waterprocess.Service_ADIMeasure__Basic$Service_ADIMeasure.alg_REQ()V: I181 Branch 14 IFGE L210 - false
   * 2 fb.rt.waterprocess.Service_ADIMeasure__Basic$Service_ADIMeasure.alg_REQ()V: I194 Branch 15 IFLT L210 - true
   * 3 fb.rt.waterprocess.Service_ADIMeasure__Basic$Service_ADIMeasure.alg_REQ()V: I251 Branch 18 IFLE L216 - false
   * 4 fb.rt.waterprocess.Service_ADIMeasure__Basic$Service_ADIMeasure.alg_REQ()V: I258 Branch 19 IFEQ L216 - false
   */

  @Test
  public void test1()  throws Throwable  {
      Service_ADIMeasure__Basic service_ADIMeasure__Basic0 = new Service_ADIMeasure__Basic();
      service_ADIMeasure__Basic0.event_REQ((-49.073418F), false, false, 2256.9526F, 2256.9526F, (-49.073418F), (-344.2F), (-344.2F), 2256.9526F);
  }

  //Test case number: 2
  /*
   * 1 covered goal:
   * 1 fb.rt.waterprocess.Service_ADIMeasure__Basic$Service_ADIMeasure.alg_REQ()V: I64 Branch 9 IFLE L195 - false
   */

  @Test
  public void test2()  throws Throwable  {
      Service_ADIMeasure__Basic service_ADIMeasure__Basic0 = new Service_ADIMeasure__Basic();
      service_ADIMeasure__Basic0.event_REQ(2256.9526F, false, false, 2256.9526F, (-344.2F), (-344.2F), (-344.2F), (-344.2F), (-344.2F));
  }

  //Test case number: 3
  /*
   * 4 covered goals:
   * 1 fb.rt.waterprocess.Service_ADIMeasure__Basic$Service_ADIMeasure.alg_REQ()V: I25 Branch 6 IFEQ L195 - false
   * 2 fb.rt.waterprocess.Service_ADIMeasure__Basic$Service_ADIMeasure.alg_REQ()V: I40 Branch 7 IFGT L195 - true
   * 3 fb.rt.waterprocess.Service_ADIMeasure__Basic$Service_ADIMeasure.alg_REQ()V: I134 Branch 12 IFLT L204 - false
   * 4 fb.rt.waterprocess.Service_ADIMeasure__Basic$Service_ADIMeasure.alg_REQ()V: I144 Branch 13 IFEQ L204 - false
   */

  @Test
  public void test3()  throws Throwable  {
      Service_ADIMeasure__Basic service_ADIMeasure__Basic0 = new Service_ADIMeasure__Basic();
      service_ADIMeasure__Basic0.event_REQ(4018.5F, true, false, (-344.2F), (-344.2F), 2256.9526F, 2256.9526F, 2256.9526F, 4018.5F);
  }

  //Test case number: 4
  /*
   * 4 covered goals:
   * 1 fb.rt.waterprocess.Service_ADIMeasure__Basic$Service_ADIMeasure.alg_REQ()V: I16 Branch 5 IFLT L195 - false
   * 2 fb.rt.waterprocess.Service_ADIMeasure__Basic$Service_ADIMeasure.alg_REQ()V: I49 Branch 8 IFEQ L195 - true
   * 3 fb.rt.waterprocess.Service_ADIMeasure__Basic$Service_ADIMeasure.alg_REQ()V: I78 Branch 10 IFGE L195 - false
   * 4 fb.rt.waterprocess.Service_ADIMeasure__Basic$Service_ADIMeasure.alg_REQ()V: I85 Branch 11 IFEQ L195 - false
   */

  @Test
  public void test4()  throws Throwable  {
      Service_ADIMeasure__Basic service_ADIMeasure__Basic0 = new Service_ADIMeasure__Basic();
      service_ADIMeasure__Basic0.event_REQ((-344.2F), false, false, (-344.2F), 2256.9526F, (-344.2F), 2256.9526F, 2256.9526F, (-344.2F));
  }

  //Test case number: 5
  /*
   * 7 covered goals:
   * 1 fb.rt.waterprocess.Service_ADIMeasure__Basic.transition_Service_ADIMeasure_0()V: root-Branch
   * 2 fb.rt.waterprocess.Service_ADIMeasure__Basic.event_INIT(FZZFFFFFF)V: root-Branch
   * 3 fb.rt.waterprocess.Service_ADIMeasure__Basic.transition_Service_ADIMeasure_2()V: root-Branch
   * 4 fb.rt.waterprocess.Service_ADIMeasure__Basic$Service_ADIMeasure.state_INIT()V: root-Branch
   * 5 fb.rt.waterprocess.Service_ADIMeasure__Basic$Service_ADIMeasure.alg_INIT()V: root-Branch
   * 6 fb.rt.waterprocess.Service_ADIMeasure__Basic$Service_ADIMeasure.service_INIT()V: I4 Branch 3 IFNE L167 - false
   * 7 fb.rt.waterprocess.Service_ADIMeasure__Basic$Service_ADIMeasure.serviceEvent(Lfb/rt/EventServer;)V: I5 Branch 1 IF_ACMPNE L161 - false
   */

  @Test
  public void test5()  throws Throwable  {
      Service_ADIMeasure__Basic service_ADIMeasure__Basic0 = new Service_ADIMeasure__Basic();
      service_ADIMeasure__Basic0.event_INIT(2256.9526F, false, false, (-344.2F), 2256.9526F, (-344.2F), 2256.9526F, (-344.2F), (-344.2F));
  }

  //Test case number: 6
  /*
   * 27 covered goals:
   * 1 fb.rt.waterprocess.Service_ADIMeasure__Basic.<init>()V: root-Branch
   * 2 fb.rt.waterprocess.Service_ADIMeasure__Basic.transition_Service_ADIMeasure_3()V: root-Branch
   * 3 fb.rt.waterprocess.Service_ADIMeasure__Basic.event_REQ(FZZFFFFFF)V: root-Branch
   * 4 fb.rt.waterprocess.Service_ADIMeasure__Basic.transition_Service_ADIMeasure_1()V: root-Branch
   * 5 fb.rt.waterprocess.Service_ADIMeasure__Basic$Service_ADIMeasure.state_START()V: root-Branch
   * 6 fb.rt.waterprocess.Service_ADIMeasure__Basic$Service_ADIMeasure.state_REQ()V: root-Branch
   * 7 fb.rt.waterprocess.Service_ADIMeasure__Basic$Service_ADIMeasure.<init>(Lfb/rt/waterprocess/Service_ADIMeasure__Basic;)V: root-Branch
   * 8 fb.rt.waterprocess.Service_ADIMeasure__Basic$Service_ADIMeasure.alg_REQ()V: I16 Branch 5 IFLT L195 - true
   * 9 fb.rt.waterprocess.Service_ADIMeasure__Basic$Service_ADIMeasure.alg_REQ()V: I25 Branch 6 IFEQ L195 - true
   * 10 fb.rt.waterprocess.Service_ADIMeasure__Basic$Service_ADIMeasure.alg_REQ()V: I40 Branch 7 IFGT L195 - false
   * 11 fb.rt.waterprocess.Service_ADIMeasure__Basic$Service_ADIMeasure.alg_REQ()V: I49 Branch 8 IFEQ L195 - false
   * 12 fb.rt.waterprocess.Service_ADIMeasure__Basic$Service_ADIMeasure.alg_REQ()V: I64 Branch 9 IFLE L195 - true
   * 13 fb.rt.waterprocess.Service_ADIMeasure__Basic$Service_ADIMeasure.alg_REQ()V: I78 Branch 10 IFGE L195 - true
   * 14 fb.rt.waterprocess.Service_ADIMeasure__Basic$Service_ADIMeasure.alg_REQ()V: I85 Branch 11 IFEQ L195 - true
   * 15 fb.rt.waterprocess.Service_ADIMeasure__Basic$Service_ADIMeasure.alg_REQ()V: I134 Branch 12 IFLT L204 - true
   * 16 fb.rt.waterprocess.Service_ADIMeasure__Basic$Service_ADIMeasure.alg_REQ()V: I144 Branch 13 IFEQ L204 - true
   * 17 fb.rt.waterprocess.Service_ADIMeasure__Basic$Service_ADIMeasure.alg_REQ()V: I181 Branch 14 IFGE L210 - true
   * 18 fb.rt.waterprocess.Service_ADIMeasure__Basic$Service_ADIMeasure.alg_REQ()V: I194 Branch 15 IFLT L210 - false
   * 19 fb.rt.waterprocess.Service_ADIMeasure__Basic$Service_ADIMeasure.alg_REQ()V: I201 Branch 16 IFEQ L210 - true
   * 20 fb.rt.waterprocess.Service_ADIMeasure__Basic$Service_ADIMeasure.alg_REQ()V: I238 Branch 17 IFGT L216 - false
   * 21 fb.rt.waterprocess.Service_ADIMeasure__Basic$Service_ADIMeasure.alg_REQ()V: I251 Branch 18 IFLE L216 - true
   * 22 fb.rt.waterprocess.Service_ADIMeasure__Basic$Service_ADIMeasure.alg_REQ()V: I258 Branch 19 IFEQ L216 - true
   * 23 fb.rt.waterprocess.Service_ADIMeasure__Basic$Service_ADIMeasure.alg_REQ()V: I295 Branch 20 IFGT L222 - false
   * 24 fb.rt.waterprocess.Service_ADIMeasure__Basic$Service_ADIMeasure.alg_REQ()V: I305 Branch 21 IFEQ L222 - false
   * 25 fb.rt.waterprocess.Service_ADIMeasure__Basic$Service_ADIMeasure.service_REQ()V: I4 Branch 4 IFNE L175 - false
   * 26 fb.rt.waterprocess.Service_ADIMeasure__Basic$Service_ADIMeasure.serviceEvent(Lfb/rt/EventServer;)V: I5 Branch 1 IF_ACMPNE L161 - true
   * 27 fb.rt.waterprocess.Service_ADIMeasure__Basic$Service_ADIMeasure.serviceEvent(Lfb/rt/EventServer;)V: I14 Branch 2 IF_ACMPNE L162 - false
   */

  @Test
  public void test6()  throws Throwable  {
      Service_ADIMeasure__Basic service_ADIMeasure__Basic0 = new Service_ADIMeasure__Basic();
      service_ADIMeasure__Basic0.event_REQ((-2143.8987F), false, true, 3962.0F, (-2143.8987F), 3962.0F, 3962.0F, (-2143.8987F), 3962.0F);
  }
}
