/*
 * This file was automatically generated by EvoSuite
 * Wed Jan 07 07:40:50 MSK 2015
 */

package fb.rt.waterprocess;

import static org.junit.Assert.*;
import org.junit.Test;
import fb.rt.waterprocess.Service_AIMeasure__Basic;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.EvoSuiteFile;
import org.junit.runner.RunWith;


public class Service_AIMeasure__Basic_Tr_ESTest {

  //Test case number: 0
  /*
   * 2 covered goals:
   * 1 fb.rt.waterprocess.Service_AIMeasure__Basic.transition_Service_AIMeasure_1()V: root-Branch
   * 2 fb.rt.waterprocess.Service_AIMeasure__Basic.transition_Service_AIMeasure_3()V: root-Branch
   */

  @Test
  public void test0()  throws Throwable  {
      Service_AIMeasure__Basic service_AIMeasure__Basic0 = new Service_AIMeasure__Basic();
      service_AIMeasure__Basic0.event_REQ((-2485.972F), 2323.7F, (-2485.972F), 34.822365F, 34.822365F, 34.822365F, 34.822365F);
  }

  //Test case number: 1
  /*
   * 2 covered goals:
   * 1 fb.rt.waterprocess.Service_AIMeasure__Basic.transition_Service_AIMeasure_2()V: root-Branch
   * 2 fb.rt.waterprocess.Service_AIMeasure__Basic.transition_Service_AIMeasure_0()V: root-Branch
   */

  @Test
  public void test1()  throws Throwable  {
      Service_AIMeasure__Basic service_AIMeasure__Basic0 = new Service_AIMeasure__Basic();
      service_AIMeasure__Basic0.event_INIT(34.822365F, 34.822365F, 34.822365F, 34.822365F, (-2485.972F), 34.822365F, 34.822365F);
  }
}
