/*
 * This file was automatically generated by EvoSuite
 * Tue Jan 06 17:51:45 MSK 2015
 */

package fb.rt.waterprocess;

import static org.junit.Assert.*;
import org.junit.Test;
import fb.rt.waterprocess.Service_AOControl__Basic;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.EvoSuiteFile;
import org.junit.runner.RunWith;


public class Service_AOControl__Basic_ESTest {

  //Test case number: 0
  /*
   * 1 covered goal:
   * 1 fb.rt.waterprocess.Service_AOControl__Basic$Service_AOControl.alg_REQ()V: I5 Branch 5 IFEQ L141 - false
   */

  @Test
  public void test0()  throws Throwable  {
      Service_AOControl__Basic service_AOControl__Basic0 = new Service_AOControl__Basic();
      service_AOControl__Basic0.event_REQ((-18.144077F), true, (-18.144077F));
  }

  //Test case number: 1
  /*
   * 8 covered goals:
   * 1 fb.rt.waterprocess.Service_AOControl__Basic.event_REQ(FZF)V: root-Branch
   * 2 fb.rt.waterprocess.Service_AOControl__Basic.transition_Service_AOControl_3()V: root-Branch
   * 3 fb.rt.waterprocess.Service_AOControl__Basic.transition_Service_AOControl_1()V: root-Branch
   * 4 fb.rt.waterprocess.Service_AOControl__Basic$Service_AOControl.state_REQ()V: root-Branch
   * 5 fb.rt.waterprocess.Service_AOControl__Basic$Service_AOControl.alg_REQ()V: I5 Branch 5 IFEQ L141 - true
   * 6 fb.rt.waterprocess.Service_AOControl__Basic$Service_AOControl.service_REQ()V: I4 Branch 4 IFNE L125 - false
   * 7 fb.rt.waterprocess.Service_AOControl__Basic$Service_AOControl.serviceEvent(Lfb/rt/EventServer;)V: I5 Branch 1 IF_ACMPNE L111 - true
   * 8 fb.rt.waterprocess.Service_AOControl__Basic$Service_AOControl.serviceEvent(Lfb/rt/EventServer;)V: I14 Branch 2 IF_ACMPNE L112 - false
   */

  @Test
  public void test1()  throws Throwable  {
      Service_AOControl__Basic service_AOControl__Basic0 = new Service_AOControl__Basic();
      service_AOControl__Basic0.event_REQ((-18.144077F), false, (-18.144077F));
  }

  //Test case number: 2
  /*
   * 10 covered goals:
   * 1 fb.rt.waterprocess.Service_AOControl__Basic.transition_Service_AOControl_0()V: root-Branch
   * 2 fb.rt.waterprocess.Service_AOControl__Basic.event_INIT(FZF)V: root-Branch
   * 3 fb.rt.waterprocess.Service_AOControl__Basic.transition_Service_AOControl_2()V: root-Branch
   * 4 fb.rt.waterprocess.Service_AOControl__Basic.<init>()V: root-Branch
   * 5 fb.rt.waterprocess.Service_AOControl__Basic$Service_AOControl.state_START()V: root-Branch
   * 6 fb.rt.waterprocess.Service_AOControl__Basic$Service_AOControl.<init>(Lfb/rt/waterprocess/Service_AOControl__Basic;)V: root-Branch
   * 7 fb.rt.waterprocess.Service_AOControl__Basic$Service_AOControl.alg_INIT()V: root-Branch
   * 8 fb.rt.waterprocess.Service_AOControl__Basic$Service_AOControl.state_INIT()V: root-Branch
   * 9 fb.rt.waterprocess.Service_AOControl__Basic$Service_AOControl.service_INIT()V: I4 Branch 3 IFNE L117 - false
   * 10 fb.rt.waterprocess.Service_AOControl__Basic$Service_AOControl.serviceEvent(Lfb/rt/EventServer;)V: I5 Branch 1 IF_ACMPNE L111 - false
   */

  @Test
  public void test2()  throws Throwable  {
      Service_AOControl__Basic service_AOControl__Basic0 = new Service_AOControl__Basic();
      service_AOControl__Basic0.event_INIT((-18.144077F), true, (-18.144077F));
  }
}
