/*
 * This file was automatically generated by EvoSuite
 * Wed Jan 07 08:31:17 MSK 2015
 */

package fb.rt.waterprocess;

import static org.junit.Assert.*;
import org.junit.Test;
import fb.rt.waterprocess.System_NoOutput__Composite;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.EvoSuiteFile;
import org.junit.runner.RunWith;


public class System_NoOutput__Composite_Tr_ESTest {

  //Test case number: 0
  /*
   * 16 covered goals:
   * 1 fb.rt.waterprocess.System_NoOutput__Composite.transition_FB_PIDControl_3()V: root-Branch
   * 2 fb.rt.waterprocess.System_NoOutput__Composite.transition_NOT3_0()V: root-Branch
   * 3 fb.rt.waterprocess.System_NoOutput__Composite.transition_Service_ADIMeasure_3()V: root-Branch
   * 4 fb.rt.waterprocess.System_NoOutput__Composite.transition_NOT2_1()V: root-Branch
   * 5 fb.rt.waterprocess.System_NoOutput__Composite.transition_Service_AIMeasure_1()V: root-Branch
   * 6 fb.rt.waterprocess.System_NoOutput__Composite.transition_FB_TankControl_1()V: root-Branch
   * 7 fb.rt.waterprocess.System_NoOutput__Composite.transition_NOT1_1()V: root-Branch
   * 8 fb.rt.waterprocess.System_NoOutput__Composite.transition_NOT10_1()V: root-Branch
   * 9 fb.rt.waterprocess.System_NoOutput__Composite.transition_NOT2_0()V: root-Branch
   * 10 fb.rt.waterprocess.System_NoOutput__Composite.transition_NOT1_0()V: root-Branch
   * 11 fb.rt.waterprocess.System_NoOutput__Composite.transition_FB_PIDControl_1()V: root-Branch
   * 12 fb.rt.waterprocess.System_NoOutput__Composite.transition_NOT10_0()V: root-Branch
   * 13 fb.rt.waterprocess.System_NoOutput__Composite.transition_Service_ADIMeasure_1()V: root-Branch
   * 14 fb.rt.waterprocess.System_NoOutput__Composite.transition_Service_AIMeasure_3()V: root-Branch
   * 15 fb.rt.waterprocess.System_NoOutput__Composite.transition_FB_TankControl_3()V: root-Branch
   * 16 fb.rt.waterprocess.System_NoOutput__Composite.transition_NOT3_1()V: root-Branch
   */

  @Test
  public void test0()  throws Throwable  {
      System_NoOutput__Composite system_NoOutput__Composite0 = new System_NoOutput__Composite();
      system_NoOutput__Composite0.event_REQ(277.6F, 277.6F, 277.6F, 277.6F, 277.6F, 277.6F, 277.6F, 277.6F, 277.6F, false, false, false, false, false, false, false, false);
  }

  //Test case number: 1
  /*
   * 22 covered goals:
   * 1 fb.rt.waterprocess.System_NoOutput__Composite.transition_FB_SequenceControl_0()V: root-Branch
   * 2 fb.rt.waterprocess.System_NoOutput__Composite.transition_FB_ValveControl_2()V: root-Branch
   * 3 fb.rt.waterprocess.System_NoOutput__Composite.transition_FB_TankControl_2()V: root-Branch
   * 4 fb.rt.waterprocess.System_NoOutput__Composite.transition_Service_AOControl_2()V: root-Branch
   * 5 fb.rt.waterprocess.System_NoOutput__Composite.transition_FB_PumpControl_2()V: root-Branch
   * 6 fb.rt.waterprocess.System_NoOutput__Composite.transition_FB_InterlockControl_2()V: root-Branch
   * 7 fb.rt.waterprocess.System_NoOutput__Composite.transition_FB_HeaterControl_0()V: root-Branch
   * 8 fb.rt.waterprocess.System_NoOutput__Composite.transition_FB_ValveControl_0()V: root-Branch
   * 9 fb.rt.waterprocess.System_NoOutput__Composite.transition_FB_PIDControl_2()V: root-Branch
   * 10 fb.rt.waterprocess.System_NoOutput__Composite.transition_Service_AIMeasure_2()V: root-Branch
   * 11 fb.rt.waterprocess.System_NoOutput__Composite.transition_Service_ADIMeasure_0()V: root-Branch
   * 12 fb.rt.waterprocess.System_NoOutput__Composite.transition_FB_TankControl_0()V: root-Branch
   * 13 fb.rt.waterprocess.System_NoOutput__Composite.transition_Service_DOControl_2()V: root-Branch
   * 14 fb.rt.waterprocess.System_NoOutput__Composite.transition_Service_AOControl_0()V: root-Branch
   * 15 fb.rt.waterprocess.System_NoOutput__Composite.transition_FB_PumpControl_0()V: root-Branch
   * 16 fb.rt.waterprocess.System_NoOutput__Composite.transition_FB_HeaterControl_2()V: root-Branch
   * 17 fb.rt.waterprocess.System_NoOutput__Composite.transition_FB_InterlockControl_0()V: root-Branch
   * 18 fb.rt.waterprocess.System_NoOutput__Composite.transition_FB_SequenceControl_1()V: root-Branch
   * 19 fb.rt.waterprocess.System_NoOutput__Composite.transition_FB_PIDControl_0()V: root-Branch
   * 20 fb.rt.waterprocess.System_NoOutput__Composite.transition_Service_DOControl_0()V: root-Branch
   * 21 fb.rt.waterprocess.System_NoOutput__Composite.transition_Service_ADIMeasure_2()V: root-Branch
   * 22 fb.rt.waterprocess.System_NoOutput__Composite.transition_Service_AIMeasure_0()V: root-Branch
   */

  @Test
  public void test1()  throws Throwable  {
      System_NoOutput__Composite system_NoOutput__Composite0 = new System_NoOutput__Composite();
      system_NoOutput__Composite0.event_INIT(277.6F, 277.6F, 277.6F, 277.6F, 277.6F, 277.6F, 277.6F, 277.6F, 277.6F, false, false, false, false, false, false, false, false);
  }
}
