/*
 * This file was automatically generated by EvoSuite
 * Tue Jan 06 19:02:32 MSK 2015
 */

package fb.rt.pnp;

import static org.junit.Assert.*;
import org.junit.Test;
import fb.rt.pnp.CylinderMaterSlave__Basic;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.EvoSuiteFile;
import org.junit.runner.RunWith;


public class CylinderMaterSlave__Basic_ESTest {

  //Test case number: 0
  /*
   * 1 covered goal:
   * 1 fb.rt.pnp.CylinderMaterSlave__Basic$CylinderMaterSlave.service_SL_CNF()V: I9 Branch 12 IFEQ L185 - true
   */

  @Test
  public void test0()  throws Throwable  {
      CylinderMaterSlave__Basic cylinderMaterSlave__Basic0 = new CylinderMaterSlave__Basic();
      cylinderMaterSlave__Basic0.event_Extend();
      cylinderMaterSlave__Basic0.event_REQ(true, true, true);
      cylinderMaterSlave__Basic0.event_SL_CNF(false);
  }

  //Test case number: 1
  /*
   * 1 covered goal:
   * 1 fb.rt.pnp.CylinderMaterSlave__Basic$CylinderMaterSlave.service_SL_CNF()V: I5 Branch 11 IF_ICMPNE L185 - true
   */

  @Test
  public void test1()  throws Throwable  {
      CylinderMaterSlave__Basic cylinderMaterSlave__Basic0 = new CylinderMaterSlave__Basic();
      cylinderMaterSlave__Basic0.event_SL_CNF(false);
  }

  //Test case number: 2
  /*
   * 1 covered goal:
   * 1 fb.rt.pnp.CylinderMaterSlave__Basic$CylinderMaterSlave.service_REQ()V: I31 Branch 10 IFEQ L177 - true
   */

  @Test
  public void test2()  throws Throwable  {
      CylinderMaterSlave__Basic cylinderMaterSlave__Basic0 = new CylinderMaterSlave__Basic();
      cylinderMaterSlave__Basic0.event_Retract();
      cylinderMaterSlave__Basic0.event_REQ(false, false, false);
  }

  //Test case number: 3
  /*
   * 2 covered goals:
   * 1 fb.rt.pnp.CylinderMaterSlave__Basic$CylinderMaterSlave.service_REQ()V: I9 Branch 8 IFEQ L173 - true
   * 2 fb.rt.pnp.CylinderMaterSlave__Basic$CylinderMaterSlave.service_REQ()V: I27 Branch 9 IF_ICMPNE L177 - true
   */

  @Test
  public void test3()  throws Throwable  {
      CylinderMaterSlave__Basic cylinderMaterSlave__Basic0 = new CylinderMaterSlave__Basic();
      cylinderMaterSlave__Basic0.event_Extend();
      cylinderMaterSlave__Basic0.event_REQ(false, false, false);
  }

  //Test case number: 4
  /*
   * 1 covered goal:
   * 1 fb.rt.pnp.CylinderMaterSlave__Basic$CylinderMaterSlave.service_Retract()V: I4 Branch 6 IFNE L165 - true
   */

  @Test
  public void test4()  throws Throwable  {
      CylinderMaterSlave__Basic cylinderMaterSlave__Basic0 = new CylinderMaterSlave__Basic();
      cylinderMaterSlave__Basic0.event_Extend();
      cylinderMaterSlave__Basic0.event_Retract();
  }

  //Test case number: 5
  /*
   * 1 covered goal:
   * 1 fb.rt.pnp.CylinderMaterSlave__Basic$CylinderMaterSlave.service_Extend()V: I4 Branch 5 IFNE L157 - true
   */

  @Test
  public void test5()  throws Throwable  {
      CylinderMaterSlave__Basic cylinderMaterSlave__Basic0 = new CylinderMaterSlave__Basic();
      cylinderMaterSlave__Basic0.event_Retract();
      cylinderMaterSlave__Basic0.event_Extend();
  }

  //Test case number: 6
  /*
   * 17 covered goals:
   * 1 fb.rt.pnp.CylinderMaterSlave__Basic.event_Extend()V: root-Branch
   * 2 fb.rt.pnp.CylinderMaterSlave__Basic.transition_CylinderMaterSlave_3()V: root-Branch
   * 3 fb.rt.pnp.CylinderMaterSlave__Basic.transition_CylinderMaterSlave_1()V: root-Branch
   * 4 fb.rt.pnp.CylinderMaterSlave__Basic.transition_CylinderMaterSlave_5()V: root-Branch
   * 5 fb.rt.pnp.CylinderMaterSlave__Basic.event_SL_CNF(Z)V: root-Branch
   * 6 fb.rt.pnp.CylinderMaterSlave__Basic$CylinderMaterSlave.state_End()V: root-Branch
   * 7 fb.rt.pnp.CylinderMaterSlave__Basic$CylinderMaterSlave.alg_Extend()V: root-Branch
   * 8 fb.rt.pnp.CylinderMaterSlave__Basic$CylinderMaterSlave.alg_End()V: root-Branch
   * 9 fb.rt.pnp.CylinderMaterSlave__Basic$CylinderMaterSlave.state_Extend()V: root-Branch
   * 10 fb.rt.pnp.CylinderMaterSlave__Basic$CylinderMaterSlave.service_REQ()V: I5 Branch 7 IF_ICMPNE L173 - false
   * 11 fb.rt.pnp.CylinderMaterSlave__Basic$CylinderMaterSlave.service_REQ()V: I9 Branch 8 IFEQ L173 - false
   * 12 fb.rt.pnp.CylinderMaterSlave__Basic$CylinderMaterSlave.service_SL_CNF()V: I5 Branch 11 IF_ICMPNE L185 - false
   * 13 fb.rt.pnp.CylinderMaterSlave__Basic$CylinderMaterSlave.service_SL_CNF()V: I9 Branch 12 IFEQ L185 - false
   * 14 fb.rt.pnp.CylinderMaterSlave__Basic$CylinderMaterSlave.serviceEvent(Lfb/rt/EventServer;)V: I5 Branch 1 IF_ACMPNE L149 - false
   * 15 fb.rt.pnp.CylinderMaterSlave__Basic$CylinderMaterSlave.serviceEvent(Lfb/rt/EventServer;)V: I23 Branch 3 IF_ACMPNE L151 - true
   * 16 fb.rt.pnp.CylinderMaterSlave__Basic$CylinderMaterSlave.serviceEvent(Lfb/rt/EventServer;)V: I32 Branch 4 IF_ACMPNE L152 - false
   * 17 fb.rt.pnp.CylinderMaterSlave__Basic$CylinderMaterSlave.service_Extend()V: I4 Branch 5 IFNE L157 - false
   */

  @Test
  public void test6()  throws Throwable  {
      CylinderMaterSlave__Basic cylinderMaterSlave__Basic0 = new CylinderMaterSlave__Basic();
      cylinderMaterSlave__Basic0.event_Extend();
      cylinderMaterSlave__Basic0.event_REQ(true, true, true);
      cylinderMaterSlave__Basic0.event_SL_CNF(true);
  }

  //Test case number: 7
  /*
   * 21 covered goals:
   * 1 fb.rt.pnp.CylinderMaterSlave__Basic.event_Retract()V: root-Branch
   * 2 fb.rt.pnp.CylinderMaterSlave__Basic.transition_CylinderMaterSlave_4()V: root-Branch
   * 3 fb.rt.pnp.CylinderMaterSlave__Basic.transition_CylinderMaterSlave_2()V: root-Branch
   * 4 fb.rt.pnp.CylinderMaterSlave__Basic.<init>()V: root-Branch
   * 5 fb.rt.pnp.CylinderMaterSlave__Basic.event_REQ(ZZZ)V: root-Branch
   * 6 fb.rt.pnp.CylinderMaterSlave__Basic.transition_CylinderMaterSlave_0()V: root-Branch
   * 7 fb.rt.pnp.CylinderMaterSlave__Basic$CylinderMaterSlave.state_Retract()V: root-Branch
   * 8 fb.rt.pnp.CylinderMaterSlave__Basic$CylinderMaterSlave.state_Home()V: root-Branch
   * 9 fb.rt.pnp.CylinderMaterSlave__Basic$CylinderMaterSlave.alg_Home()V: root-Branch
   * 10 fb.rt.pnp.CylinderMaterSlave__Basic$CylinderMaterSlave.<init>(Lfb/rt/pnp/CylinderMaterSlave__Basic;)V: root-Branch
   * 11 fb.rt.pnp.CylinderMaterSlave__Basic$CylinderMaterSlave.state_START()V: root-Branch
   * 12 fb.rt.pnp.CylinderMaterSlave__Basic$CylinderMaterSlave.alg_Retract()V: root-Branch
   * 13 fb.rt.pnp.CylinderMaterSlave__Basic$CylinderMaterSlave.alg_Test()V: root-Branch
   * 14 fb.rt.pnp.CylinderMaterSlave__Basic$CylinderMaterSlave.service_Retract()V: I4 Branch 6 IFNE L165 - false
   * 15 fb.rt.pnp.CylinderMaterSlave__Basic$CylinderMaterSlave.service_REQ()V: I5 Branch 7 IF_ICMPNE L173 - true
   * 16 fb.rt.pnp.CylinderMaterSlave__Basic$CylinderMaterSlave.service_REQ()V: I27 Branch 9 IF_ICMPNE L177 - false
   * 17 fb.rt.pnp.CylinderMaterSlave__Basic$CylinderMaterSlave.service_REQ()V: I31 Branch 10 IFEQ L177 - false
   * 18 fb.rt.pnp.CylinderMaterSlave__Basic$CylinderMaterSlave.serviceEvent(Lfb/rt/EventServer;)V: I5 Branch 1 IF_ACMPNE L149 - true
   * 19 fb.rt.pnp.CylinderMaterSlave__Basic$CylinderMaterSlave.serviceEvent(Lfb/rt/EventServer;)V: I14 Branch 2 IF_ACMPNE L150 - true
   * 20 fb.rt.pnp.CylinderMaterSlave__Basic$CylinderMaterSlave.serviceEvent(Lfb/rt/EventServer;)V: I14 Branch 2 IF_ACMPNE L150 - false
   * 21 fb.rt.pnp.CylinderMaterSlave__Basic$CylinderMaterSlave.serviceEvent(Lfb/rt/EventServer;)V: I23 Branch 3 IF_ACMPNE L151 - false
   */

  @Test
  public void test7()  throws Throwable  {
      CylinderMaterSlave__Basic cylinderMaterSlave__Basic0 = new CylinderMaterSlave__Basic();
      cylinderMaterSlave__Basic0.event_Retract();
      cylinderMaterSlave__Basic0.event_REQ(true, true, true);
  }
}
