/*
 * This file was automatically generated by EvoSuite
 * Wed Jan 07 09:11:43 MSK 2015
 */

package fb.rt.pnp;

import static org.junit.Assert.*;
import org.junit.Test;
import fb.rt.pnp.E_Split4__Basic;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.EvoSuiteFile;
import org.junit.runner.RunWith;


public class E_Split4__Basic_Tr_ESTest {

  //Test case number: 0
  /*
   * 2 covered goals:
   * 1 fb.rt.pnp.E_Split4__Basic.transition_E_Split4_1()V: root-Branch
   * 2 fb.rt.pnp.E_Split4__Basic.transition_E_Split4_0()V: root-Branch
   */

  @Test
  public void test0()  throws Throwable  {
      E_Split4__Basic e_Split4__Basic0 = new E_Split4__Basic();
      e_Split4__Basic0.event_E();
  }
}
