/*
 * This file was automatically generated by EvoSuite
 * Wed Jan 07 10:42:45 MSK 2015
 */

package fb.rt.pnp;

import static org.junit.Assert.*;
import org.junit.Test;
import fb.rt.pnp.MachadoSFC__Composite;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.EvoSuiteFile;
import org.junit.runner.RunWith;


public class MachadoSFC__Composite_Tr_ESTest {

  //Test case number: 0
  /*
   * 3 covered goals:
   * 1 fb.rt.pnp.MachadoSFC__Composite.transition_SFC1_7()V: root-Branch
   * 2 fb.rt.pnp.MachadoSFC__Composite.transition_SFC1_4()V: root-Branch
   * 3 fb.rt.pnp.MachadoSFC__Composite.transition_SFC2_3()V: root-Branch
   */

  @Test
  public void test0()  throws Throwable  {
      MachadoSFC__Composite machadoSFC__Composite0 = new MachadoSFC__Composite();
      machadoSFC__Composite0.event_INIT(false, true, false, false, false, false, false, false, false, false, false);
      machadoSFC__Composite0.event_REQ(false, false, false, false, false, false, false, false, false, true, false);
      machadoSFC__Composite0.event_REQ(false, true, false, false, false, false, false, true, false, false, false);
  }

  //Test case number: 1
  /*
   * 2 covered goals:
   * 1 fb.rt.pnp.MachadoSFC__Composite.transition_SFC1_3()V: root-Branch
   * 2 fb.rt.pnp.MachadoSFC__Composite.transition_SFC1_6()V: root-Branch
   */

  @Test
  public void test1()  throws Throwable  {
      MachadoSFC__Composite machadoSFC__Composite0 = new MachadoSFC__Composite();
      machadoSFC__Composite0.event_REQ(false, false, false, false, false, true, false, false, true, false, false);
      machadoSFC__Composite0.event_REQ(false, false, false, false, false, false, false, false, false, false, true);
  }

  //Test case number: 2
  /*
   * 5 covered goals:
   * 1 fb.rt.pnp.MachadoSFC__Composite.transition_SFC4_7()V: root-Branch
   * 2 fb.rt.pnp.MachadoSFC__Composite.transition_SFC4_5()V: root-Branch
   * 3 fb.rt.pnp.MachadoSFC__Composite.transition_SFC4_9()V: root-Branch
   * 4 fb.rt.pnp.MachadoSFC__Composite.transition_SFC4_4()V: root-Branch
   * 5 fb.rt.pnp.MachadoSFC__Composite.transition_SFC4_6()V: root-Branch
   */

  @Test
  public void test2()  throws Throwable  {
      MachadoSFC__Composite machadoSFC__Composite0 = new MachadoSFC__Composite();
      machadoSFC__Composite0.event_INIT(true, true, true, true, true, true, true, false, false, true, true);
      machadoSFC__Composite0.event_INIT(true, true, true, true, true, false, false, true, true, true, false);
      machadoSFC__Composite0.event_INIT(true, true, true, true, false, true, true, true, true, true, false);
      machadoSFC__Composite0.event_INIT(true, true, true, true, true, true, true, true, true, true, true);
  }

  //Test case number: 3
  /*
   * 13 covered goals:
   * 1 fb.rt.pnp.MachadoSFC__Composite.transition_SFC1_5()V: root-Branch
   * 2 fb.rt.pnp.MachadoSFC__Composite.transition_SFC4_3()V: root-Branch
   * 3 fb.rt.pnp.MachadoSFC__Composite.transition_SFC4_1()V: root-Branch
   * 4 fb.rt.pnp.MachadoSFC__Composite.transition_SFC2_2()V: root-Branch
   * 5 fb.rt.pnp.MachadoSFC__Composite.transition_SFC2_0()V: root-Branch
   * 6 fb.rt.pnp.MachadoSFC__Composite.transition_SFC1_1()V: root-Branch
   * 7 fb.rt.pnp.MachadoSFC__Composite.transition_SFC4_2()V: root-Branch
   * 8 fb.rt.pnp.MachadoSFC__Composite.transition_SFC4_8()V: root-Branch
   * 9 fb.rt.pnp.MachadoSFC__Composite.transition_SFC2_1()V: root-Branch
   * 10 fb.rt.pnp.MachadoSFC__Composite.transition_SFC4_10()V: root-Branch
   * 11 fb.rt.pnp.MachadoSFC__Composite.transition_SFC4_0()V: root-Branch
   * 12 fb.rt.pnp.MachadoSFC__Composite.transition_SFC1_2()V: root-Branch
   * 13 fb.rt.pnp.MachadoSFC__Composite.transition_SFC1_0()V: root-Branch
   */

  @Test
  public void test3()  throws Throwable  {
      MachadoSFC__Composite machadoSFC__Composite0 = new MachadoSFC__Composite();
      machadoSFC__Composite0.event_INIT(false, false, false, false, false, false, false, false, false, false, false);
      machadoSFC__Composite0.event_REQ(false, false, false, false, true, true, true, true, false, false, false);
      machadoSFC__Composite0.event_REQ(false, false, false, false, false, false, false, false, false, false, true);
  }
}
