/*
 * This file was automatically generated by EvoSuite
 * Tue Jan 06 21:54:20 MSK 2015
 */

package fb.rt.pnp;

import static org.junit.Assert.*;
import org.junit.Test;
import fb.rt.pnp.Master_TEST__Basic;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.EvoSuiteFile;
import org.junit.runner.RunWith;


public class Master_TEST__Basic_ESTest {

  //Test case number: 0
  /*
   * 1 covered goal:
   * 1 fb.rt.pnp.Master_TEST__Basic$Master_TEST.service_REQ()V: I418 Branch 38 IFEQ L308 - true
   */

  @Test
  public void test00()  throws Throwable  {
      Master_TEST__Basic master_TEST__Basic0 = new Master_TEST__Basic();
      master_TEST__Basic0.event_REQ(false, false, false, false, true, false, false, 1054.0F, 1054.0F);
      master_TEST__Basic0.event_REQ(false, false, false, false, false, false, false, 1054.0F, 1054.0F);
  }

  //Test case number: 1
  /*
   * 1 covered goal:
   * 1 fb.rt.pnp.Master_TEST__Basic$Master_TEST.service_REQ()V: I392 Branch 36 IFEQ L304 - true
   */

  @Test
  public void test01()  throws Throwable  {
      Master_TEST__Basic master_TEST__Basic0 = new Master_TEST__Basic();
      master_TEST__Basic0.event_REQ(false, false, true, false, true, false, true, (-3335.9954F), (-3335.9954F));
      master_TEST__Basic0.event_REQ(false, false, false, true, true, true, true, (-3335.9954F), (-3335.9954F));
      master_TEST__Basic0.event_REQ(true, false, true, true, false, true, true, (-3335.9954F), (-3335.9954F));
      master_TEST__Basic0.event_REQ(true, true, true, true, true, false, true, (-3335.9954F), (-3335.9954F));
  }

  //Test case number: 2
  /*
   * 1 covered goal:
   * 1 fb.rt.pnp.Master_TEST__Basic$Master_TEST.service_REQ()V: I366 Branch 34 IFEQ L300 - true
   */

  @Test
  public void test02()  throws Throwable  {
      Master_TEST__Basic master_TEST__Basic0 = new Master_TEST__Basic();
      master_TEST__Basic0.event_REQ(false, false, false, true, false, true, false, 0.0F, 0.0F);
      master_TEST__Basic0.event_REQ(true, false, true, false, true, true, true, 0.0F, 0.0F);
      master_TEST__Basic0.event_REQ(true, true, true, false, true, true, true, 0.0F, 0.0F);
      master_TEST__Basic0.event_REQ(true, true, true, false, true, true, false, 0.0F, 0.0F);
  }

  //Test case number: 3
  /*
   * 1 covered goal:
   * 1 fb.rt.pnp.Master_TEST__Basic$Master_TEST.service_REQ()V: I340 Branch 32 IFEQ L296 - true
   */

  @Test
  public void test03()  throws Throwable  {
      Master_TEST__Basic master_TEST__Basic0 = new Master_TEST__Basic();
      master_TEST__Basic0.event_REQ(false, false, false, true, false, true, false, (-25.6F), (-25.6F));
      master_TEST__Basic0.event_REQ(false, false, true, false, true, true, true, (-25.6F), (-25.6F));
      master_TEST__Basic0.event_REQ(false, false, false, false, false, true, false, (-25.6F), (-25.6F));
  }

  //Test case number: 4
  /*
   * 1 covered goal:
   * 1 fb.rt.pnp.Master_TEST__Basic$Master_TEST.service_REQ()V: I314 Branch 30 IFEQ L292 - true
   */

  @Test
  public void test04()  throws Throwable  {
      Master_TEST__Basic master_TEST__Basic0 = new Master_TEST__Basic();
      master_TEST__Basic0.event_REQ(false, false, false, true, false, true, false, 0.0F, 0.0F);
      master_TEST__Basic0.event_REQ(false, true, true, false, false, false, false, 0.0F, 0.0F);
  }

  //Test case number: 5
  /*
   * 1 covered goal:
   * 1 fb.rt.pnp.Master_TEST__Basic$Master_TEST.service_REQ()V: I288 Branch 28 IFEQ L288 - true
   */

  @Test
  public void test05()  throws Throwable  {
      Master_TEST__Basic master_TEST__Basic0 = new Master_TEST__Basic();
      master_TEST__Basic0.event_REQ(true, false, true, false, true, false, true, (-196.59512F), (-196.59512F));
      master_TEST__Basic0.event_REQ(false, false, false, false, true, true, true, (-196.59512F), (-196.59512F));
      master_TEST__Basic0.event_REQ(false, false, false, false, false, false, false, (-196.59512F), (-196.59512F));
  }

  //Test case number: 6
  /*
   * 1 covered goal:
   * 1 fb.rt.pnp.Master_TEST__Basic$Master_TEST.service_REQ()V: I262 Branch 26 IFEQ L284 - true
   */

  @Test
  public void test06()  throws Throwable  {
      Master_TEST__Basic master_TEST__Basic0 = new Master_TEST__Basic();
      master_TEST__Basic0.event_REQ(false, false, true, true, true, true, true, (-878.7009F), (-878.7009F));
      master_TEST__Basic0.event_REQ(true, true, true, true, true, true, false, (-878.7009F), (-878.7009F));
  }

  //Test case number: 7
  /*
   * 1 covered goal:
   * 1 fb.rt.pnp.Master_TEST__Basic$Master_TEST.service_REQ()V: I164 Branch 17 IFEQ L272 - true
   */

  @Test
  public void test07()  throws Throwable  {
      Master_TEST__Basic master_TEST__Basic0 = new Master_TEST__Basic();
      master_TEST__Basic0.event_REQ(true, true, true, true, true, true, false, 1.0F, 1.0F);
      master_TEST__Basic0.event_REQ(true, true, true, true, true, true, true, 1.0F, 1.0F);
      master_TEST__Basic0.event_REQ(true, true, true, true, true, true, true, 1.0F, 1.0F);
      master_TEST__Basic0.event_REQ(true, true, true, true, true, true, true, 1.0F, 1.0F);
      master_TEST__Basic0.event_REQ(true, true, true, true, true, true, true, 1.0F, 1.0F);
      master_TEST__Basic0.event_REQ(true, true, false, true, false, true, true, 1.0F, 1.0F);
      master_TEST__Basic0.event_REQ(false, true, true, false, false, true, false, 1.0F, 1.0F);
  }

  //Test case number: 8
  /*
   * 17 covered goals:
   * 1 fb.rt.pnp.Master_TEST__Basic$Master_TEST.alg_Go_3_0()V: root-Branch
   * 2 fb.rt.pnp.Master_TEST__Basic$Master_TEST.state_Pick2_3()V: root-Branch
   * 3 fb.rt.pnp.Master_TEST__Basic$Master_TEST.state_Pick2_1()V: root-Branch
   * 4 fb.rt.pnp.Master_TEST__Basic$Master_TEST.alg_Go_3_3()V: root-Branch
   * 5 fb.rt.pnp.Master_TEST__Basic$Master_TEST.state_Pick2_2()V: root-Branch
   * 6 fb.rt.pnp.Master_TEST__Basic$Master_TEST.service_REQ()V: I138 Branch 15 IFEQ L268 - true
   * 7 fb.rt.pnp.Master_TEST__Basic$Master_TEST.service_REQ()V: I195 Branch 20 IFEQ L276 - false
   * 8 fb.rt.pnp.Master_TEST__Basic$Master_TEST.service_REQ()V: I254 Branch 25 IF_ICMPNE L284 - false
   * 9 fb.rt.pnp.Master_TEST__Basic$Master_TEST.service_REQ()V: I262 Branch 26 IFEQ L284 - false
   * 10 fb.rt.pnp.Master_TEST__Basic$Master_TEST.service_REQ()V: I280 Branch 27 IF_ICMPNE L288 - false
   * 11 fb.rt.pnp.Master_TEST__Basic$Master_TEST.service_REQ()V: I288 Branch 28 IFEQ L288 - false
   * 12 fb.rt.pnp.Master_TEST__Basic$Master_TEST.service_REQ()V: I384 Branch 35 IF_ICMPNE L304 - false
   * 13 fb.rt.pnp.Master_TEST__Basic$Master_TEST.service_REQ()V: I392 Branch 36 IFEQ L304 - false
   * 14 fb.rt.pnp.Master_TEST__Basic.transition_Master_TEST_11()V: root-Branch
   * 15 fb.rt.pnp.Master_TEST__Basic.transition_Master_TEST_12()V: root-Branch
   * 16 fb.rt.pnp.Master_TEST__Basic.transition_Master_TEST_9()V: root-Branch
   * 17 fb.rt.pnp.Master_TEST__Basic.transition_Master_TEST_16()V: root-Branch
   */

  @Test
  public void test08()  throws Throwable  {
      Master_TEST__Basic master_TEST__Basic0 = new Master_TEST__Basic();
      master_TEST__Basic0.event_REQ(true, false, true, false, true, false, true, (-196.59512F), (-196.59512F));
      master_TEST__Basic0.event_REQ(false, false, false, false, true, true, true, (-196.59512F), (-196.59512F));
      master_TEST__Basic0.event_REQ(false, true, false, false, false, true, true, (-196.59512F), (-196.59512F));
      master_TEST__Basic0.event_REQ(true, true, true, false, true, true, true, (-196.59512F), (-196.59512F));
      master_TEST__Basic0.event_REQ(true, false, false, true, false, true, true, (-196.59512F), (-196.59512F));
      master_TEST__Basic0.event_REQ(false, false, false, true, true, false, false, (-196.59512F), (-196.59512F));
  }

  //Test case number: 9
  /*
   * 13 covered goals:
   * 1 fb.rt.pnp.Master_TEST__Basic$Master_TEST.state_Pick3_2()V: root-Branch
   * 2 fb.rt.pnp.Master_TEST__Basic$Master_TEST.state_Pick3_3()V: root-Branch
   * 3 fb.rt.pnp.Master_TEST__Basic$Master_TEST.alg_Go_4_2()V: root-Branch
   * 4 fb.rt.pnp.Master_TEST__Basic$Master_TEST.service_REQ()V: I112 Branch 13 IFEQ L264 - true
   * 5 fb.rt.pnp.Master_TEST__Basic$Master_TEST.service_REQ()V: I306 Branch 29 IF_ICMPNE L292 - false
   * 6 fb.rt.pnp.Master_TEST__Basic$Master_TEST.service_REQ()V: I314 Branch 30 IFEQ L292 - false
   * 7 fb.rt.pnp.Master_TEST__Basic$Master_TEST.service_REQ()V: I332 Branch 31 IF_ICMPNE L296 - false
   * 8 fb.rt.pnp.Master_TEST__Basic$Master_TEST.service_REQ()V: I340 Branch 32 IFEQ L296 - false
   * 9 fb.rt.pnp.Master_TEST__Basic$Master_TEST.service_REQ()V: I358 Branch 33 IF_ICMPNE L300 - false
   * 10 fb.rt.pnp.Master_TEST__Basic$Master_TEST.service_REQ()V: I366 Branch 34 IFEQ L300 - false
   * 11 fb.rt.pnp.Master_TEST__Basic.transition_Master_TEST_13()V: root-Branch
   * 12 fb.rt.pnp.Master_TEST__Basic.transition_Master_TEST_14()V: root-Branch
   * 13 fb.rt.pnp.Master_TEST__Basic.transition_Master_TEST_15()V: root-Branch
   */

  @Test
  public void test09()  throws Throwable  {
      Master_TEST__Basic master_TEST__Basic0 = new Master_TEST__Basic();
      master_TEST__Basic0.event_REQ(false, false, false, true, false, true, false, (-25.6F), (-25.6F));
      master_TEST__Basic0.event_REQ(false, false, true, false, true, true, true, (-25.6F), (-25.6F));
      master_TEST__Basic0.event_REQ(true, false, true, false, true, true, true, (-25.6F), (-25.6F));
      master_TEST__Basic0.event_REQ(true, false, false, true, true, true, true, (-25.6F), (-25.6F));
      master_TEST__Basic0.event_REQ(true, true, false, true, false, false, false, (-25.6F), (-25.6F));
  }

  //Test case number: 10
  /*
   * 1 covered goal:
   * 1 fb.rt.pnp.Master_TEST__Basic$Master_TEST.service_REQ()V: I86 Branch 11 IFEQ L260 - true
   */

  @Test
  public void test10()  throws Throwable  {
      Master_TEST__Basic master_TEST__Basic0 = new Master_TEST__Basic();
      master_TEST__Basic0.event_REQ(true, true, true, true, true, false, true, (-16.524693F), (-16.524693F));
      master_TEST__Basic0.event_REQ(true, true, true, true, true, true, true, (-16.524693F), (-16.524693F));
      master_TEST__Basic0.event_REQ(true, true, true, true, true, true, true, (-16.524693F), (-16.524693F));
      master_TEST__Basic0.event_REQ(true, true, false, true, true, false, true, (-16.524693F), (-16.524693F));
  }

  //Test case number: 11
  /*
   * 1 covered goal:
   * 1 fb.rt.pnp.Master_TEST__Basic$Master_TEST.service_REQ()V: I60 Branch 9 IFEQ L256 - true
   */

  @Test
  public void test11()  throws Throwable  {
      Master_TEST__Basic master_TEST__Basic0 = new Master_TEST__Basic();
      master_TEST__Basic0.event_REQ(true, true, true, true, true, false, true, (-16.524693F), (-16.524693F));
      master_TEST__Basic0.event_REQ(true, true, true, true, true, true, true, (-16.524693F), (-16.524693F));
      master_TEST__Basic0.event_REQ(false, true, true, true, true, false, false, (-16.524693F), (-16.524693F));
  }

  //Test case number: 12
  /*
   * 2 covered goals:
   * 1 fb.rt.pnp.Master_TEST__Basic$Master_TEST.service_REQ()V: I34 Branch 7 IFEQ L252 - true
   * 2 fb.rt.pnp.Master_TEST__Basic$Master_TEST.service_REQ()V: I435 Branch 39 IFNE L312 - true
   */

  @Test
  public void test12()  throws Throwable  {
      Master_TEST__Basic master_TEST__Basic0 = new Master_TEST__Basic();
      master_TEST__Basic0.event_REQ(true, true, true, true, true, false, true, (-16.524693F), (-16.524693F));
      master_TEST__Basic0.event_REQ(false, false, false, true, true, false, false, (-16.524693F), (-16.524693F));
  }

  //Test case number: 13
  /*
   * 5 covered goals:
   * 1 fb.rt.pnp.Master_TEST__Basic$Master_TEST.alg_Go_4_0()V: root-Branch
   * 2 fb.rt.pnp.Master_TEST__Basic$Master_TEST.state_Pick3_1()V: root-Branch
   * 3 fb.rt.pnp.Master_TEST__Basic$Master_TEST.service_REQ()V: I236 Branch 24 IFEQ L280 - false
   * 4 fb.rt.pnp.Master_TEST__Basic$Master_TEST.service_INIT()V: I4 Branch 3 IFNE L240 - true
   * 5 fb.rt.pnp.Master_TEST__Basic.transition_Master_TEST_10()V: root-Branch
   */

  @Test
  public void test13()  throws Throwable  {
      Master_TEST__Basic master_TEST__Basic0 = new Master_TEST__Basic();
      master_TEST__Basic0.event_REQ(false, false, false, true, false, true, false, 0.0F, 0.0F);
      master_TEST__Basic0.event_INIT(true, true, true, true, true, true, false, 0.0F, 0.0F);
  }

  //Test case number: 14
  /*
   * 29 covered goals:
   * 1 fb.rt.pnp.Master_TEST__Basic$Master_TEST.alg_Go_0_0()V: root-Branch
   * 2 fb.rt.pnp.Master_TEST__Basic$Master_TEST.state_Go_sleep()V: root-Branch
   * 3 fb.rt.pnp.Master_TEST__Basic$Master_TEST.service_REQ()V: I8 Branch 5 IFEQ L248 - true
   * 4 fb.rt.pnp.Master_TEST__Basic$Master_TEST.service_REQ()V: I156 Branch 16 IF_ICMPNE L272 - true
   * 5 fb.rt.pnp.Master_TEST__Basic$Master_TEST.service_REQ()V: I181 Branch 18 IFNE L276 - true
   * 6 fb.rt.pnp.Master_TEST__Basic$Master_TEST.service_REQ()V: I181 Branch 18 IFNE L276 - false
   * 7 fb.rt.pnp.Master_TEST__Basic$Master_TEST.service_REQ()V: I188 Branch 19 IFEQ L276 - true
   * 8 fb.rt.pnp.Master_TEST__Basic$Master_TEST.service_REQ()V: I195 Branch 20 IFEQ L276 - true
   * 9 fb.rt.pnp.Master_TEST__Basic$Master_TEST.service_REQ()V: I212 Branch 21 IFNE L280 - true
   * 10 fb.rt.pnp.Master_TEST__Basic$Master_TEST.service_REQ()V: I212 Branch 21 IFNE L280 - false
   * 11 fb.rt.pnp.Master_TEST__Basic$Master_TEST.service_REQ()V: I219 Branch 22 IFEQ L280 - true
   * 12 fb.rt.pnp.Master_TEST__Basic$Master_TEST.service_REQ()V: I229 Branch 23 IFEQ L280 - true
   * 13 fb.rt.pnp.Master_TEST__Basic$Master_TEST.service_REQ()V: I236 Branch 24 IFEQ L280 - true
   * 14 fb.rt.pnp.Master_TEST__Basic$Master_TEST.service_REQ()V: I254 Branch 25 IF_ICMPNE L284 - true
   * 15 fb.rt.pnp.Master_TEST__Basic$Master_TEST.service_REQ()V: I280 Branch 27 IF_ICMPNE L288 - true
   * 16 fb.rt.pnp.Master_TEST__Basic$Master_TEST.service_REQ()V: I306 Branch 29 IF_ICMPNE L292 - true
   * 17 fb.rt.pnp.Master_TEST__Basic$Master_TEST.service_REQ()V: I332 Branch 31 IF_ICMPNE L296 - true
   * 18 fb.rt.pnp.Master_TEST__Basic$Master_TEST.service_REQ()V: I358 Branch 33 IF_ICMPNE L300 - true
   * 19 fb.rt.pnp.Master_TEST__Basic$Master_TEST.service_REQ()V: I384 Branch 35 IF_ICMPNE L304 - true
   * 20 fb.rt.pnp.Master_TEST__Basic$Master_TEST.service_REQ()V: I410 Branch 37 IF_ICMPNE L308 - true
   * 21 fb.rt.pnp.Master_TEST__Basic$Master_TEST.service_REQ()V: I410 Branch 37 IF_ICMPNE L308 - false
   * 22 fb.rt.pnp.Master_TEST__Basic$Master_TEST.service_REQ()V: I418 Branch 38 IFEQ L308 - false
   * 23 fb.rt.pnp.Master_TEST__Basic$Master_TEST.service_REQ()V: I435 Branch 39 IFNE L312 - false
   * 24 fb.rt.pnp.Master_TEST__Basic$Master_TEST.service_REQ()V: I439 Branch 40 IFEQ L312 - true
   * 25 fb.rt.pnp.Master_TEST__Basic$Master_TEST.service_REQ()V: I448 Branch 41 IFEQ L312 - true
   * 26 fb.rt.pnp.Master_TEST__Basic$Master_TEST.service_REQ()V: I458 Branch 42 IFEQ L312 - true
   * 27 fb.rt.pnp.Master_TEST__Basic$Master_TEST.service_REQ()V: I465 Branch 43 IFEQ L312 - false
   * 28 fb.rt.pnp.Master_TEST__Basic.transition_Master_TEST_18()V: root-Branch
   * 29 fb.rt.pnp.Master_TEST__Basic.transition_Master_TEST_17()V: root-Branch
   */

  @Test
  public void test14()  throws Throwable  {
      Master_TEST__Basic master_TEST__Basic0 = new Master_TEST__Basic();
      master_TEST__Basic0.event_REQ(false, false, false, false, true, false, false, 1054.0F, 1054.0F);
      master_TEST__Basic0.event_REQ(false, false, false, false, false, true, true, 1054.0F, 1054.0F);
  }

  //Test case number: 15
  /*
   * 42 covered goals:
   * 1 fb.rt.pnp.Master_TEST__Basic$Master_TEST.state_Deposit_1()V: root-Branch
   * 2 fb.rt.pnp.Master_TEST__Basic$Master_TEST.alg_Go_1_1()V: root-Branch
   * 3 fb.rt.pnp.Master_TEST__Basic$Master_TEST.state_Pick1_1()V: root-Branch
   * 4 fb.rt.pnp.Master_TEST__Basic$Master_TEST.state_Pick1_3()V: root-Branch
   * 5 fb.rt.pnp.Master_TEST__Basic$Master_TEST.alg_Go_2_0()V: root-Branch
   * 6 fb.rt.pnp.Master_TEST__Basic$Master_TEST.alg_Vacuum_Off()V: root-Branch
   * 7 fb.rt.pnp.Master_TEST__Basic$Master_TEST.alg_Vacuum_On()V: root-Branch
   * 8 fb.rt.pnp.Master_TEST__Basic$Master_TEST.state_Deposit_2()V: root-Branch
   * 9 fb.rt.pnp.Master_TEST__Basic$Master_TEST.state_Pick1_2()V: root-Branch
   * 10 fb.rt.pnp.Master_TEST__Basic$Master_TEST.alg_Go_1_0()V: root-Branch
   * 11 fb.rt.pnp.Master_TEST__Basic$Master_TEST.state_Deposit_3()V: root-Branch
   * 12 fb.rt.pnp.Master_TEST__Basic$Master_TEST.alg_Go_2_1()V: root-Branch
   * 13 fb.rt.pnp.Master_TEST__Basic$Master_TEST.service_REQ()V: I4 Branch 4 IFNE L248 - true
   * 14 fb.rt.pnp.Master_TEST__Basic$Master_TEST.service_REQ()V: I4 Branch 4 IFNE L248 - false
   * 15 fb.rt.pnp.Master_TEST__Basic$Master_TEST.service_REQ()V: I8 Branch 5 IFEQ L248 - false
   * 16 fb.rt.pnp.Master_TEST__Basic$Master_TEST.service_REQ()V: I26 Branch 6 IF_ICMPNE L252 - true
   * 17 fb.rt.pnp.Master_TEST__Basic$Master_TEST.service_REQ()V: I26 Branch 6 IF_ICMPNE L252 - false
   * 18 fb.rt.pnp.Master_TEST__Basic$Master_TEST.service_REQ()V: I34 Branch 7 IFEQ L252 - false
   * 19 fb.rt.pnp.Master_TEST__Basic$Master_TEST.service_REQ()V: I52 Branch 8 IF_ICMPNE L256 - true
   * 20 fb.rt.pnp.Master_TEST__Basic$Master_TEST.service_REQ()V: I52 Branch 8 IF_ICMPNE L256 - false
   * 21 fb.rt.pnp.Master_TEST__Basic$Master_TEST.service_REQ()V: I60 Branch 9 IFEQ L256 - false
   * 22 fb.rt.pnp.Master_TEST__Basic$Master_TEST.service_REQ()V: I78 Branch 10 IF_ICMPNE L260 - true
   * 23 fb.rt.pnp.Master_TEST__Basic$Master_TEST.service_REQ()V: I78 Branch 10 IF_ICMPNE L260 - false
   * 24 fb.rt.pnp.Master_TEST__Basic$Master_TEST.service_REQ()V: I86 Branch 11 IFEQ L260 - false
   * 25 fb.rt.pnp.Master_TEST__Basic$Master_TEST.service_REQ()V: I104 Branch 12 IF_ICMPNE L264 - true
   * 26 fb.rt.pnp.Master_TEST__Basic$Master_TEST.service_REQ()V: I104 Branch 12 IF_ICMPNE L264 - false
   * 27 fb.rt.pnp.Master_TEST__Basic$Master_TEST.service_REQ()V: I112 Branch 13 IFEQ L264 - false
   * 28 fb.rt.pnp.Master_TEST__Basic$Master_TEST.service_REQ()V: I130 Branch 14 IF_ICMPNE L268 - true
   * 29 fb.rt.pnp.Master_TEST__Basic$Master_TEST.service_REQ()V: I130 Branch 14 IF_ICMPNE L268 - false
   * 30 fb.rt.pnp.Master_TEST__Basic$Master_TEST.service_REQ()V: I138 Branch 15 IFEQ L268 - false
   * 31 fb.rt.pnp.Master_TEST__Basic$Master_TEST.service_REQ()V: I156 Branch 16 IF_ICMPNE L272 - false
   * 32 fb.rt.pnp.Master_TEST__Basic$Master_TEST.service_REQ()V: I164 Branch 17 IFEQ L272 - false
   * 33 fb.rt.pnp.Master_TEST__Basic$Master_TEST.serviceEvent(Lfb/rt/EventServer;)V: I5 Branch 1 IF_ACMPNE L234 - true
   * 34 fb.rt.pnp.Master_TEST__Basic$Master_TEST.serviceEvent(Lfb/rt/EventServer;)V: I14 Branch 2 IF_ACMPNE L235 - false
   * 35 fb.rt.pnp.Master_TEST__Basic.event_REQ(ZZZZZZZFF)V: root-Branch
   * 36 fb.rt.pnp.Master_TEST__Basic.transition_Master_TEST_8()V: root-Branch
   * 37 fb.rt.pnp.Master_TEST__Basic.transition_Master_TEST_7()V: root-Branch
   * 38 fb.rt.pnp.Master_TEST__Basic.transition_Master_TEST_4()V: root-Branch
   * 39 fb.rt.pnp.Master_TEST__Basic.transition_Master_TEST_3()V: root-Branch
   * 40 fb.rt.pnp.Master_TEST__Basic.transition_Master_TEST_5()V: root-Branch
   * 41 fb.rt.pnp.Master_TEST__Basic.transition_Master_TEST_6()V: root-Branch
   * 42 fb.rt.pnp.Master_TEST__Basic.transition_Master_TEST_2()V: root-Branch
   */

  @Test
  public void test15()  throws Throwable  {
      Master_TEST__Basic master_TEST__Basic0 = new Master_TEST__Basic();
      master_TEST__Basic0.event_REQ(true, true, true, true, true, true, true, 2923.8271F, 2923.8271F);
      master_TEST__Basic0.event_REQ(true, true, true, true, true, true, true, 2923.8271F, 2923.8271F);
      master_TEST__Basic0.event_REQ(true, true, true, true, true, true, true, 2923.8271F, 2923.8271F);
      master_TEST__Basic0.event_REQ(true, true, true, true, true, true, true, 2923.8271F, 2923.8271F);
      master_TEST__Basic0.event_REQ(true, true, true, true, true, true, true, 2923.8271F, 2923.8271F);
      master_TEST__Basic0.event_REQ(true, true, true, true, true, true, true, 2923.8271F, 2923.8271F);
      master_TEST__Basic0.event_REQ(true, true, true, true, true, true, true, 2923.8271F, 2923.8271F);
  }

  //Test case number: 16
  /*
   * 9 covered goals:
   * 1 fb.rt.pnp.Master_TEST__Basic$Master_TEST.<init>(Lfb/rt/pnp/Master_TEST__Basic;)V: root-Branch
   * 2 fb.rt.pnp.Master_TEST__Basic$Master_TEST.state_START()V: root-Branch
   * 3 fb.rt.pnp.Master_TEST__Basic$Master_TEST.state_Init()V: root-Branch
   * 4 fb.rt.pnp.Master_TEST__Basic$Master_TEST.service_INIT()V: I4 Branch 3 IFNE L240 - false
   * 5 fb.rt.pnp.Master_TEST__Basic$Master_TEST.serviceEvent(Lfb/rt/EventServer;)V: I5 Branch 1 IF_ACMPNE L234 - false
   * 6 fb.rt.pnp.Master_TEST__Basic.event_INIT(ZZZZZZZFF)V: root-Branch
   * 7 fb.rt.pnp.Master_TEST__Basic.transition_Master_TEST_1()V: root-Branch
   * 8 fb.rt.pnp.Master_TEST__Basic.transition_Master_TEST_0()V: root-Branch
   * 9 fb.rt.pnp.Master_TEST__Basic.<init>()V: root-Branch
   */

  @Test
  public void test16()  throws Throwable  {
      Master_TEST__Basic master_TEST__Basic0 = new Master_TEST__Basic();
      master_TEST__Basic0.event_INIT(false, true, true, true, true, true, false, (-196.59512F), (-196.59512F));
  }
}
