/*
 * This file was automatically generated by EvoSuite
 * Tue Jan 06 21:24:02 MSK 2015
 */

package fb.rt.pnp;

import static org.junit.Assert.*;
import org.junit.Test;
import fb.rt.pnp.MasterSlave__Composite;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.EvoSuiteFile;
import org.junit.runner.RunWith;


public class MasterSlave__Composite_ESTest {

  //Test case number: 0
  /*
   * 1 covered goal:
   * 1 fb.rt.pnp.MasterSlave__Composite$WPMaster.service_REQ()V: I80 Branch 79 IFEQ L1259 - true
   */

  @Test
  public void test00()  throws Throwable  {
      MasterSlave__Composite masterSlave__Composite0 = new MasterSlave__Composite();
      masterSlave__Composite0.event_REQ(false, false, false, false, false, false, false, false, false, false, false);
  }

  //Test case number: 1
  /*
   * 1 covered goal:
   * 1 fb.rt.pnp.MasterSlave__Composite$WPMaster.service_INIT()V: I4 Branch 70 IFNE L1243 - true
   */

  @Test
  public void test01()  throws Throwable  {
      MasterSlave__Composite masterSlave__Composite0 = new MasterSlave__Composite();
      masterSlave__Composite0.event_REQ(true, true, true, true, true, true, true, true, true, true, true);
      masterSlave__Composite0.event_INIT(true, false, true, true, true, true, false, true, true, false, true);
  }

  //Test case number: 2
  /*
   * 1 covered goal:
   * 1 fb.rt.pnp.MasterSlave__Composite$CylinderMaterSlave.service_REQ()V: I31 Branch 55 IFEQ L958 - true
   */

  @Test
  public void test02()  throws Throwable  {
      MasterSlave__Composite masterSlave__Composite0 = new MasterSlave__Composite();
      masterSlave__Composite0.event_REQ(true, true, true, true, true, true, true, true, true, false, true);
      masterSlave__Composite0.event_REQ(true, false, true, true, false, false, false, false, true, true, true);
      masterSlave__Composite0.event_REQ(true, true, true, true, false, true, false, true, true, true, true);
  }

  //Test case number: 3
  /*
   * 7 covered goals:
   * 1 fb.rt.pnp.MasterSlave__Composite$WPMaster.state_Temp1()V: root-Branch
   * 2 fb.rt.pnp.MasterSlave__Composite$WPMaster.service_RC_CONF()V: I49 Branch 94 IF_ICMPNE L1299 - false
   * 3 fb.rt.pnp.MasterSlave__Composite$WPMaster.service_RC_CONF()V: I53 Branch 95 IFEQ L1299 - false
   * 4 fb.rt.pnp.MasterSlave__Composite$WPMaster.service_LC_CONF()V: I27 Branch 82 IF_ICMPNE L1271 - false
   * 5 fb.rt.pnp.MasterSlave__Composite$WPMaster.service_LC_CONF()V: I31 Branch 83 IFEQ L1271 - false
   * 6 fb.rt.pnp.MasterSlave__Composite.transition_WPMaster_6()V: root-Branch
   * 7 fb.rt.pnp.MasterSlave__Composite.transition_WPMaster_12()V: root-Branch
   */

  @Test
  public void test03()  throws Throwable  {
      MasterSlave__Composite masterSlave__Composite0 = new MasterSlave__Composite();
      masterSlave__Composite0.event_REQ(false, true, false, true, true, true, true, false, false, false, true);
      masterSlave__Composite0.event_REQ(true, true, true, true, true, true, false, true, true, false, true);
  }

  //Test case number: 4
  /*
   * 6 covered goals:
   * 1 fb.rt.pnp.MasterSlave__Composite$WPMaster.service_VC_CONF()V: I35 Branch 103 IFEQ L1319 - true
   * 2 fb.rt.pnp.MasterSlave__Composite$WPMaster.service_VC_CONF()V: I53 Branch 104 IF_ICMPNE L1323 - false
   * 3 fb.rt.pnp.MasterSlave__Composite$WPMaster.service_VC_CONF()V: I60 Branch 105 IFEQ L1323 - true
   * 4 fb.rt.pnp.MasterSlave__Composite$WPMaster.service_VC_CONF()V: I67 Branch 106 IFEQ L1323 - false
   * 5 fb.rt.pnp.MasterSlave__Composite$WPMaster.alg_ChangeFlag()V: I5 Branch 107 IFEQ L1340 - false
   * 6 fb.rt.pnp.MasterSlave__Composite.transition_WPMaster_17()V: root-Branch
   */

  @Test
  public void test04()  throws Throwable  {
      MasterSlave__Composite masterSlave__Composite0 = new MasterSlave__Composite();
      masterSlave__Composite0.event_REQ(true, true, true, true, true, true, true, true, true, true, true);
      masterSlave__Composite0.event_REQ(true, false, true, false, true, false, false, true, false, false, true);
      masterSlave__Composite0.event_REQ(false, false, true, true, true, true, true, true, true, false, false);
      masterSlave__Composite0.event_REQ(true, true, true, true, true, true, true, false, false, true, true);
      masterSlave__Composite0.event_REQ(false, false, false, false, false, true, false, false, true, false, false);
      masterSlave__Composite0.event_REQ(false, true, false, false, true, true, false, true, false, false, true);
  }

  //Test case number: 5
  /*
   * 10 covered goals:
   * 1 fb.rt.pnp.MasterSlave__Composite$VaccumSlave.state_OP12()V: root-Branch
   * 2 fb.rt.pnp.MasterSlave__Composite$VaccumSlave.alg_OP12()V: root-Branch
   * 3 fb.rt.pnp.MasterSlave__Composite$VaccumSlave.service_REQ()V: I5 Branch 17 IF_ICMPNE L394 - false
   * 4 fb.rt.pnp.MasterSlave__Composite$VaccumSlave.service_REQ()V: I9 Branch 18 IFEQ L394 - true
   * 5 fb.rt.pnp.MasterSlave__Composite$VaccumSlave.service_REQ()V: I9 Branch 18 IFEQ L394 - false
   * 6 fb.rt.pnp.MasterSlave__Composite$VaccumSlave.service_OP1()V: I8 Branch 10 IFEQ L370 - true
   * 7 fb.rt.pnp.MasterSlave__Composite$VaccumSlave.service_OP1()V: I25 Branch 11 IFNE L374 - false
   * 8 fb.rt.pnp.MasterSlave__Composite$VaccumSlave.service_OP1()V: I29 Branch 12 IFNE L374 - false
   * 9 fb.rt.pnp.MasterSlave__Composite.transition_VaccumSlave_3()V: root-Branch
   * 10 fb.rt.pnp.MasterSlave__Composite.transition_VaccumSlave_6()V: root-Branch
   */

  @Test
  public void test05()  throws Throwable  {
      MasterSlave__Composite masterSlave__Composite0 = new MasterSlave__Composite();
      masterSlave__Composite0.event_REQ(true, true, true, true, true, true, false, true, true, false, true);
      masterSlave__Composite0.event_REQ(true, true, true, true, true, false, true, false, false, true, true);
  }

  //Test case number: 6
  /*
   * 9 covered goals:
   * 1 fb.rt.pnp.MasterSlave__Composite$WPMaster.state_Temp3()V: root-Branch
   * 2 fb.rt.pnp.MasterSlave__Composite$WPMaster.service_RC_CONF()V: I71 Branch 96 IF_ICMPNE L1303 - true
   * 3 fb.rt.pnp.MasterSlave__Composite$WPMaster.service_RC_CONF()V: I93 Branch 98 IF_ICMPNE L1307 - false
   * 4 fb.rt.pnp.MasterSlave__Composite$WPMaster.service_RC_CONF()V: I97 Branch 99 IFEQ L1307 - false
   * 5 fb.rt.pnp.MasterSlave__Composite$WPMaster.service_LC_CONF()V: I71 Branch 86 IF_ICMPNE L1279 - false
   * 6 fb.rt.pnp.MasterSlave__Composite$WPMaster.service_LC_CONF()V: I75 Branch 87 IFEQ L1279 - false
   * 7 fb.rt.pnp.MasterSlave__Composite$SlaveCylinder.service_REQ()V: I9 Branch 36 IFEQ L721 - true
   * 8 fb.rt.pnp.MasterSlave__Composite.transition_WPMaster_8()V: root-Branch
   * 9 fb.rt.pnp.MasterSlave__Composite.transition_WPMaster_14()V: root-Branch
   */

  @Test
  public void test06()  throws Throwable  {
      MasterSlave__Composite masterSlave__Composite0 = new MasterSlave__Composite();
      masterSlave__Composite0.event_REQ(true, true, true, true, true, true, true, true, true, true, true);
      masterSlave__Composite0.event_REQ(true, false, true, false, true, false, false, true, false, false, true);
      masterSlave__Composite0.event_REQ(false, false, true, true, true, true, true, true, true, false, false);
      masterSlave__Composite0.event_REQ(true, true, false, true, false, true, false, false, true, true, true);
      masterSlave__Composite0.event_REQ(true, true, true, true, true, true, true, false, false, true, true);
  }

  //Test case number: 7
  /*
   * 6 covered goals:
   * 1 fb.rt.pnp.MasterSlave__Composite$WPMaster.state_Pick2()V: root-Branch
   * 2 fb.rt.pnp.MasterSlave__Composite$WPMaster.service_REQ()V: I39 Branch 75 IFEQ L1255 - false
   * 3 fb.rt.pnp.MasterSlave__Composite$WPMaster.service_RC_CONF()V: I5 Branch 90 IF_ICMPNE L1291 - false
   * 4 fb.rt.pnp.MasterSlave__Composite$WPMaster.service_RC_CONF()V: I9 Branch 91 IFEQ L1291 - false
   * 5 fb.rt.pnp.MasterSlave__Composite.transition_WPMaster_10()V: root-Branch
   * 6 fb.rt.pnp.MasterSlave__Composite.transition_WPMaster_3()V: root-Branch
   */

  @Test
  public void test07()  throws Throwable  {
      MasterSlave__Composite masterSlave__Composite0 = new MasterSlave__Composite();
      masterSlave__Composite0.event_REQ(false, false, false, true, false, true, false, true, false, true, true);
      masterSlave__Composite0.event_REQ(true, true, true, true, true, true, true, true, true, false, true);
  }

  //Test case number: 8
  /*
   * 83 covered goals:
   * 1 fb.rt.pnp.MasterSlave__Composite$VaccumSlave.state_Vaccum()V: root-Branch
   * 2 fb.rt.pnp.MasterSlave__Composite$VaccumSlave.alg_Vaccum()V: root-Branch
   * 3 fb.rt.pnp.MasterSlave__Composite$VaccumSlave.alg_OP11()V: root-Branch
   * 4 fb.rt.pnp.MasterSlave__Composite$VaccumSlave.state_OP11()V: root-Branch
   * 5 fb.rt.pnp.MasterSlave__Composite$VaccumSlave.service_REQ()V: I27 Branch 19 IF_ICMPNE L398 - false
   * 6 fb.rt.pnp.MasterSlave__Composite$VaccumSlave.service_REQ()V: I31 Branch 20 IFNE L398 - true
   * 7 fb.rt.pnp.MasterSlave__Composite$VaccumSlave.service_REQ()V: I31 Branch 20 IFNE L398 - false
   * 8 fb.rt.pnp.MasterSlave__Composite$VaccumSlave.service_OP1()V: I4 Branch 9 IFNE L370 - false
   * 9 fb.rt.pnp.MasterSlave__Composite$VaccumSlave.service_OP1()V: I8 Branch 10 IFEQ L370 - false
   * 10 fb.rt.pnp.MasterSlave__Composite$VaccumSlave.serviceEvent(Lfb/rt/EventServer;)V: I5 Branch 5 IF_ACMPNE L362 - false
   * 11 fb.rt.pnp.MasterSlave__Composite$WPMaster.state_VCUp()V: root-Branch
   * 12 fb.rt.pnp.MasterSlave__Composite$WPMaster.state_Pick1()V: root-Branch
   * 13 fb.rt.pnp.MasterSlave__Composite$WPMaster.state_CylGoBack()V: root-Branch
   * 14 fb.rt.pnp.MasterSlave__Composite$WPMaster.state_Temp4()V: root-Branch
   * 15 fb.rt.pnp.MasterSlave__Composite$WPMaster.service_REQ()V: I8 Branch 72 IFEQ L1251 - false
   * 16 fb.rt.pnp.MasterSlave__Composite$WPMaster.service_VC_CONF()V: I5 Branch 100 IF_ICMPNE L1315 - true
   * 17 fb.rt.pnp.MasterSlave__Composite$WPMaster.service_VC_CONF()V: I5 Branch 100 IF_ICMPNE L1315 - false
   * 18 fb.rt.pnp.MasterSlave__Composite$WPMaster.service_VC_CONF()V: I9 Branch 101 IFEQ L1315 - false
   * 19 fb.rt.pnp.MasterSlave__Composite$WPMaster.service_VC_CONF()V: I27 Branch 102 IF_ICMPNE L1319 - false
   * 20 fb.rt.pnp.MasterSlave__Composite$WPMaster.service_VC_CONF()V: I35 Branch 103 IFEQ L1319 - false
   * 21 fb.rt.pnp.MasterSlave__Composite$WPMaster.service_RC_CONF()V: I27 Branch 92 IF_ICMPNE L1295 - true
   * 22 fb.rt.pnp.MasterSlave__Composite$WPMaster.service_RC_CONF()V: I49 Branch 94 IF_ICMPNE L1299 - true
   * 23 fb.rt.pnp.MasterSlave__Composite$WPMaster.service_RC_CONF()V: I71 Branch 96 IF_ICMPNE L1303 - false
   * 24 fb.rt.pnp.MasterSlave__Composite$WPMaster.service_RC_CONF()V: I75 Branch 97 IFEQ L1303 - false
   * 25 fb.rt.pnp.MasterSlave__Composite$WPMaster.alg_ChangeFlag()V: I5 Branch 107 IFEQ L1340 - true
   * 26 fb.rt.pnp.MasterSlave__Composite$WPMaster.service_LC_CONF()V: I5 Branch 80 IF_ICMPNE L1267 - false
   * 27 fb.rt.pnp.MasterSlave__Composite$WPMaster.service_LC_CONF()V: I9 Branch 81 IFEQ L1267 - false
   * 28 fb.rt.pnp.MasterSlave__Composite$WPMaster.service_LC_CONF()V: I49 Branch 84 IF_ICMPNE L1275 - true
   * 29 fb.rt.pnp.MasterSlave__Composite$WPMaster.service_LC_CONF()V: I71 Branch 86 IF_ICMPNE L1279 - true
   * 30 fb.rt.pnp.MasterSlave__Composite$WPMaster.service_LC_CONF()V: I93 Branch 88 IF_ICMPNE L1283 - false
   * 31 fb.rt.pnp.MasterSlave__Composite$WPMaster.service_LC_CONF()V: I97 Branch 89 IFEQ L1283 - false
   * 32 fb.rt.pnp.MasterSlave__Composite$WPMaster.serviceEvent(Lfb/rt/EventServer;)V: I32 Branch 68 IF_ACMPNE L1237 - true
   * 33 fb.rt.pnp.MasterSlave__Composite$WPMaster.serviceEvent(Lfb/rt/EventServer;)V: I41 Branch 69 IF_ACMPNE L1238 - false
   * 34 fb.rt.pnp.MasterSlave__Composite$CylinderMaterSlave.state_START()V: root-Branch
   * 35 fb.rt.pnp.MasterSlave__Composite$CylinderMaterSlave.alg_Test()V: root-Branch
   * 36 fb.rt.pnp.MasterSlave__Composite$CylinderMaterSlave.state_Home()V: root-Branch
   * 37 fb.rt.pnp.MasterSlave__Composite$CylinderMaterSlave.state_End()V: root-Branch
   * 38 fb.rt.pnp.MasterSlave__Composite$CylinderMaterSlave.state_Retract()V: root-Branch
   * 39 fb.rt.pnp.MasterSlave__Composite$CylinderMaterSlave.alg_Home()V: root-Branch
   * 40 fb.rt.pnp.MasterSlave__Composite$CylinderMaterSlave.alg_Retract()V: root-Branch
   * 41 fb.rt.pnp.MasterSlave__Composite$CylinderMaterSlave.alg_End()V: root-Branch
   * 42 fb.rt.pnp.MasterSlave__Composite$CylinderMaterSlave.service_Retract()V: I4 Branch 51 IFNE L946 - false
   * 43 fb.rt.pnp.MasterSlave__Composite$CylinderMaterSlave.service_REQ()V: I9 Branch 53 IFEQ L954 - false
   * 44 fb.rt.pnp.MasterSlave__Composite$CylinderMaterSlave.service_REQ()V: I27 Branch 54 IF_ICMPNE L958 - false
   * 45 fb.rt.pnp.MasterSlave__Composite$CylinderMaterSlave.service_REQ()V: I31 Branch 55 IFEQ L958 - false
   * 46 fb.rt.pnp.MasterSlave__Composite$CylinderMaterSlave.service_SL_CNF()V: I5 Branch 56 IF_ICMPNE L966 - false
   * 47 fb.rt.pnp.MasterSlave__Composite$CylinderMaterSlave.service_SL_CNF()V: I9 Branch 57 IFEQ L966 - false
   * 48 fb.rt.pnp.MasterSlave__Composite$CylinderMaterSlave.serviceEvent(Lfb/rt/EventServer;)V: I14 Branch 47 IF_ACMPNE L931 - false
   * 49 fb.rt.pnp.MasterSlave__Composite$CylinderMaterSlave.serviceEvent(Lfb/rt/EventServer;)V: I23 Branch 48 IF_ACMPNE L932 - true
   * 50 fb.rt.pnp.MasterSlave__Composite$CylinderMaterSlave.serviceEvent(Lfb/rt/EventServer;)V: I32 Branch 49 IF_ACMPNE L933 - false
   * 51 fb.rt.pnp.MasterSlave__Composite$SpringCyl.state_In2()V: root-Branch
   * 52 fb.rt.pnp.MasterSlave__Composite$SpringCyl.alg_In2()V: root-Branch
   * 53 fb.rt.pnp.MasterSlave__Composite$SpringCyl.service_REQ()V: I8 Branch 115 IFEQ L1525 - true
   * 54 fb.rt.pnp.MasterSlave__Composite$SpringCyl.service_REQ()V: I25 Branch 116 IFNE L1529 - false
   * 55 fb.rt.pnp.MasterSlave__Composite$SpringCyl.service_REQ()V: I29 Branch 117 IFEQ L1529 - true
   * 56 fb.rt.pnp.MasterSlave__Composite$SpringCyl.service_REQ()V: I29 Branch 117 IFEQ L1529 - false
   * 57 fb.rt.pnp.MasterSlave__Composite$SlaveCylinder.state_Retract()V: root-Branch
   * 58 fb.rt.pnp.MasterSlave__Composite$SlaveCylinder.state_Home()V: root-Branch
   * 59 fb.rt.pnp.MasterSlave__Composite$SlaveCylinder.alg_Home()V: root-Branch
   * 60 fb.rt.pnp.MasterSlave__Composite$SlaveCylinder.alg_Retract()V: root-Branch
   * 61 fb.rt.pnp.MasterSlave__Composite$SlaveCylinder.service_Retract()V: I4 Branch 34 IFNE L713 - false
   * 62 fb.rt.pnp.MasterSlave__Composite$SlaveCylinder.service_REQ()V: I5 Branch 35 IF_ICMPNE L721 - false
   * 63 fb.rt.pnp.MasterSlave__Composite$SlaveCylinder.service_REQ()V: I9 Branch 36 IFEQ L721 - false
   * 64 fb.rt.pnp.MasterSlave__Composite$SlaveCylinder.serviceEvent(Lfb/rt/EventServer;)V: I14 Branch 31 IF_ACMPNE L699 - false
   * 65 fb.rt.pnp.MasterSlave__Composite.transition_WPMaster_9()V: root-Branch
   * 66 fb.rt.pnp.MasterSlave__Composite.transition_WPMaster_2()V: root-Branch
   * 67 fb.rt.pnp.MasterSlave__Composite.transition_SlaveCylinder_1()V: root-Branch
   * 68 fb.rt.pnp.MasterSlave__Composite.transition_CylinderMaterSlave_2()V: root-Branch
   * 69 fb.rt.pnp.MasterSlave__Composite.transition_WPMaster_15()V: root-Branch
   * 70 fb.rt.pnp.MasterSlave__Composite.transition_VaccumSlave_7()V: root-Branch
   * 71 fb.rt.pnp.MasterSlave__Composite.transition_VaccumSlave_2()V: root-Branch
   * 72 fb.rt.pnp.MasterSlave__Composite.transition_CylinderMaterSlave_5()V: root-Branch
   * 73 fb.rt.pnp.MasterSlave__Composite.transition_WPMaster_5()V: root-Branch
   * 74 fb.rt.pnp.MasterSlave__Composite.transition_SlaveCylinder_4()V: root-Branch
   * 75 fb.rt.pnp.MasterSlave__Composite.transition_SpringCyl_5()V: root-Branch
   * 76 fb.rt.pnp.MasterSlave__Composite.transition_WPMaster_13()V: root-Branch
   * 77 fb.rt.pnp.MasterSlave__Composite.transition_SlaveCylinder_3()V: root-Branch
   * 78 fb.rt.pnp.MasterSlave__Composite.transition_CylinderMaterSlave_4()V: root-Branch
   * 79 fb.rt.pnp.MasterSlave__Composite.transition_VaccumSlave_0()V: root-Branch
   * 80 fb.rt.pnp.MasterSlave__Composite.transition_CylinderMaterSlave_0()V: root-Branch
   * 81 fb.rt.pnp.MasterSlave__Composite.transition_SpringCyl_2()V: root-Branch
   * 82 fb.rt.pnp.MasterSlave__Composite.transition_WPMaster_16()V: root-Branch
   * 83 fb.rt.pnp.MasterSlave__Composite.transition_CylinderMaterSlave_3()V: root-Branch
   */

  @Test
  public void test08()  throws Throwable  {
      MasterSlave__Composite masterSlave__Composite0 = new MasterSlave__Composite();
      masterSlave__Composite0.event_REQ(true, true, true, true, true, true, true, true, true, true, true);
      masterSlave__Composite0.event_REQ(true, true, false, true, false, true, false, false, true, true, true);
      masterSlave__Composite0.event_REQ(false, true, true, true, true, true, true, false, false, true, true);
      masterSlave__Composite0.event_REQ(true, false, true, true, true, false, false, false, false, false, true);
  }

  //Test case number: 9
  /*
   * 80 covered goals:
   * 1 fb.rt.pnp.MasterSlave__Composite$VaccumSlave.service_REQ()V: I5 Branch 17 IF_ICMPNE L394 - true
   * 2 fb.rt.pnp.MasterSlave__Composite$VaccumSlave.service_REQ()V: I27 Branch 19 IF_ICMPNE L398 - true
   * 3 fb.rt.pnp.MasterSlave__Composite$VaccumSlave.serviceEvent(Lfb/rt/EventServer;)V: I23 Branch 7 IF_ACMPNE L364 - false
   * 4 fb.rt.pnp.MasterSlave__Composite$WPMaster.state_VCDown()V: root-Branch
   * 5 fb.rt.pnp.MasterSlave__Composite$WPMaster.state_Pick3()V: root-Branch
   * 6 fb.rt.pnp.MasterSlave__Composite$WPMaster.state_Temp2()V: root-Branch
   * 7 fb.rt.pnp.MasterSlave__Composite$WPMaster.service_REQ()V: I4 Branch 71 IFNE L1251 - true
   * 8 fb.rt.pnp.MasterSlave__Composite$WPMaster.service_REQ()V: I4 Branch 71 IFNE L1251 - false
   * 9 fb.rt.pnp.MasterSlave__Composite$WPMaster.service_REQ()V: I8 Branch 72 IFEQ L1251 - true
   * 10 fb.rt.pnp.MasterSlave__Composite$WPMaster.service_REQ()V: I25 Branch 73 IFNE L1255 - true
   * 11 fb.rt.pnp.MasterSlave__Composite$WPMaster.service_REQ()V: I25 Branch 73 IFNE L1255 - false
   * 12 fb.rt.pnp.MasterSlave__Composite$WPMaster.service_REQ()V: I32 Branch 74 IFEQ L1255 - true
   * 13 fb.rt.pnp.MasterSlave__Composite$WPMaster.service_REQ()V: I39 Branch 75 IFEQ L1255 - true
   * 14 fb.rt.pnp.MasterSlave__Composite$WPMaster.service_REQ()V: I56 Branch 76 IFNE L1259 - true
   * 15 fb.rt.pnp.MasterSlave__Composite$WPMaster.service_REQ()V: I56 Branch 76 IFNE L1259 - false
   * 16 fb.rt.pnp.MasterSlave__Composite$WPMaster.service_REQ()V: I63 Branch 77 IFEQ L1259 - true
   * 17 fb.rt.pnp.MasterSlave__Composite$WPMaster.service_REQ()V: I73 Branch 78 IFEQ L1259 - true
   * 18 fb.rt.pnp.MasterSlave__Composite$WPMaster.service_REQ()V: I80 Branch 79 IFEQ L1259 - false
   * 19 fb.rt.pnp.MasterSlave__Composite$WPMaster.service_RC_CONF()V: I5 Branch 90 IF_ICMPNE L1291 - true
   * 20 fb.rt.pnp.MasterSlave__Composite$WPMaster.service_RC_CONF()V: I27 Branch 92 IF_ICMPNE L1295 - false
   * 21 fb.rt.pnp.MasterSlave__Composite$WPMaster.service_RC_CONF()V: I31 Branch 93 IFEQ L1295 - false
   * 22 fb.rt.pnp.MasterSlave__Composite$WPMaster.service_LC_CONF()V: I5 Branch 80 IF_ICMPNE L1267 - true
   * 23 fb.rt.pnp.MasterSlave__Composite$WPMaster.service_LC_CONF()V: I27 Branch 82 IF_ICMPNE L1271 - true
   * 24 fb.rt.pnp.MasterSlave__Composite$WPMaster.service_LC_CONF()V: I49 Branch 84 IF_ICMPNE L1275 - false
   * 25 fb.rt.pnp.MasterSlave__Composite$WPMaster.service_LC_CONF()V: I53 Branch 85 IFEQ L1275 - false
   * 26 fb.rt.pnp.MasterSlave__Composite$WPMaster.serviceEvent(Lfb/rt/EventServer;)V: I5 Branch 65 IF_ACMPNE L1234 - true
   * 27 fb.rt.pnp.MasterSlave__Composite$WPMaster.serviceEvent(Lfb/rt/EventServer;)V: I14 Branch 66 IF_ACMPNE L1235 - true
   * 28 fb.rt.pnp.MasterSlave__Composite$WPMaster.serviceEvent(Lfb/rt/EventServer;)V: I14 Branch 66 IF_ACMPNE L1235 - false
   * 29 fb.rt.pnp.MasterSlave__Composite$WPMaster.serviceEvent(Lfb/rt/EventServer;)V: I23 Branch 67 IF_ACMPNE L1236 - true
   * 30 fb.rt.pnp.MasterSlave__Composite$WPMaster.serviceEvent(Lfb/rt/EventServer;)V: I23 Branch 67 IF_ACMPNE L1236 - false
   * 31 fb.rt.pnp.MasterSlave__Composite$WPMaster.serviceEvent(Lfb/rt/EventServer;)V: I32 Branch 68 IF_ACMPNE L1237 - false
   * 32 fb.rt.pnp.MasterSlave__Composite$CylinderMaterSlave.alg_Extend()V: root-Branch
   * 33 fb.rt.pnp.MasterSlave__Composite$CylinderMaterSlave.state_Extend()V: root-Branch
   * 34 fb.rt.pnp.MasterSlave__Composite$CylinderMaterSlave.service_REQ()V: I5 Branch 52 IF_ICMPNE L954 - true
   * 35 fb.rt.pnp.MasterSlave__Composite$CylinderMaterSlave.service_REQ()V: I5 Branch 52 IF_ICMPNE L954 - false
   * 36 fb.rt.pnp.MasterSlave__Composite$CylinderMaterSlave.service_REQ()V: I9 Branch 53 IFEQ L954 - true
   * 37 fb.rt.pnp.MasterSlave__Composite$CylinderMaterSlave.service_REQ()V: I27 Branch 54 IF_ICMPNE L958 - true
   * 38 fb.rt.pnp.MasterSlave__Composite$CylinderMaterSlave.serviceEvent(Lfb/rt/EventServer;)V: I5 Branch 46 IF_ACMPNE L930 - true
   * 39 fb.rt.pnp.MasterSlave__Composite$CylinderMaterSlave.serviceEvent(Lfb/rt/EventServer;)V: I5 Branch 46 IF_ACMPNE L930 - false
   * 40 fb.rt.pnp.MasterSlave__Composite$CylinderMaterSlave.serviceEvent(Lfb/rt/EventServer;)V: I14 Branch 47 IF_ACMPNE L931 - true
   * 41 fb.rt.pnp.MasterSlave__Composite$CylinderMaterSlave.serviceEvent(Lfb/rt/EventServer;)V: I23 Branch 48 IF_ACMPNE L932 - false
   * 42 fb.rt.pnp.MasterSlave__Composite$CylinderMaterSlave.service_Extend()V: I4 Branch 50 IFNE L938 - false
   * 43 fb.rt.pnp.MasterSlave__Composite$SpringCyl.state_START()V: root-Branch
   * 44 fb.rt.pnp.MasterSlave__Composite$SpringCyl.state_In1()V: root-Branch
   * 45 fb.rt.pnp.MasterSlave__Composite$SpringCyl.alg_In1()V: root-Branch
   * 46 fb.rt.pnp.MasterSlave__Composite$SpringCyl.service_REQ()V: I4 Branch 114 IFNE L1525 - false
   * 47 fb.rt.pnp.MasterSlave__Composite$SpringCyl.service_REQ()V: I8 Branch 115 IFEQ L1525 - false
   * 48 fb.rt.pnp.MasterSlave__Composite$SpringCyl.serviceEvent(Lfb/rt/EventServer;)V: I5 Branch 111 IF_ACMPNE L1511 - true
   * 49 fb.rt.pnp.MasterSlave__Composite$SpringCyl.serviceEvent(Lfb/rt/EventServer;)V: I14 Branch 112 IF_ACMPNE L1512 - false
   * 50 fb.rt.pnp.MasterSlave__Composite$SlaveCylinder.alg_End()V: root-Branch
   * 51 fb.rt.pnp.MasterSlave__Composite$SlaveCylinder.state_Extend()V: root-Branch
   * 52 fb.rt.pnp.MasterSlave__Composite$SlaveCylinder.alg_Extend()V: root-Branch
   * 53 fb.rt.pnp.MasterSlave__Composite$SlaveCylinder.state_START()V: root-Branch
   * 54 fb.rt.pnp.MasterSlave__Composite$SlaveCylinder.state_End()V: root-Branch
   * 55 fb.rt.pnp.MasterSlave__Composite$SlaveCylinder.service_REQ()V: I5 Branch 35 IF_ICMPNE L721 - true
   * 56 fb.rt.pnp.MasterSlave__Composite$SlaveCylinder.service_REQ()V: I27 Branch 37 IF_ICMPNE L725 - true
   * 57 fb.rt.pnp.MasterSlave__Composite$SlaveCylinder.service_REQ()V: I27 Branch 37 IF_ICMPNE L725 - false
   * 58 fb.rt.pnp.MasterSlave__Composite$SlaveCylinder.service_REQ()V: I31 Branch 38 IFEQ L725 - true
   * 59 fb.rt.pnp.MasterSlave__Composite$SlaveCylinder.service_REQ()V: I31 Branch 38 IFEQ L725 - false
   * 60 fb.rt.pnp.MasterSlave__Composite$SlaveCylinder.serviceEvent(Lfb/rt/EventServer;)V: I5 Branch 30 IF_ACMPNE L698 - true
   * 61 fb.rt.pnp.MasterSlave__Composite$SlaveCylinder.serviceEvent(Lfb/rt/EventServer;)V: I5 Branch 30 IF_ACMPNE L698 - false
   * 62 fb.rt.pnp.MasterSlave__Composite$SlaveCylinder.serviceEvent(Lfb/rt/EventServer;)V: I14 Branch 31 IF_ACMPNE L699 - true
   * 63 fb.rt.pnp.MasterSlave__Composite$SlaveCylinder.serviceEvent(Lfb/rt/EventServer;)V: I23 Branch 32 IF_ACMPNE L700 - false
   * 64 fb.rt.pnp.MasterSlave__Composite$SlaveCylinder.service_Extend()V: I4 Branch 33 IFNE L705 - false
   * 65 fb.rt.pnp.MasterSlave__Composite$E_Split5.state_START()V: root-Branch
   * 66 fb.rt.pnp.MasterSlave__Composite$E_Split5.state_REQ()V: root-Branch
   * 67 fb.rt.pnp.MasterSlave__Composite$E_Split5.service_E()V: I4 Branch 23 IFNE L545 - false
   * 68 fb.rt.pnp.MasterSlave__Composite$E_Split5.serviceEvent(Lfb/rt/EventServer;)V: I5 Branch 22 IF_ACMPNE L540 - false
   * 69 fb.rt.pnp.MasterSlave__Composite.transition_E_Split5_1()V: root-Branch
   * 70 fb.rt.pnp.MasterSlave__Composite.transition_WPMaster_11()V: root-Branch
   * 71 fb.rt.pnp.MasterSlave__Composite.transition_SlaveCylinder_5()V: root-Branch
   * 72 fb.rt.pnp.MasterSlave__Composite.transition_E_Split5_0()V: root-Branch
   * 73 fb.rt.pnp.MasterSlave__Composite.transition_SpringCyl_4()V: root-Branch
   * 74 fb.rt.pnp.MasterSlave__Composite.transition_SlaveCylinder_0()V: root-Branch
   * 75 fb.rt.pnp.MasterSlave__Composite.transition_CylinderMaterSlave_1()V: root-Branch
   * 76 fb.rt.pnp.MasterSlave__Composite.transition_WPMaster_7()V: root-Branch
   * 77 fb.rt.pnp.MasterSlave__Composite.transition_SpringCyl_1()V: root-Branch
   * 78 fb.rt.pnp.MasterSlave__Composite.transition_WPMaster_4()V: root-Branch
   * 79 fb.rt.pnp.MasterSlave__Composite.event_REQ(ZZZZZZZZZZZ)V: root-Branch
   * 80 fb.rt.pnp.MasterSlave__Composite.transition_SlaveCylinder_2()V: root-Branch
   */

  @Test
  public void test09()  throws Throwable  {
      MasterSlave__Composite masterSlave__Composite0 = new MasterSlave__Composite();
      masterSlave__Composite0.event_REQ(false, false, true, true, true, false, false, false, false, false, true);
      masterSlave__Composite0.event_REQ(true, true, true, true, true, false, false, true, true, true, true);
  }

  //Test case number: 10
  /*
   * 84 covered goals:
   * 1 fb.rt.pnp.MasterSlave__Composite$VaccumSlave.connect_VACCUM(Lfb/datatype/BOOL;)V: root-Branch
   * 2 fb.rt.pnp.MasterSlave__Composite$VaccumSlave.state_START()V: root-Branch
   * 3 fb.rt.pnp.MasterSlave__Composite$VaccumSlave.alg_INIT()V: root-Branch
   * 4 fb.rt.pnp.MasterSlave__Composite$VaccumSlave.<init>(Lfb/rt/pnp/MasterSlave__Composite;)V: root-Branch
   * 5 fb.rt.pnp.MasterSlave__Composite$VaccumSlave.state_INIT()V: root-Branch
   * 6 fb.rt.pnp.MasterSlave__Composite$VaccumSlave.ovNamed(Ljava/lang/String;)Lfb/datatype/ANY;: I5 Branch 1 IFLE L287 - true
   * 7 fb.rt.pnp.MasterSlave__Composite$VaccumSlave.ovNamed(Ljava/lang/String;)Lfb/datatype/ANY;: I5 Branch 1 IFLE L287 - false
   * 8 fb.rt.pnp.MasterSlave__Composite$VaccumSlave.ovNamed(Ljava/lang/String;)Lfb/datatype/ANY;: I14 Branch 2 IFLE L288 - true
   * 9 fb.rt.pnp.MasterSlave__Composite$VaccumSlave.ovNamed(Ljava/lang/String;)Lfb/datatype/ANY;: I14 Branch 2 IFLE L288 - false
   * 10 fb.rt.pnp.MasterSlave__Composite$VaccumSlave.ovNamed(Ljava/lang/String;)Lfb/datatype/ANY;: I23 Branch 3 IFLE L289 - false
   * 11 fb.rt.pnp.MasterSlave__Composite$VaccumSlave.service_INIT()V: I4 Branch 21 IFNE L406 - false
   * 12 fb.rt.pnp.MasterSlave__Composite$VaccumSlave.connectIV(Ljava/lang/String;Lfb/datatype/ANY;)V: I5 Branch 4 IFLE L298 - false
   * 13 fb.rt.pnp.MasterSlave__Composite$VaccumSlave.serviceEvent(Lfb/rt/EventServer;)V: I5 Branch 5 IF_ACMPNE L362 - true
   * 14 fb.rt.pnp.MasterSlave__Composite$VaccumSlave.serviceEvent(Lfb/rt/EventServer;)V: I14 Branch 6 IF_ACMPNE L363 - true
   * 15 fb.rt.pnp.MasterSlave__Composite$VaccumSlave.serviceEvent(Lfb/rt/EventServer;)V: I23 Branch 7 IF_ACMPNE L364 - true
   * 16 fb.rt.pnp.MasterSlave__Composite$VaccumSlave.serviceEvent(Lfb/rt/EventServer;)V: I32 Branch 8 IF_ACMPNE L365 - false
   * 17 fb.rt.pnp.MasterSlave__Composite$WPMaster.connect_pp1(Lfb/datatype/BOOL;)V: root-Branch
   * 18 fb.rt.pnp.MasterSlave__Composite$WPMaster.<init>(Lfb/rt/pnp/MasterSlave__Composite;)V: root-Branch
   * 19 fb.rt.pnp.MasterSlave__Composite$WPMaster.alg_INIT()V: root-Branch
   * 20 fb.rt.pnp.MasterSlave__Composite$WPMaster.connect_pp0(Lfb/datatype/BOOL;)V: root-Branch
   * 21 fb.rt.pnp.MasterSlave__Composite$WPMaster.connect_RC_READY(Lfb/datatype/BOOL;)V: root-Branch
   * 22 fb.rt.pnp.MasterSlave__Composite$WPMaster.connect_VC_READY(Lfb/datatype/BOOL;)V: root-Branch
   * 23 fb.rt.pnp.MasterSlave__Composite$WPMaster.connect_LC_READY(Lfb/datatype/BOOL;)V: root-Branch
   * 24 fb.rt.pnp.MasterSlave__Composite$WPMaster.state_START()V: root-Branch
   * 25 fb.rt.pnp.MasterSlave__Composite$WPMaster.connect_pp3(Lfb/datatype/BOOL;)V: root-Branch
   * 26 fb.rt.pnp.MasterSlave__Composite$WPMaster.connect_pp2(Lfb/datatype/BOOL;)V: root-Branch
   * 27 fb.rt.pnp.MasterSlave__Composite$WPMaster.state_INIT()V: root-Branch
   * 28 fb.rt.pnp.MasterSlave__Composite$WPMaster.service_INIT()V: I4 Branch 70 IFNE L1243 - false
   * 29 fb.rt.pnp.MasterSlave__Composite$WPMaster.connectIV(Ljava/lang/String;Lfb/datatype/ANY;)V: I5 Branch 58 IFLE L1106 - true
   * 30 fb.rt.pnp.MasterSlave__Composite$WPMaster.connectIV(Ljava/lang/String;Lfb/datatype/ANY;)V: I5 Branch 58 IFLE L1106 - false
   * 31 fb.rt.pnp.MasterSlave__Composite$WPMaster.connectIV(Ljava/lang/String;Lfb/datatype/ANY;)V: I16 Branch 59 IFLE L1107 - true
   * 32 fb.rt.pnp.MasterSlave__Composite$WPMaster.connectIV(Ljava/lang/String;Lfb/datatype/ANY;)V: I16 Branch 59 IFLE L1107 - false
   * 33 fb.rt.pnp.MasterSlave__Composite$WPMaster.connectIV(Ljava/lang/String;Lfb/datatype/ANY;)V: I27 Branch 60 IFLE L1108 - true
   * 34 fb.rt.pnp.MasterSlave__Composite$WPMaster.connectIV(Ljava/lang/String;Lfb/datatype/ANY;)V: I27 Branch 60 IFLE L1108 - false
   * 35 fb.rt.pnp.MasterSlave__Composite$WPMaster.connectIV(Ljava/lang/String;Lfb/datatype/ANY;)V: I38 Branch 61 IFLE L1109 - true
   * 36 fb.rt.pnp.MasterSlave__Composite$WPMaster.connectIV(Ljava/lang/String;Lfb/datatype/ANY;)V: I38 Branch 61 IFLE L1109 - false
   * 37 fb.rt.pnp.MasterSlave__Composite$WPMaster.connectIV(Ljava/lang/String;Lfb/datatype/ANY;)V: I49 Branch 62 IFLE L1110 - true
   * 38 fb.rt.pnp.MasterSlave__Composite$WPMaster.connectIV(Ljava/lang/String;Lfb/datatype/ANY;)V: I49 Branch 62 IFLE L1110 - false
   * 39 fb.rt.pnp.MasterSlave__Composite$WPMaster.connectIV(Ljava/lang/String;Lfb/datatype/ANY;)V: I60 Branch 63 IFLE L1111 - true
   * 40 fb.rt.pnp.MasterSlave__Composite$WPMaster.connectIV(Ljava/lang/String;Lfb/datatype/ANY;)V: I60 Branch 63 IFLE L1111 - false
   * 41 fb.rt.pnp.MasterSlave__Composite$WPMaster.connectIV(Ljava/lang/String;Lfb/datatype/ANY;)V: I71 Branch 64 IFLE L1112 - false
   * 42 fb.rt.pnp.MasterSlave__Composite$WPMaster.serviceEvent(Lfb/rt/EventServer;)V: I5 Branch 65 IF_ACMPNE L1234 - false
   * 43 fb.rt.pnp.MasterSlave__Composite$MasterSlave.<init>(Lfb/rt/pnp/MasterSlave__Composite;)V: root-Branch
   * 44 fb.rt.pnp.MasterSlave__Composite$CylinderMaterSlave.connect_END(Lfb/datatype/BOOL;)V: root-Branch
   * 45 fb.rt.pnp.MasterSlave__Composite$CylinderMaterSlave.<init>(Lfb/rt/pnp/MasterSlave__Composite;)V: root-Branch
   * 46 fb.rt.pnp.MasterSlave__Composite$CylinderMaterSlave.connect_HOME(Lfb/datatype/BOOL;)V: root-Branch
   * 47 fb.rt.pnp.MasterSlave__Composite$CylinderMaterSlave.connect_SL_READY(Lfb/datatype/BOOL;)V: root-Branch
   * 48 fb.rt.pnp.MasterSlave__Composite$CylinderMaterSlave.ovNamed(Ljava/lang/String;)Lfb/datatype/ANY;: I5 Branch 39 IFLE L843 - true
   * 49 fb.rt.pnp.MasterSlave__Composite$CylinderMaterSlave.ovNamed(Ljava/lang/String;)Lfb/datatype/ANY;: I5 Branch 39 IFLE L843 - false
   * 50 fb.rt.pnp.MasterSlave__Composite$CylinderMaterSlave.ovNamed(Ljava/lang/String;)Lfb/datatype/ANY;: I14 Branch 40 IFLE L844 - true
   * 51 fb.rt.pnp.MasterSlave__Composite$CylinderMaterSlave.ovNamed(Ljava/lang/String;)Lfb/datatype/ANY;: I14 Branch 40 IFLE L844 - false
   * 52 fb.rt.pnp.MasterSlave__Composite$CylinderMaterSlave.ovNamed(Ljava/lang/String;)Lfb/datatype/ANY;: I23 Branch 41 IFLE L845 - false
   * 53 fb.rt.pnp.MasterSlave__Composite$CylinderMaterSlave.connectIV(Ljava/lang/String;Lfb/datatype/ANY;)V: I5 Branch 42 IFLE L854 - true
   * 54 fb.rt.pnp.MasterSlave__Composite$CylinderMaterSlave.connectIV(Ljava/lang/String;Lfb/datatype/ANY;)V: I5 Branch 42 IFLE L854 - false
   * 55 fb.rt.pnp.MasterSlave__Composite$CylinderMaterSlave.connectIV(Ljava/lang/String;Lfb/datatype/ANY;)V: I16 Branch 43 IFLE L855 - true
   * 56 fb.rt.pnp.MasterSlave__Composite$CylinderMaterSlave.connectIV(Ljava/lang/String;Lfb/datatype/ANY;)V: I27 Branch 44 IFLE L856 - true
   * 57 fb.rt.pnp.MasterSlave__Composite$CylinderMaterSlave.connectIV(Ljava/lang/String;Lfb/datatype/ANY;)V: I27 Branch 44 IFLE L856 - false
   * 58 fb.rt.pnp.MasterSlave__Composite$CylinderMaterSlave.connectIV(Ljava/lang/String;Lfb/datatype/ANY;)V: I38 Branch 45 IFLE L857 - false
   * 59 fb.rt.pnp.MasterSlave__Composite$SpringCyl.connect_In2(Lfb/datatype/BOOL;)V: root-Branch
   * 60 fb.rt.pnp.MasterSlave__Composite$SpringCyl.<init>(Lfb/rt/pnp/MasterSlave__Composite;)V: root-Branch
   * 61 fb.rt.pnp.MasterSlave__Composite$SpringCyl.connect_In1(Lfb/datatype/BOOL;)V: root-Branch
   * 62 fb.rt.pnp.MasterSlave__Composite$SpringCyl.ovNamed(Ljava/lang/String;)Lfb/datatype/ANY;: I5 Branch 108 IFLE L1447 - false
   * 63 fb.rt.pnp.MasterSlave__Composite$SpringCyl.connectIV(Ljava/lang/String;Lfb/datatype/ANY;)V: I5 Branch 109 IFLE L1456 - true
   * 64 fb.rt.pnp.MasterSlave__Composite$SpringCyl.connectIV(Ljava/lang/String;Lfb/datatype/ANY;)V: I5 Branch 109 IFLE L1456 - false
   * 65 fb.rt.pnp.MasterSlave__Composite$SpringCyl.connectIV(Ljava/lang/String;Lfb/datatype/ANY;)V: I16 Branch 110 IFLE L1457 - false
   * 66 fb.rt.pnp.MasterSlave__Composite$SlaveCylinder.connect_END(Lfb/datatype/BOOL;)V: root-Branch
   * 67 fb.rt.pnp.MasterSlave__Composite$SlaveCylinder.<init>(Lfb/rt/pnp/MasterSlave__Composite;)V: root-Branch
   * 68 fb.rt.pnp.MasterSlave__Composite$SlaveCylinder.connect_HOME(Lfb/datatype/BOOL;)V: root-Branch
   * 69 fb.rt.pnp.MasterSlave__Composite$SlaveCylinder.ovNamed(Ljava/lang/String;)Lfb/datatype/ANY;: I5 Branch 24 IFLE L618 - true
   * 70 fb.rt.pnp.MasterSlave__Composite$SlaveCylinder.ovNamed(Ljava/lang/String;)Lfb/datatype/ANY;: I5 Branch 24 IFLE L618 - false
   * 71 fb.rt.pnp.MasterSlave__Composite$SlaveCylinder.ovNamed(Ljava/lang/String;)Lfb/datatype/ANY;: I14 Branch 25 IFLE L619 - true
   * 72 fb.rt.pnp.MasterSlave__Composite$SlaveCylinder.ovNamed(Ljava/lang/String;)Lfb/datatype/ANY;: I14 Branch 25 IFLE L619 - false
   * 73 fb.rt.pnp.MasterSlave__Composite$SlaveCylinder.ovNamed(Ljava/lang/String;)Lfb/datatype/ANY;: I23 Branch 26 IFLE L620 - false
   * 74 fb.rt.pnp.MasterSlave__Composite$SlaveCylinder.connectIV(Ljava/lang/String;Lfb/datatype/ANY;)V: I5 Branch 27 IFLE L629 - true
   * 75 fb.rt.pnp.MasterSlave__Composite$SlaveCylinder.connectIV(Ljava/lang/String;Lfb/datatype/ANY;)V: I5 Branch 27 IFLE L629 - false
   * 76 fb.rt.pnp.MasterSlave__Composite$SlaveCylinder.connectIV(Ljava/lang/String;Lfb/datatype/ANY;)V: I16 Branch 28 IFLE L630 - true
   * 77 fb.rt.pnp.MasterSlave__Composite$SlaveCylinder.connectIV(Ljava/lang/String;Lfb/datatype/ANY;)V: I27 Branch 29 IFLE L631 - false
   * 78 fb.rt.pnp.MasterSlave__Composite$E_Split5.<init>(Lfb/rt/pnp/MasterSlave__Composite;)V: root-Branch
   * 79 fb.rt.pnp.MasterSlave__Composite.event_INIT(ZZZZZZZZZZZ)V: root-Branch
   * 80 fb.rt.pnp.MasterSlave__Composite.<init>()V: root-Branch
   * 81 fb.rt.pnp.MasterSlave__Composite.transition_WPMaster_1()V: root-Branch
   * 82 fb.rt.pnp.MasterSlave__Composite.transition_VaccumSlave_1()V: root-Branch
   * 83 fb.rt.pnp.MasterSlave__Composite.transition_WPMaster_0()V: root-Branch
   * 84 fb.rt.pnp.MasterSlave__Composite.transition_VaccumSlave_8()V: root-Branch
   */

  @Test
  public void test10()  throws Throwable  {
      MasterSlave__Composite masterSlave__Composite0 = new MasterSlave__Composite();
      masterSlave__Composite0.event_INIT(false, false, false, false, false, false, false, false, false, false, false);
  }
}
