/*
 * This file was automatically generated by EvoSuite
 * Tue Jan 06 21:44:11 MSK 2015
 */

package fb.rt.pnp;

import static org.junit.Assert.*;
import org.junit.Test;
import fb.rt.pnp.MasterSlave_TEST__Composite;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.EvoSuiteFile;
import org.junit.runner.RunWith;


public class MasterSlave_TEST__Composite_ESTest {

  //Test case number: 0
  /*
   * 1 covered goal:
   * 1 fb.rt.pnp.MasterSlave_TEST__Composite$Master_TEST.service_INIT()V: I4 Branch 61 IFNE L1089 - true
   */

  @Test
  public void test0()  throws Throwable  {
      MasterSlave_TEST__Composite masterSlave_TEST__Composite0 = new MasterSlave_TEST__Composite();
      masterSlave_TEST__Composite0.event_REQ(false, false, false, false, true, false, false, false, false, true, true, false, false, false, false, false, false, true, false);
      masterSlave_TEST__Composite0.event_INIT(false, false, false, false, true, false, true, true, false, true, true, true, true, true, false, false, true, true, false);
  }

  //Test case number: 1
  /*
   * 13 covered goals:
   * 1 fb.rt.pnp.MasterSlave_TEST__Composite$Master_TEST.state_Init()V: root-Branch
   * 2 fb.rt.pnp.MasterSlave_TEST__Composite$Master_TEST.service_INIT()V: I4 Branch 61 IFNE L1089 - false
   * 3 fb.rt.pnp.MasterSlave_TEST__Composite$Master_TEST.serviceEvent(Lfb/rt/EventServer;)V: I5 Branch 59 IF_ACMPNE L1083 - false
   * 4 fb.rt.pnp.MasterSlave_TEST__Composite$SlaveCylinder_TEST.state_INIT()V: root-Branch
   * 5 fb.rt.pnp.MasterSlave_TEST__Composite$SlaveCylinder_TEST.alg_Init()V: I5 Branch 27 IFNE L731 - true
   * 6 fb.rt.pnp.MasterSlave_TEST__Composite$SlaveCylinder_TEST.alg_Init()V: I5 Branch 27 IFNE L731 - false
   * 7 fb.rt.pnp.MasterSlave_TEST__Composite$SlaveCylinder_TEST.service_INIT()V: I4 Branch 24 IFNE L707 - false
   * 8 fb.rt.pnp.MasterSlave_TEST__Composite$SlaveCylinder_TEST.serviceEvent(Lfb/rt/EventServer;)V: I5 Branch 21 IF_ACMPNE L700 - false
   * 9 fb.rt.pnp.MasterSlave_TEST__Composite.event_INIT(ZZZZZZZZZZZZZZZZZZZ)V: root-Branch
   * 10 fb.rt.pnp.MasterSlave_TEST__Composite.transition_SlaveCylinder_TEST_2()V: root-Branch
   * 11 fb.rt.pnp.MasterSlave_TEST__Composite.transition_Master_TEST_1()V: root-Branch
   * 12 fb.rt.pnp.MasterSlave_TEST__Composite.transition_SlaveCylinder_TEST_3()V: root-Branch
   * 13 fb.rt.pnp.MasterSlave_TEST__Composite.transition_Master_TEST_0()V: root-Branch
   */

  @Test
  public void test1()  throws Throwable  {
      MasterSlave_TEST__Composite masterSlave_TEST__Composite0 = new MasterSlave_TEST__Composite();
      masterSlave_TEST__Composite0.event_INIT(true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true);
      masterSlave_TEST__Composite0.event_INIT(true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true);
  }

  //Test case number: 2
  /*
   * 24 covered goals:
   * 1 fb.rt.pnp.MasterSlave_TEST__Composite$Master_TEST.alg_Go_3_3()V: root-Branch
   * 2 fb.rt.pnp.MasterSlave_TEST__Composite$Master_TEST.state_Pick2_2()V: root-Branch
   * 3 fb.rt.pnp.MasterSlave_TEST__Composite$Master_TEST.alg_Go_3_0()V: root-Branch
   * 4 fb.rt.pnp.MasterSlave_TEST__Composite$Master_TEST.state_Pick2_3()V: root-Branch
   * 5 fb.rt.pnp.MasterSlave_TEST__Composite$Master_TEST.state_Pick2_1()V: root-Branch
   * 6 fb.rt.pnp.MasterSlave_TEST__Composite$Master_TEST.service_REQ()V: I195 Branch 78 IFEQ L1125 - false
   * 7 fb.rt.pnp.MasterSlave_TEST__Composite$Master_TEST.service_REQ()V: I254 Branch 83 IF_ICMPNE L1133 - false
   * 8 fb.rt.pnp.MasterSlave_TEST__Composite$Master_TEST.service_REQ()V: I262 Branch 84 IFEQ L1133 - true
   * 9 fb.rt.pnp.MasterSlave_TEST__Composite$Master_TEST.service_REQ()V: I262 Branch 84 IFEQ L1133 - false
   * 10 fb.rt.pnp.MasterSlave_TEST__Composite$Master_TEST.service_REQ()V: I280 Branch 85 IF_ICMPNE L1137 - false
   * 11 fb.rt.pnp.MasterSlave_TEST__Composite$Master_TEST.service_REQ()V: I288 Branch 86 IFEQ L1137 - true
   * 12 fb.rt.pnp.MasterSlave_TEST__Composite$Master_TEST.service_REQ()V: I288 Branch 86 IFEQ L1137 - false
   * 13 fb.rt.pnp.MasterSlave_TEST__Composite$Master_TEST.service_REQ()V: I384 Branch 93 IF_ICMPNE L1153 - false
   * 14 fb.rt.pnp.MasterSlave_TEST__Composite$Master_TEST.service_REQ()V: I392 Branch 94 IFEQ L1153 - true
   * 15 fb.rt.pnp.MasterSlave_TEST__Composite$Master_TEST.service_REQ()V: I392 Branch 94 IFEQ L1153 - false
   * 16 fb.rt.pnp.MasterSlave_TEST__Composite$SlaveCylinder_TEST.alg_Order()V: I62 Branch 29 IFNE L754 - false
   * 17 fb.rt.pnp.MasterSlave_TEST__Composite$SlaveCylinder_TEST.alg_Order()V: I68 Branch 30 IFNE L754 - false
   * 18 fb.rt.pnp.MasterSlave_TEST__Composite$SlaveCylinder_TEST.alg_Req()V: I65 Branch 36 IFEQ L787 - false
   * 19 fb.rt.pnp.MasterSlave_TEST__Composite$SlaveCylinder_TEST.alg_Req()V: I93 Branch 38 IFEQ L792 - false
   * 20 fb.rt.pnp.MasterSlave_TEST__Composite$SlaveCylinder_TEST.alg_Req()V: I121 Branch 40 IFEQ L797 - false
   * 21 fb.rt.pnp.MasterSlave_TEST__Composite.transition_Master_TEST_11()V: root-Branch
   * 22 fb.rt.pnp.MasterSlave_TEST__Composite.transition_Master_TEST_12()V: root-Branch
   * 23 fb.rt.pnp.MasterSlave_TEST__Composite.transition_Master_TEST_9()V: root-Branch
   * 24 fb.rt.pnp.MasterSlave_TEST__Composite.transition_Master_TEST_16()V: root-Branch
   */

  @Test
  public void test2()  throws Throwable  {
      MasterSlave_TEST__Composite masterSlave_TEST__Composite0 = new MasterSlave_TEST__Composite();
      masterSlave_TEST__Composite0.event_REQ(false, false, false, true, true, true, true, false, false, true, true, true, true, true, false, true, false, true, true);
      masterSlave_TEST__Composite0.event_REQ(true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false, true);
      masterSlave_TEST__Composite0.event_REQ(false, true, false, true, false, false, false, false, false, true, true, false, true, true, false, true, false, false, false);
      masterSlave_TEST__Composite0.event_REQ(false, true, true, true, false, true, false, true, true, true, false, true, true, true, true, false, true, true, false);
      masterSlave_TEST__Composite0.event_REQ(true, false, true, true, true, false, true, false, true, true, true, true, true, false, true, true, true, true, true);
      masterSlave_TEST__Composite0.event_REQ(true, false, true, true, true, false, true, false, true, false, true, false, false, false, false, true, true, true, true);
      masterSlave_TEST__Composite0.event_REQ(true, true, false, false, false, true, false, false, true, true, false, true, true, true, true, false, false, false, true);
  }

  //Test case number: 3
  /*
   * 13 covered goals:
   * 1 fb.rt.pnp.MasterSlave_TEST__Composite$Master_TEST.alg_Go_0_0()V: root-Branch
   * 2 fb.rt.pnp.MasterSlave_TEST__Composite$Master_TEST.state_Go_sleep()V: root-Branch
   * 3 fb.rt.pnp.MasterSlave_TEST__Composite$Master_TEST.service_REQ()V: I236 Branch 82 IFEQ L1129 - true
   * 4 fb.rt.pnp.MasterSlave_TEST__Composite$Master_TEST.service_REQ()V: I410 Branch 95 IF_ICMPNE L1157 - false
   * 5 fb.rt.pnp.MasterSlave_TEST__Composite$Master_TEST.service_REQ()V: I418 Branch 96 IFEQ L1157 - true
   * 6 fb.rt.pnp.MasterSlave_TEST__Composite$Master_TEST.service_REQ()V: I418 Branch 96 IFEQ L1157 - false
   * 7 fb.rt.pnp.MasterSlave_TEST__Composite$Master_TEST.service_REQ()V: I435 Branch 97 IFNE L1161 - false
   * 8 fb.rt.pnp.MasterSlave_TEST__Composite$Master_TEST.service_REQ()V: I439 Branch 98 IFEQ L1161 - true
   * 9 fb.rt.pnp.MasterSlave_TEST__Composite$Master_TEST.service_REQ()V: I448 Branch 99 IFEQ L1161 - true
   * 10 fb.rt.pnp.MasterSlave_TEST__Composite$Master_TEST.service_REQ()V: I458 Branch 100 IFEQ L1161 - true
   * 11 fb.rt.pnp.MasterSlave_TEST__Composite$Master_TEST.service_REQ()V: I465 Branch 101 IFEQ L1161 - false
   * 12 fb.rt.pnp.MasterSlave_TEST__Composite.transition_Master_TEST_17()V: root-Branch
   * 13 fb.rt.pnp.MasterSlave_TEST__Composite.transition_Master_TEST_18()V: root-Branch
   */

  @Test
  public void test3()  throws Throwable  {
      MasterSlave_TEST__Composite masterSlave_TEST__Composite0 = new MasterSlave_TEST__Composite();
      masterSlave_TEST__Composite0.event_REQ(false, false, false, false, false, true, true, true, false, true, false, true, false, false, false, false, true, false, false);
      masterSlave_TEST__Composite0.event_REQ(true, true, true, true, true, true, true, true, true, true, false, true, true, true, true, true, true, true, true);
      masterSlave_TEST__Composite0.event_REQ(true, true, true, false, true, false, false, true, true, false, false, false, false, false, true, false, false, false, false);
  }

  //Test case number: 4
  /*
   * 50 covered goals:
   * 1 fb.rt.pnp.MasterSlave_TEST__Composite$Master_TEST.state_START()V: root-Branch
   * 2 fb.rt.pnp.MasterSlave_TEST__Composite$Master_TEST.state_Deposit_3()V: root-Branch
   * 3 fb.rt.pnp.MasterSlave_TEST__Composite$Master_TEST.alg_Vacuum_Off()V: root-Branch
   * 4 fb.rt.pnp.MasterSlave_TEST__Composite$Master_TEST.state_Deposit_2()V: root-Branch
   * 5 fb.rt.pnp.MasterSlave_TEST__Composite$Master_TEST.state_Pick3_3()V: root-Branch
   * 6 fb.rt.pnp.MasterSlave_TEST__Composite$Master_TEST.state_Pick3_1()V: root-Branch
   * 7 fb.rt.pnp.MasterSlave_TEST__Composite$Master_TEST.alg_Go_4_0()V: root-Branch
   * 8 fb.rt.pnp.MasterSlave_TEST__Composite$Master_TEST.alg_Go_4_2()V: root-Branch
   * 9 fb.rt.pnp.MasterSlave_TEST__Composite$Master_TEST.alg_Go_1_1()V: root-Branch
   * 10 fb.rt.pnp.MasterSlave_TEST__Composite$Master_TEST.state_Pick3_2()V: root-Branch
   * 11 fb.rt.pnp.MasterSlave_TEST__Composite$Master_TEST.service_REQ()V: I8 Branch 63 IFEQ L1097 - true
   * 12 fb.rt.pnp.MasterSlave_TEST__Composite$Master_TEST.service_REQ()V: I104 Branch 70 IF_ICMPNE L1113 - false
   * 13 fb.rt.pnp.MasterSlave_TEST__Composite$Master_TEST.service_REQ()V: I112 Branch 71 IFEQ L1113 - true
   * 14 fb.rt.pnp.MasterSlave_TEST__Composite$Master_TEST.service_REQ()V: I112 Branch 71 IFEQ L1113 - false
   * 15 fb.rt.pnp.MasterSlave_TEST__Composite$Master_TEST.service_REQ()V: I130 Branch 72 IF_ICMPNE L1117 - false
   * 16 fb.rt.pnp.MasterSlave_TEST__Composite$Master_TEST.service_REQ()V: I138 Branch 73 IFEQ L1117 - true
   * 17 fb.rt.pnp.MasterSlave_TEST__Composite$Master_TEST.service_REQ()V: I138 Branch 73 IFEQ L1117 - false
   * 18 fb.rt.pnp.MasterSlave_TEST__Composite$Master_TEST.service_REQ()V: I156 Branch 74 IF_ICMPNE L1121 - false
   * 19 fb.rt.pnp.MasterSlave_TEST__Composite$Master_TEST.service_REQ()V: I164 Branch 75 IFEQ L1121 - true
   * 20 fb.rt.pnp.MasterSlave_TEST__Composite$Master_TEST.service_REQ()V: I164 Branch 75 IFEQ L1121 - false
   * 21 fb.rt.pnp.MasterSlave_TEST__Composite$Master_TEST.service_REQ()V: I181 Branch 76 IFNE L1125 - false
   * 22 fb.rt.pnp.MasterSlave_TEST__Composite$Master_TEST.service_REQ()V: I188 Branch 77 IFEQ L1125 - true
   * 23 fb.rt.pnp.MasterSlave_TEST__Composite$Master_TEST.service_REQ()V: I195 Branch 78 IFEQ L1125 - true
   * 24 fb.rt.pnp.MasterSlave_TEST__Composite$Master_TEST.service_REQ()V: I212 Branch 79 IFNE L1129 - false
   * 25 fb.rt.pnp.MasterSlave_TEST__Composite$Master_TEST.service_REQ()V: I219 Branch 80 IFEQ L1129 - true
   * 26 fb.rt.pnp.MasterSlave_TEST__Composite$Master_TEST.service_REQ()V: I229 Branch 81 IFEQ L1129 - true
   * 27 fb.rt.pnp.MasterSlave_TEST__Composite$Master_TEST.service_REQ()V: I236 Branch 82 IFEQ L1129 - false
   * 28 fb.rt.pnp.MasterSlave_TEST__Composite$Master_TEST.service_REQ()V: I306 Branch 87 IF_ICMPNE L1141 - false
   * 29 fb.rt.pnp.MasterSlave_TEST__Composite$Master_TEST.service_REQ()V: I314 Branch 88 IFEQ L1141 - true
   * 30 fb.rt.pnp.MasterSlave_TEST__Composite$Master_TEST.service_REQ()V: I314 Branch 88 IFEQ L1141 - false
   * 31 fb.rt.pnp.MasterSlave_TEST__Composite$Master_TEST.service_REQ()V: I332 Branch 89 IF_ICMPNE L1145 - false
   * 32 fb.rt.pnp.MasterSlave_TEST__Composite$Master_TEST.service_REQ()V: I340 Branch 90 IFEQ L1145 - true
   * 33 fb.rt.pnp.MasterSlave_TEST__Composite$Master_TEST.service_REQ()V: I340 Branch 90 IFEQ L1145 - false
   * 34 fb.rt.pnp.MasterSlave_TEST__Composite$Master_TEST.service_REQ()V: I358 Branch 91 IF_ICMPNE L1149 - false
   * 35 fb.rt.pnp.MasterSlave_TEST__Composite$Master_TEST.service_REQ()V: I366 Branch 92 IFEQ L1149 - true
   * 36 fb.rt.pnp.MasterSlave_TEST__Composite$Master_TEST.service_REQ()V: I366 Branch 92 IFEQ L1149 - false
   * 37 fb.rt.pnp.MasterSlave_TEST__Composite$SlaveCylinder_TEST.alg_Req()V: I5 Branch 31 IFEQ L775 - true
   * 38 fb.rt.pnp.MasterSlave_TEST__Composite$SlaveCylinder_TEST.alg_Req()V: I33 Branch 33 IFEQ L781 - true
   * 39 fb.rt.pnp.MasterSlave_TEST__Composite$SlaveCylinder_TEST.alg_Req()V: I61 Branch 35 IFEQ L787 - true
   * 40 fb.rt.pnp.MasterSlave_TEST__Composite$SlaveCylinder_TEST.alg_Req()V: I89 Branch 37 IFEQ L792 - true
   * 41 fb.rt.pnp.MasterSlave_TEST__Composite$SlaveCylinder_TEST.alg_Req()V: I145 Branch 41 IFNE L803 - true
   * 42 fb.rt.pnp.MasterSlave_TEST__Composite$SlaveCylinder_TEST.alg_Req()V: I149 Branch 42 IFNE L803 - true
   * 43 fb.rt.pnp.MasterSlave_TEST__Composite$SlaveCylinder_TEST.alg_Req()V: I171 Branch 45 IFEQ L806 - true
   * 44 fb.rt.pnp.MasterSlave_TEST__Composite.transition_Master_TEST_13()V: root-Branch
   * 45 fb.rt.pnp.MasterSlave_TEST__Composite.transition_Master_TEST_15()V: root-Branch
   * 46 fb.rt.pnp.MasterSlave_TEST__Composite.transition_Master_TEST_8()V: root-Branch
   * 47 fb.rt.pnp.MasterSlave_TEST__Composite.transition_Master_TEST_6()V: root-Branch
   * 48 fb.rt.pnp.MasterSlave_TEST__Composite.transition_Master_TEST_14()V: root-Branch
   * 49 fb.rt.pnp.MasterSlave_TEST__Composite.transition_Master_TEST_10()V: root-Branch
   * 50 fb.rt.pnp.MasterSlave_TEST__Composite.transition_Master_TEST_7()V: root-Branch
   */

  @Test
  public void test4()  throws Throwable  {
      MasterSlave_TEST__Composite masterSlave_TEST__Composite0 = new MasterSlave_TEST__Composite();
      masterSlave_TEST__Composite0.event_REQ(false, false, false, false, true, false, false, false, false, true, true, false, false, false, false, false, false, true, false);
      masterSlave_TEST__Composite0.event_REQ(true, false, false, true, true, false, false, false, false, false, false, false, false, true, true, true, true, false, true);
      masterSlave_TEST__Composite0.event_REQ(true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false, false);
      masterSlave_TEST__Composite0.event_REQ(true, true, true, false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true);
      masterSlave_TEST__Composite0.event_REQ(true, true, false, false, false, false, true, false, false, true, true, false, false, false, false, false, false, false, false);
      masterSlave_TEST__Composite0.event_REQ(true, true, true, true, true, true, false, true, true, true, true, false, true, true, false, true, true, false, false);
      masterSlave_TEST__Composite0.event_REQ(false, true, false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true);
      masterSlave_TEST__Composite0.event_REQ(true, true, true, true, true, true, true, true, false, false, true, true, true, false, true, false, true, true, true);
      masterSlave_TEST__Composite0.event_REQ(true, false, true, false, false, true, false, false, true, true, false, false, true, true, true, false, true, true, true);
      masterSlave_TEST__Composite0.event_REQ(false, true, true, true, true, false, true, true, true, true, true, false, false, false, true, true, true, true, true);
      masterSlave_TEST__Composite0.event_REQ(false, false, false, true, false, true, true, false, false, false, false, true, false, true, false, true, false, false, false);
      masterSlave_TEST__Composite0.event_REQ(true, true, true, true, false, true, true, true, true, true, true, true, true, true, true, true, true, true, true);
      masterSlave_TEST__Composite0.event_REQ(true, false, false, true, false, true, true, false, false, false, false, true, true, true, true, false, false, true, true);
  }

  //Test case number: 5
  /*
   * 162 covered goals:
   * 1 fb.rt.pnp.MasterSlave_TEST__Composite$Master_TEST.connect_pp1(Lfb/datatype/BOOL;)V: root-Branch
   * 2 fb.rt.pnp.MasterSlave_TEST__Composite$Master_TEST.state_Pick1_2()V: root-Branch
   * 3 fb.rt.pnp.MasterSlave_TEST__Composite$Master_TEST.connect_Y_READY(Lfb/datatype/BOOL;)V: root-Branch
   * 4 fb.rt.pnp.MasterSlave_TEST__Composite$Master_TEST.alg_Go_1_0()V: root-Branch
   * 5 fb.rt.pnp.MasterSlave_TEST__Composite$Master_TEST.alg_Go_2_1()V: root-Branch
   * 6 fb.rt.pnp.MasterSlave_TEST__Composite$Master_TEST.connect_pp4(Lfb/datatype/BOOL;)V: root-Branch
   * 7 fb.rt.pnp.MasterSlave_TEST__Composite$Master_TEST.connect_X_READY(Lfb/datatype/BOOL;)V: root-Branch
   * 8 fb.rt.pnp.MasterSlave_TEST__Composite$Master_TEST.state_Pick1_3()V: root-Branch
   * 9 fb.rt.pnp.MasterSlave_TEST__Composite$Master_TEST.state_Pick1_1()V: root-Branch
   * 10 fb.rt.pnp.MasterSlave_TEST__Composite$Master_TEST.connect_pp2(Lfb/datatype/BOOL;)V: root-Branch
   * 11 fb.rt.pnp.MasterSlave_TEST__Composite$Master_TEST.connect_Y_POS(Lfb/datatype/REAL;)V: root-Branch
   * 12 fb.rt.pnp.MasterSlave_TEST__Composite$Master_TEST.connect_pp3(Lfb/datatype/BOOL;)V: root-Branch
   * 13 fb.rt.pnp.MasterSlave_TEST__Composite$Master_TEST.state_Deposit_1()V: root-Branch
   * 14 fb.rt.pnp.MasterSlave_TEST__Composite$Master_TEST.connect_X_POS(Lfb/datatype/REAL;)V: root-Branch
   * 15 fb.rt.pnp.MasterSlave_TEST__Composite$Master_TEST.<init>(Lfb/rt/pnp/MasterSlave_TEST__Composite;)V: root-Branch
   * 16 fb.rt.pnp.MasterSlave_TEST__Composite$Master_TEST.alg_Go_2_0()V: root-Branch
   * 17 fb.rt.pnp.MasterSlave_TEST__Composite$Master_TEST.connect_pp0(Lfb/datatype/BOOL;)V: root-Branch
   * 18 fb.rt.pnp.MasterSlave_TEST__Composite$Master_TEST.alg_Vacuum_On()V: root-Branch
   * 19 fb.rt.pnp.MasterSlave_TEST__Composite$Master_TEST.ovNamed(Ljava/lang/String;)Lfb/datatype/ANY;: I5 Branch 46 IFLE L895 - true
   * 20 fb.rt.pnp.MasterSlave_TEST__Composite$Master_TEST.ovNamed(Ljava/lang/String;)Lfb/datatype/ANY;: I5 Branch 46 IFLE L895 - false
   * 21 fb.rt.pnp.MasterSlave_TEST__Composite$Master_TEST.ovNamed(Ljava/lang/String;)Lfb/datatype/ANY;: I14 Branch 47 IFLE L896 - true
   * 22 fb.rt.pnp.MasterSlave_TEST__Composite$Master_TEST.ovNamed(Ljava/lang/String;)Lfb/datatype/ANY;: I14 Branch 47 IFLE L896 - false
   * 23 fb.rt.pnp.MasterSlave_TEST__Composite$Master_TEST.ovNamed(Ljava/lang/String;)Lfb/datatype/ANY;: I23 Branch 48 IFLE L897 - true
   * 24 fb.rt.pnp.MasterSlave_TEST__Composite$Master_TEST.ovNamed(Ljava/lang/String;)Lfb/datatype/ANY;: I23 Branch 48 IFLE L897 - false
   * 25 fb.rt.pnp.MasterSlave_TEST__Composite$Master_TEST.ovNamed(Ljava/lang/String;)Lfb/datatype/ANY;: I32 Branch 49 IFLE L898 - false
   * 26 fb.rt.pnp.MasterSlave_TEST__Composite$Master_TEST.service_REQ()V: I4 Branch 62 IFNE L1097 - true
   * 27 fb.rt.pnp.MasterSlave_TEST__Composite$Master_TEST.service_REQ()V: I4 Branch 62 IFNE L1097 - false
   * 28 fb.rt.pnp.MasterSlave_TEST__Composite$Master_TEST.service_REQ()V: I8 Branch 63 IFEQ L1097 - false
   * 29 fb.rt.pnp.MasterSlave_TEST__Composite$Master_TEST.service_REQ()V: I26 Branch 64 IF_ICMPNE L1101 - true
   * 30 fb.rt.pnp.MasterSlave_TEST__Composite$Master_TEST.service_REQ()V: I26 Branch 64 IF_ICMPNE L1101 - false
   * 31 fb.rt.pnp.MasterSlave_TEST__Composite$Master_TEST.service_REQ()V: I34 Branch 65 IFEQ L1101 - true
   * 32 fb.rt.pnp.MasterSlave_TEST__Composite$Master_TEST.service_REQ()V: I34 Branch 65 IFEQ L1101 - false
   * 33 fb.rt.pnp.MasterSlave_TEST__Composite$Master_TEST.service_REQ()V: I52 Branch 66 IF_ICMPNE L1105 - true
   * 34 fb.rt.pnp.MasterSlave_TEST__Composite$Master_TEST.service_REQ()V: I52 Branch 66 IF_ICMPNE L1105 - false
   * 35 fb.rt.pnp.MasterSlave_TEST__Composite$Master_TEST.service_REQ()V: I60 Branch 67 IFEQ L1105 - true
   * 36 fb.rt.pnp.MasterSlave_TEST__Composite$Master_TEST.service_REQ()V: I60 Branch 67 IFEQ L1105 - false
   * 37 fb.rt.pnp.MasterSlave_TEST__Composite$Master_TEST.service_REQ()V: I78 Branch 68 IF_ICMPNE L1109 - true
   * 38 fb.rt.pnp.MasterSlave_TEST__Composite$Master_TEST.service_REQ()V: I78 Branch 68 IF_ICMPNE L1109 - false
   * 39 fb.rt.pnp.MasterSlave_TEST__Composite$Master_TEST.service_REQ()V: I86 Branch 69 IFEQ L1109 - true
   * 40 fb.rt.pnp.MasterSlave_TEST__Composite$Master_TEST.service_REQ()V: I86 Branch 69 IFEQ L1109 - false
   * 41 fb.rt.pnp.MasterSlave_TEST__Composite$Master_TEST.service_REQ()V: I104 Branch 70 IF_ICMPNE L1113 - true
   * 42 fb.rt.pnp.MasterSlave_TEST__Composite$Master_TEST.service_REQ()V: I130 Branch 72 IF_ICMPNE L1117 - true
   * 43 fb.rt.pnp.MasterSlave_TEST__Composite$Master_TEST.service_REQ()V: I156 Branch 74 IF_ICMPNE L1121 - true
   * 44 fb.rt.pnp.MasterSlave_TEST__Composite$Master_TEST.service_REQ()V: I181 Branch 76 IFNE L1125 - true
   * 45 fb.rt.pnp.MasterSlave_TEST__Composite$Master_TEST.service_REQ()V: I212 Branch 79 IFNE L1129 - true
   * 46 fb.rt.pnp.MasterSlave_TEST__Composite$Master_TEST.service_REQ()V: I254 Branch 83 IF_ICMPNE L1133 - true
   * 47 fb.rt.pnp.MasterSlave_TEST__Composite$Master_TEST.service_REQ()V: I280 Branch 85 IF_ICMPNE L1137 - true
   * 48 fb.rt.pnp.MasterSlave_TEST__Composite$Master_TEST.service_REQ()V: I306 Branch 87 IF_ICMPNE L1141 - true
   * 49 fb.rt.pnp.MasterSlave_TEST__Composite$Master_TEST.service_REQ()V: I332 Branch 89 IF_ICMPNE L1145 - true
   * 50 fb.rt.pnp.MasterSlave_TEST__Composite$Master_TEST.service_REQ()V: I358 Branch 91 IF_ICMPNE L1149 - true
   * 51 fb.rt.pnp.MasterSlave_TEST__Composite$Master_TEST.service_REQ()V: I384 Branch 93 IF_ICMPNE L1153 - true
   * 52 fb.rt.pnp.MasterSlave_TEST__Composite$Master_TEST.service_REQ()V: I410 Branch 95 IF_ICMPNE L1157 - true
   * 53 fb.rt.pnp.MasterSlave_TEST__Composite$Master_TEST.service_REQ()V: I435 Branch 97 IFNE L1161 - true
   * 54 fb.rt.pnp.MasterSlave_TEST__Composite$Master_TEST.connectIV(Ljava/lang/String;Lfb/datatype/ANY;)V: I5 Branch 50 IFLE L907 - true
   * 55 fb.rt.pnp.MasterSlave_TEST__Composite$Master_TEST.connectIV(Ljava/lang/String;Lfb/datatype/ANY;)V: I5 Branch 50 IFLE L907 - false
   * 56 fb.rt.pnp.MasterSlave_TEST__Composite$Master_TEST.connectIV(Ljava/lang/String;Lfb/datatype/ANY;)V: I16 Branch 51 IFLE L908 - true
   * 57 fb.rt.pnp.MasterSlave_TEST__Composite$Master_TEST.connectIV(Ljava/lang/String;Lfb/datatype/ANY;)V: I16 Branch 51 IFLE L908 - false
   * 58 fb.rt.pnp.MasterSlave_TEST__Composite$Master_TEST.connectIV(Ljava/lang/String;Lfb/datatype/ANY;)V: I27 Branch 52 IFLE L909 - true
   * 59 fb.rt.pnp.MasterSlave_TEST__Composite$Master_TEST.connectIV(Ljava/lang/String;Lfb/datatype/ANY;)V: I27 Branch 52 IFLE L909 - false
   * 60 fb.rt.pnp.MasterSlave_TEST__Composite$Master_TEST.connectIV(Ljava/lang/String;Lfb/datatype/ANY;)V: I38 Branch 53 IFLE L910 - true
   * 61 fb.rt.pnp.MasterSlave_TEST__Composite$Master_TEST.connectIV(Ljava/lang/String;Lfb/datatype/ANY;)V: I38 Branch 53 IFLE L910 - false
   * 62 fb.rt.pnp.MasterSlave_TEST__Composite$Master_TEST.connectIV(Ljava/lang/String;Lfb/datatype/ANY;)V: I49 Branch 54 IFLE L911 - true
   * 63 fb.rt.pnp.MasterSlave_TEST__Composite$Master_TEST.connectIV(Ljava/lang/String;Lfb/datatype/ANY;)V: I49 Branch 54 IFLE L911 - false
   * 64 fb.rt.pnp.MasterSlave_TEST__Composite$Master_TEST.connectIV(Ljava/lang/String;Lfb/datatype/ANY;)V: I60 Branch 55 IFLE L912 - true
   * 65 fb.rt.pnp.MasterSlave_TEST__Composite$Master_TEST.connectIV(Ljava/lang/String;Lfb/datatype/ANY;)V: I60 Branch 55 IFLE L912 - false
   * 66 fb.rt.pnp.MasterSlave_TEST__Composite$Master_TEST.connectIV(Ljava/lang/String;Lfb/datatype/ANY;)V: I71 Branch 56 IFLE L913 - true
   * 67 fb.rt.pnp.MasterSlave_TEST__Composite$Master_TEST.connectIV(Ljava/lang/String;Lfb/datatype/ANY;)V: I71 Branch 56 IFLE L913 - false
   * 68 fb.rt.pnp.MasterSlave_TEST__Composite$Master_TEST.connectIV(Ljava/lang/String;Lfb/datatype/ANY;)V: I82 Branch 57 IFLE L914 - true
   * 69 fb.rt.pnp.MasterSlave_TEST__Composite$Master_TEST.connectIV(Ljava/lang/String;Lfb/datatype/ANY;)V: I82 Branch 57 IFLE L914 - false
   * 70 fb.rt.pnp.MasterSlave_TEST__Composite$Master_TEST.connectIV(Ljava/lang/String;Lfb/datatype/ANY;)V: I93 Branch 58 IFLE L915 - false
   * 71 fb.rt.pnp.MasterSlave_TEST__Composite$Master_TEST.serviceEvent(Lfb/rt/EventServer;)V: I5 Branch 59 IF_ACMPNE L1083 - true
   * 72 fb.rt.pnp.MasterSlave_TEST__Composite$Master_TEST.serviceEvent(Lfb/rt/EventServer;)V: I14 Branch 60 IF_ACMPNE L1084 - false
   * 73 fb.rt.pnp.MasterSlave_TEST__Composite$SpringCyl.state_START()V: root-Branch
   * 74 fb.rt.pnp.MasterSlave_TEST__Composite$SpringCyl.<init>(Lfb/rt/pnp/MasterSlave_TEST__Composite;)V: root-Branch
   * 75 fb.rt.pnp.MasterSlave_TEST__Composite$SpringCyl.connect_In2(Lfb/datatype/BOOL;)V: root-Branch
   * 76 fb.rt.pnp.MasterSlave_TEST__Composite$SpringCyl.alg_In1()V: root-Branch
   * 77 fb.rt.pnp.MasterSlave_TEST__Composite$SpringCyl.alg_In2()V: root-Branch
   * 78 fb.rt.pnp.MasterSlave_TEST__Composite$SpringCyl.connect_In1(Lfb/datatype/BOOL;)V: root-Branch
   * 79 fb.rt.pnp.MasterSlave_TEST__Composite$SpringCyl.state_In1()V: root-Branch
   * 80 fb.rt.pnp.MasterSlave_TEST__Composite$SpringCyl.state_In2()V: root-Branch
   * 81 fb.rt.pnp.MasterSlave_TEST__Composite$SpringCyl.ovNamed(Ljava/lang/String;)Lfb/datatype/ANY;: I5 Branch 1 IFLE L407 - false
   * 82 fb.rt.pnp.MasterSlave_TEST__Composite$SpringCyl.service_REQ()V: I4 Branch 7 IFNE L485 - false
   * 83 fb.rt.pnp.MasterSlave_TEST__Composite$SpringCyl.service_REQ()V: I8 Branch 8 IFEQ L485 - true
   * 84 fb.rt.pnp.MasterSlave_TEST__Composite$SpringCyl.service_REQ()V: I8 Branch 8 IFEQ L485 - false
   * 85 fb.rt.pnp.MasterSlave_TEST__Composite$SpringCyl.service_REQ()V: I25 Branch 9 IFNE L489 - false
   * 86 fb.rt.pnp.MasterSlave_TEST__Composite$SpringCyl.service_REQ()V: I29 Branch 10 IFEQ L489 - true
   * 87 fb.rt.pnp.MasterSlave_TEST__Composite$SpringCyl.service_REQ()V: I29 Branch 10 IFEQ L489 - false
   * 88 fb.rt.pnp.MasterSlave_TEST__Composite$SpringCyl.connectIV(Ljava/lang/String;Lfb/datatype/ANY;)V: I5 Branch 2 IFLE L416 - true
   * 89 fb.rt.pnp.MasterSlave_TEST__Composite$SpringCyl.connectIV(Ljava/lang/String;Lfb/datatype/ANY;)V: I5 Branch 2 IFLE L416 - false
   * 90 fb.rt.pnp.MasterSlave_TEST__Composite$SpringCyl.connectIV(Ljava/lang/String;Lfb/datatype/ANY;)V: I16 Branch 3 IFLE L417 - false
   * 91 fb.rt.pnp.MasterSlave_TEST__Composite$SpringCyl.serviceEvent(Lfb/rt/EventServer;)V: I5 Branch 4 IF_ACMPNE L471 - true
   * 92 fb.rt.pnp.MasterSlave_TEST__Composite$SpringCyl.serviceEvent(Lfb/rt/EventServer;)V: I14 Branch 5 IF_ACMPNE L472 - false
   * 93 fb.rt.pnp.MasterSlave_TEST__Composite$SlaveCylinder_TEST.connect_HOME(Lfb/datatype/BOOL;)V: root-Branch
   * 94 fb.rt.pnp.MasterSlave_TEST__Composite$SlaveCylinder_TEST.state_START()V: root-Branch
   * 95 fb.rt.pnp.MasterSlave_TEST__Composite$SlaveCylinder_TEST.connect_END(Lfb/datatype/BOOL;)V: root-Branch
   * 96 fb.rt.pnp.MasterSlave_TEST__Composite$SlaveCylinder_TEST.state_REQ()V: root-Branch
   * 97 fb.rt.pnp.MasterSlave_TEST__Composite$SlaveCylinder_TEST.connect_DONE(Lfb/datatype/BOOL;)V: root-Branch
   * 98 fb.rt.pnp.MasterSlave_TEST__Composite$SlaveCylinder_TEST.<init>(Lfb/rt/pnp/MasterSlave_TEST__Composite;)V: root-Branch
   * 99 fb.rt.pnp.MasterSlave_TEST__Composite$SlaveCylinder_TEST.connect_Position(Lfb/datatype/REAL;)V: root-Branch
   * 100 fb.rt.pnp.MasterSlave_TEST__Composite$SlaveCylinder_TEST.connect_MID(Lfb/datatype/BOOL;)V: root-Branch
   * 101 fb.rt.pnp.MasterSlave_TEST__Composite$SlaveCylinder_TEST.state_ORDER()V: root-Branch
   * 102 fb.rt.pnp.MasterSlave_TEST__Composite$SlaveCylinder_TEST.ovNamed(Ljava/lang/String;)Lfb/datatype/ANY;: I5 Branch 11 IFLE L600 - true
   * 103 fb.rt.pnp.MasterSlave_TEST__Composite$SlaveCylinder_TEST.ovNamed(Ljava/lang/String;)Lfb/datatype/ANY;: I5 Branch 11 IFLE L600 - false
   * 104 fb.rt.pnp.MasterSlave_TEST__Composite$SlaveCylinder_TEST.ovNamed(Ljava/lang/String;)Lfb/datatype/ANY;: I14 Branch 12 IFLE L601 - true
   * 105 fb.rt.pnp.MasterSlave_TEST__Composite$SlaveCylinder_TEST.ovNamed(Ljava/lang/String;)Lfb/datatype/ANY;: I14 Branch 12 IFLE L601 - false
   * 106 fb.rt.pnp.MasterSlave_TEST__Composite$SlaveCylinder_TEST.ovNamed(Ljava/lang/String;)Lfb/datatype/ANY;: I23 Branch 13 IFLE L602 - true
   * 107 fb.rt.pnp.MasterSlave_TEST__Composite$SlaveCylinder_TEST.ovNamed(Ljava/lang/String;)Lfb/datatype/ANY;: I23 Branch 13 IFLE L602 - false
   * 108 fb.rt.pnp.MasterSlave_TEST__Composite$SlaveCylinder_TEST.ovNamed(Ljava/lang/String;)Lfb/datatype/ANY;: I32 Branch 14 IFLE L603 - false
   * 109 fb.rt.pnp.MasterSlave_TEST__Composite$SlaveCylinder_TEST.alg_Order()V: I33 Branch 28 IFLT L750 - true
   * 110 fb.rt.pnp.MasterSlave_TEST__Composite$SlaveCylinder_TEST.alg_Order()V: I33 Branch 28 IFLT L750 - false
   * 111 fb.rt.pnp.MasterSlave_TEST__Composite$SlaveCylinder_TEST.alg_Order()V: I62 Branch 29 IFNE L754 - true
   * 112 fb.rt.pnp.MasterSlave_TEST__Composite$SlaveCylinder_TEST.service_REQ()V: I4 Branch 26 IFNE L723 - false
   * 113 fb.rt.pnp.MasterSlave_TEST__Composite$SlaveCylinder_TEST.alg_Req()V: I5 Branch 31 IFEQ L775 - false
   * 114 fb.rt.pnp.MasterSlave_TEST__Composite$SlaveCylinder_TEST.alg_Req()V: I9 Branch 32 IFEQ L775 - true
   * 115 fb.rt.pnp.MasterSlave_TEST__Composite$SlaveCylinder_TEST.alg_Req()V: I9 Branch 32 IFEQ L775 - false
   * 116 fb.rt.pnp.MasterSlave_TEST__Composite$SlaveCylinder_TEST.alg_Req()V: I33 Branch 33 IFEQ L781 - false
   * 117 fb.rt.pnp.MasterSlave_TEST__Composite$SlaveCylinder_TEST.alg_Req()V: I37 Branch 34 IFEQ L781 - true
   * 118 fb.rt.pnp.MasterSlave_TEST__Composite$SlaveCylinder_TEST.alg_Req()V: I37 Branch 34 IFEQ L781 - false
   * 119 fb.rt.pnp.MasterSlave_TEST__Composite$SlaveCylinder_TEST.alg_Req()V: I61 Branch 35 IFEQ L787 - false
   * 120 fb.rt.pnp.MasterSlave_TEST__Composite$SlaveCylinder_TEST.alg_Req()V: I65 Branch 36 IFEQ L787 - true
   * 121 fb.rt.pnp.MasterSlave_TEST__Composite$SlaveCylinder_TEST.alg_Req()V: I89 Branch 37 IFEQ L792 - false
   * 122 fb.rt.pnp.MasterSlave_TEST__Composite$SlaveCylinder_TEST.alg_Req()V: I93 Branch 38 IFEQ L792 - true
   * 123 fb.rt.pnp.MasterSlave_TEST__Composite$SlaveCylinder_TEST.alg_Req()V: I117 Branch 39 IFEQ L797 - true
   * 124 fb.rt.pnp.MasterSlave_TEST__Composite$SlaveCylinder_TEST.alg_Req()V: I117 Branch 39 IFEQ L797 - false
   * 125 fb.rt.pnp.MasterSlave_TEST__Composite$SlaveCylinder_TEST.alg_Req()V: I121 Branch 40 IFEQ L797 - true
   * 126 fb.rt.pnp.MasterSlave_TEST__Composite$SlaveCylinder_TEST.alg_Req()V: I145 Branch 41 IFNE L803 - false
   * 127 fb.rt.pnp.MasterSlave_TEST__Composite$SlaveCylinder_TEST.alg_Req()V: I149 Branch 42 IFNE L803 - false
   * 128 fb.rt.pnp.MasterSlave_TEST__Composite$SlaveCylinder_TEST.alg_Req()V: I153 Branch 43 IFEQ L803 - true
   * 129 fb.rt.pnp.MasterSlave_TEST__Composite$SlaveCylinder_TEST.alg_Req()V: I153 Branch 43 IFEQ L803 - false
   * 130 fb.rt.pnp.MasterSlave_TEST__Composite$SlaveCylinder_TEST.alg_Req()V: I167 Branch 44 IFNE L806 - true
   * 131 fb.rt.pnp.MasterSlave_TEST__Composite$SlaveCylinder_TEST.alg_Req()V: I167 Branch 44 IFNE L806 - false
   * 132 fb.rt.pnp.MasterSlave_TEST__Composite$SlaveCylinder_TEST.alg_Req()V: I171 Branch 45 IFEQ L806 - false
   * 133 fb.rt.pnp.MasterSlave_TEST__Composite$SlaveCylinder_TEST.service_Order()V: I4 Branch 25 IFNE L715 - false
   * 134 fb.rt.pnp.MasterSlave_TEST__Composite$SlaveCylinder_TEST.connectIV(Ljava/lang/String;Lfb/datatype/ANY;)V: I5 Branch 15 IFLE L612 - true
   * 135 fb.rt.pnp.MasterSlave_TEST__Composite$SlaveCylinder_TEST.connectIV(Ljava/lang/String;Lfb/datatype/ANY;)V: I5 Branch 15 IFLE L612 - false
   * 136 fb.rt.pnp.MasterSlave_TEST__Composite$SlaveCylinder_TEST.connectIV(Ljava/lang/String;Lfb/datatype/ANY;)V: I16 Branch 16 IFLE L613 - true
   * 137 fb.rt.pnp.MasterSlave_TEST__Composite$SlaveCylinder_TEST.connectIV(Ljava/lang/String;Lfb/datatype/ANY;)V: I16 Branch 16 IFLE L613 - false
   * 138 fb.rt.pnp.MasterSlave_TEST__Composite$SlaveCylinder_TEST.connectIV(Ljava/lang/String;Lfb/datatype/ANY;)V: I27 Branch 17 IFLE L614 - true
   * 139 fb.rt.pnp.MasterSlave_TEST__Composite$SlaveCylinder_TEST.connectIV(Ljava/lang/String;Lfb/datatype/ANY;)V: I27 Branch 17 IFLE L614 - false
   * 140 fb.rt.pnp.MasterSlave_TEST__Composite$SlaveCylinder_TEST.connectIV(Ljava/lang/String;Lfb/datatype/ANY;)V: I38 Branch 18 IFLE L615 - true
   * 141 fb.rt.pnp.MasterSlave_TEST__Composite$SlaveCylinder_TEST.connectIV(Ljava/lang/String;Lfb/datatype/ANY;)V: I38 Branch 18 IFLE L615 - false
   * 142 fb.rt.pnp.MasterSlave_TEST__Composite$SlaveCylinder_TEST.connectIV(Ljava/lang/String;Lfb/datatype/ANY;)V: I49 Branch 19 IFLE L616 - true
   * 143 fb.rt.pnp.MasterSlave_TEST__Composite$SlaveCylinder_TEST.connectIV(Ljava/lang/String;Lfb/datatype/ANY;)V: I60 Branch 20 IFLE L617 - false
   * 144 fb.rt.pnp.MasterSlave_TEST__Composite$SlaveCylinder_TEST.serviceEvent(Lfb/rt/EventServer;)V: I5 Branch 21 IF_ACMPNE L700 - true
   * 145 fb.rt.pnp.MasterSlave_TEST__Composite$SlaveCylinder_TEST.serviceEvent(Lfb/rt/EventServer;)V: I14 Branch 22 IF_ACMPNE L701 - true
   * 146 fb.rt.pnp.MasterSlave_TEST__Composite$SlaveCylinder_TEST.serviceEvent(Lfb/rt/EventServer;)V: I14 Branch 22 IF_ACMPNE L701 - false
   * 147 fb.rt.pnp.MasterSlave_TEST__Composite$SlaveCylinder_TEST.serviceEvent(Lfb/rt/EventServer;)V: I23 Branch 23 IF_ACMPNE L702 - false
   * 148 fb.rt.pnp.MasterSlave_TEST__Composite.transition_Master_TEST_3()V: root-Branch
   * 149 fb.rt.pnp.MasterSlave_TEST__Composite.transition_SlaveCylinder_TEST_0()V: root-Branch
   * 150 fb.rt.pnp.MasterSlave_TEST__Composite.transition_Master_TEST_5()V: root-Branch
   * 151 fb.rt.pnp.MasterSlave_TEST__Composite.transition_SlaveCylinder_TEST_4()V: root-Branch
   * 152 fb.rt.pnp.MasterSlave_TEST__Composite.transition_SpringCyl_5()V: root-Branch
   * 153 fb.rt.pnp.MasterSlave_TEST__Composite.transition_SpringCyl_1()V: root-Branch
   * 154 fb.rt.pnp.MasterSlave_TEST__Composite.transition_Master_TEST_4()V: root-Branch
   * 155 fb.rt.pnp.MasterSlave_TEST__Composite.transition_SlaveCylinder_TEST_1()V: root-Branch
   * 156 fb.rt.pnp.MasterSlave_TEST__Composite.transition_SlaveCylinder_TEST_5()V: root-Branch
   * 157 fb.rt.pnp.MasterSlave_TEST__Composite.transition_Master_TEST_2()V: root-Branch
   * 158 fb.rt.pnp.MasterSlave_TEST__Composite.event_REQ(ZZZZZZZZZZZZZZZZZZZ)V: root-Branch
   * 159 fb.rt.pnp.MasterSlave_TEST__Composite.<init>()V: root-Branch
   * 160 fb.rt.pnp.MasterSlave_TEST__Composite.transition_SpringCyl_4()V: root-Branch
   * 161 fb.rt.pnp.MasterSlave_TEST__Composite.transition_SpringCyl_2()V: root-Branch
   * 162 fb.rt.pnp.MasterSlave_TEST__Composite$MasterSlave_TEST.<init>(Lfb/rt/pnp/MasterSlave_TEST__Composite;)V: root-Branch
   */

  @Test
  public void test5()  throws Throwable  {
      MasterSlave_TEST__Composite masterSlave_TEST__Composite0 = new MasterSlave_TEST__Composite();
      masterSlave_TEST__Composite0.event_REQ(true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true);
      masterSlave_TEST__Composite0.event_REQ(true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true);
      masterSlave_TEST__Composite0.event_REQ(true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true);
      masterSlave_TEST__Composite0.event_REQ(true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true);
      masterSlave_TEST__Composite0.event_REQ(true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true);
      masterSlave_TEST__Composite0.event_REQ(true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true);
      masterSlave_TEST__Composite0.event_REQ(true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true);
  }
}
