/*
 * This file was automatically generated by EvoSuite
 * Wed Jan 07 12:13:57 MSK 2015
 */

package fb.rt.pnp;

import static org.junit.Assert.*;
import org.junit.Test;
import fb.rt.pnp.ModelBA__Composite;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.EvoSuiteFile;
import org.junit.runner.RunWith;


public class ModelBA__Composite_Tr_ESTest {

  //Test case number: 0
  /*
   * 1 covered goal:
   * 1 fb.rt.pnp.ModelBA__Composite.transition_MovementBlockType1_13()V: root-Branch
   */

  @Test
  public void test00()  throws Throwable  {
      ModelBA__Composite modelBA__Composite0 = new ModelBA__Composite();
      modelBA__Composite0.event_INIT((-2672), (-2672));
      modelBA__Composite0.event_CYL_IND(true, false, false, false, true, false, true, true, true);
      modelBA__Composite0.event_CYL_IND(false, true, false, true, true, true, true, true, false);
  }

  //Test case number: 1
  /*
   * 3 covered goals:
   * 1 fb.rt.pnp.ModelBA__Composite.transition_MovementBlockType1_9()V: root-Branch
   * 2 fb.rt.pnp.ModelBA__Composite.transition_MovementBlockType1_12()V: root-Branch
   * 3 fb.rt.pnp.ModelBA__Composite.transition_PnPVacuum_3()V: root-Branch
   */

  @Test
  public void test01()  throws Throwable  {
      ModelBA__Composite modelBA__Composite0 = new ModelBA__Composite();
      modelBA__Composite0.event_INIT((-20), (-20));
      modelBA__Composite0.event_CYL_IND(true, true, true, true, true, false, true, true, true);
      modelBA__Composite0.event_CYL_IND(true, true, true, true, true, true, false, true, true);
      modelBA__Composite0.event_CYL_IND(true, true, true, true, true, true, true, true, true);
  }

  //Test case number: 2
  /*
   * 1 covered goal:
   * 1 fb.rt.pnp.ModelBA__Composite.transition_MovementBlockType1_4()V: root-Branch
   */

  @Test
  public void test02()  throws Throwable  {
      ModelBA__Composite modelBA__Composite0 = new ModelBA__Composite();
      modelBA__Composite0.event_INIT(1919, 271);
      modelBA__Composite0.event_CYL_IND(false, false, false, false, false, true, false, false, true);
      modelBA__Composite0.event_CYL_IND(false, false, false, false, false, false, false, true, false);
  }

  //Test case number: 3
  /*
   * 1 covered goal:
   * 1 fb.rt.pnp.ModelBA__Composite.transition_MovementBlockType1_8()V: root-Branch
   */

  @Test
  public void test03()  throws Throwable  {
      ModelBA__Composite modelBA__Composite0 = new ModelBA__Composite();
      modelBA__Composite0.event_INIT(0, (-2491));
      modelBA__Composite0.event_CYL_IND(false, false, true, true, true, true, false, true, true);
      modelBA__Composite0.event_CYL_IND(true, true, true, true, false, false, true, true, true);
  }

  //Test case number: 4
  /*
   * 1 covered goal:
   * 1 fb.rt.pnp.ModelBA__Composite.transition_MovementBlockType1_16()V: root-Branch
   */

  @Test
  public void test04()  throws Throwable  {
      ModelBA__Composite modelBA__Composite0 = new ModelBA__Composite();
      modelBA__Composite0.event_INIT(1919, 271);
      modelBA__Composite0.event_CYL_IND(false, false, false, false, false, false, false, true, false);
      modelBA__Composite0.event_CYL_IND(false, true, true, false, false, false, false, false, false);
  }

  //Test case number: 5
  /*
   * 5 covered goals:
   * 1 fb.rt.pnp.ModelBA__Composite.transition_LinearMotionLoad_3()V: root-Branch
   * 2 fb.rt.pnp.ModelBA__Composite.transition_LinearMotionLoad_4()V: root-Branch
   * 3 fb.rt.pnp.ModelBA__Composite.transition_MovementBlockType2_9()V: root-Branch
   * 4 fb.rt.pnp.ModelBA__Composite.transition_LinearMotionLoad_9()V: root-Branch
   * 5 fb.rt.pnp.ModelBA__Composite.transition_MovementBlockType1_10()V: root-Branch
   */

  @Test
  public void test05()  throws Throwable  {
      ModelBA__Composite modelBA__Composite0 = new ModelBA__Composite();
      modelBA__Composite0.event_INIT((-731), (-731));
      modelBA__Composite0.event_CYL_IND(true, true, true, true, true, false, false, false, false);
      modelBA__Composite0.event_CLK(1829, 0, 1829, 917, 0, 0);
      modelBA__Composite0.event_CYL_IND(false, false, false, true, false, true, true, true, true);
      modelBA__Composite0.event_CLK(0, 0, 0, 0, 0, 0);
      modelBA__Composite0.event_CYL_IND(true, true, true, true, false, true, false, true, true);
      modelBA__Composite0.event_CLK(22, (-1456), 0, 22, 0, 0);
  }

  //Test case number: 6
  /*
   * 2 covered goals:
   * 1 fb.rt.pnp.ModelBA__Composite.transition_PnpXYCalculatorBA_4()V: root-Branch
   * 2 fb.rt.pnp.ModelBA__Composite.transition_PnpXYCalculatorBA_11()V: root-Branch
   */

  @Test
  public void test06()  throws Throwable  {
      ModelBA__Composite modelBA__Composite0 = new ModelBA__Composite();
      modelBA__Composite0.event_REMOVE_WP();
  }

  //Test case number: 7
  /*
   * 3 covered goals:
   * 1 fb.rt.pnp.ModelBA__Composite.transition_LinearMotionLoad_8()V: root-Branch
   * 2 fb.rt.pnp.ModelBA__Composite.transition_MovementBlockType1_15()V: root-Branch
   * 3 fb.rt.pnp.ModelBA__Composite.transition_LinearMotionLoad_11()V: root-Branch
   */

  @Test
  public void test07()  throws Throwable  {
      ModelBA__Composite modelBA__Composite0 = new ModelBA__Composite();
      modelBA__Composite0.event_INIT((-2672), (-2672));
      modelBA__Composite0.event_CYL_IND(false, false, false, false, true, false, true, false, true);
      modelBA__Composite0.event_CLK((-2672), (-2672), (-2672), (-2672), (-2672), (-2672));
      modelBA__Composite0.event_CYL_IND(false, false, false, true, true, false, true, true, false);
      modelBA__Composite0.event_CLK((-2672), 81, 0, 0, (-1493), 1348);
      modelBA__Composite0.event_CLK(90, (-2672), (-2672), (-2672), (-2672), (-2672));
  }

  //Test case number: 8
  /*
   * 2 covered goals:
   * 1 fb.rt.pnp.ModelBA__Composite.transition_PnpXYCalculatorBA_8()V: root-Branch
   * 2 fb.rt.pnp.ModelBA__Composite.transition_PnpXYCalculatorBA_1()V: root-Branch
   */

  @Test
  public void test08()  throws Throwable  {
      ModelBA__Composite modelBA__Composite0 = new ModelBA__Composite();
      modelBA__Composite0.event_REQ(false, false, false, false);
  }

  //Test case number: 9
  /*
   * 2 covered goals:
   * 1 fb.rt.pnp.ModelBA__Composite.transition_MovementBlockType1_7()V: root-Branch
   * 2 fb.rt.pnp.ModelBA__Composite.transition_PnPVacuum_2()V: root-Branch
   */

  @Test
  public void test09()  throws Throwable  {
      ModelBA__Composite modelBA__Composite0 = new ModelBA__Composite();
      modelBA__Composite0.event_INIT((-2672), (-2672));
      modelBA__Composite0.event_CYL_IND(false, true, false, false, true, false, false, true, false);
      modelBA__Composite0.event_CYL_IND(false, false, false, true, true, false, true, true, false);
  }

  //Test case number: 10
  /*
   * 2 covered goals:
   * 1 fb.rt.pnp.ModelBA__Composite.transition_PnpXYCalculatorBA_9()V: root-Branch
   * 2 fb.rt.pnp.ModelBA__Composite.transition_PnpXYCalculatorBA_3()V: root-Branch
   */

  @Test
  public void test10()  throws Throwable  {
      ModelBA__Composite modelBA__Composite0 = new ModelBA__Composite();
      modelBA__Composite0.event_ADD_WP((-20), (-20));
  }

  //Test case number: 11
  /*
   * 2 covered goals:
   * 1 fb.rt.pnp.ModelBA__Composite.transition_MovementBlockType1_6()V: root-Branch
   * 2 fb.rt.pnp.ModelBA__Composite.transition_MovementBlockType1_2()V: root-Branch
   */

  @Test
  public void test11()  throws Throwable  {
      ModelBA__Composite modelBA__Composite0 = new ModelBA__Composite();
      modelBA__Composite0.event_INIT((-731), (-731));
      modelBA__Composite0.event_CYL_IND(true, true, false, true, true, false, false, false, true);
      modelBA__Composite0.event_CYL_IND(true, false, false, false, false, true, false, false, false);
  }

  //Test case number: 12
  /*
   * 2 covered goals:
   * 1 fb.rt.pnp.ModelBA__Composite.transition_PnpXYCalculatorBA_10()V: root-Branch
   * 2 fb.rt.pnp.ModelBA__Composite.transition_PnpXYCalculatorBA_5()V: root-Branch
   */

  @Test
  public void test12()  throws Throwable  {
      ModelBA__Composite modelBA__Composite0 = new ModelBA__Composite();
      modelBA__Composite0.event_ADD_WP00();
  }

  //Test case number: 13
  /*
   * 2 covered goals:
   * 1 fb.rt.pnp.ModelBA__Composite.transition_MovementBlockType1_1()V: root-Branch
   * 2 fb.rt.pnp.ModelBA__Composite.transition_MovementBlockType1_14()V: root-Branch
   */

  @Test
  public void test13()  throws Throwable  {
      ModelBA__Composite modelBA__Composite0 = new ModelBA__Composite();
      modelBA__Composite0.event_INIT((-2672), (-2672));
      modelBA__Composite0.event_CYL_IND(true, false, false, false, true, true, false, false, false);
      modelBA__Composite0.event_CYL_IND(false, true, true, false, false, true, false, false, false);
  }

  //Test case number: 14
  /*
   * 1 covered goal:
   * 1 fb.rt.pnp.ModelBA__Composite.transition_PnPVacuum_4()V: root-Branch
   */

  @Test
  public void test14()  throws Throwable  {
      ModelBA__Composite modelBA__Composite0 = new ModelBA__Composite();
      modelBA__Composite0.event_INIT(15, 15);
      modelBA__Composite0.event_CYL_IND(false, false, true, true, false, false, true, false, false);
  }

  //Test case number: 15
  /*
   * 5 covered goals:
   * 1 fb.rt.pnp.ModelBA__Composite.transition_MovementBlockType1_5()V: root-Branch
   * 2 fb.rt.pnp.ModelBA__Composite.transition_MovementBlockType2_8()V: root-Branch
   * 3 fb.rt.pnp.ModelBA__Composite.transition_MovementBlockType2_5()V: root-Branch
   * 4 fb.rt.pnp.ModelBA__Composite.transition_MovementBlockType2_6()V: root-Branch
   * 5 fb.rt.pnp.ModelBA__Composite.transition_MovementBlockType2_7()V: root-Branch
   */

  @Test
  public void test15()  throws Throwable  {
      ModelBA__Composite modelBA__Composite0 = new ModelBA__Composite();
      modelBA__Composite0.event_INIT((-2672), (-2672));
      modelBA__Composite0.event_CYL_IND(true, false, false, false, true, false, true, true, true);
      modelBA__Composite0.event_CYL_IND(false, true, false, false, true, false, false, true, false);
  }

  //Test case number: 16
  /*
   * 19 covered goals:
   * 1 fb.rt.pnp.ModelBA__Composite.transition_LinearMotionLoad_13()V: root-Branch
   * 2 fb.rt.pnp.ModelBA__Composite.transition_LinearMotionLoad_7()V: root-Branch
   * 3 fb.rt.pnp.ModelBA__Composite.transition_PnpXYCalculatorBA_2()V: root-Branch
   * 4 fb.rt.pnp.ModelBA__Composite.transition_PnPSensor_3()V: root-Branch
   * 5 fb.rt.pnp.ModelBA__Composite.transition_my_sensor_3()V: root-Branch
   * 6 fb.rt.pnp.ModelBA__Composite.transition_AND_3()V: root-Branch
   * 7 fb.rt.pnp.ModelBA__Composite.transition_OR_3()V: root-Branch
   * 8 fb.rt.pnp.ModelBA__Composite.transition_PnPVacuum_1()V: root-Branch
   * 9 fb.rt.pnp.ModelBA__Composite.transition_LinearMotionLoad_10()V: root-Branch
   * 10 fb.rt.pnp.ModelBA__Composite.transition_MovementBlockType2_1()V: root-Branch
   * 11 fb.rt.pnp.ModelBA__Composite.transition_OR_1()V: root-Branch
   * 12 fb.rt.pnp.ModelBA__Composite.transition_MovementBlockType1_3()V: root-Branch
   * 13 fb.rt.pnp.ModelBA__Composite.transition_my_sensor_1()V: root-Branch
   * 14 fb.rt.pnp.ModelBA__Composite.transition_AND_1()V: root-Branch
   * 15 fb.rt.pnp.ModelBA__Composite.transition_PnPSensor_1()V: root-Branch
   * 16 fb.rt.pnp.ModelBA__Composite.transition_LinearMotionLoad_12()V: root-Branch
   * 17 fb.rt.pnp.ModelBA__Composite.transition_LinearMotionLoad_2()V: root-Branch
   * 18 fb.rt.pnp.ModelBA__Composite.transition_PnpXYCalculatorBA_7()V: root-Branch
   * 19 fb.rt.pnp.ModelBA__Composite.transition_PnPSensor_2()V: root-Branch
   */

  @Test
  public void test16()  throws Throwable  {
      ModelBA__Composite modelBA__Composite0 = new ModelBA__Composite();
      modelBA__Composite0.event_INIT((-20), (-20));
      modelBA__Composite0.event_CYL_IND(true, true, true, true, true, false, true, true, true);
      modelBA__Composite0.event_CLK((-20), 3136, (-20), 0, 0, 3626);
      modelBA__Composite0.event_CLK(3136, 3136, (-20), 3136, 0, (-20));
  }

  //Test case number: 17
  /*
   * 18 covered goals:
   * 1 fb.rt.pnp.ModelBA__Composite.transition_MovementBlockType1_11()V: root-Branch
   * 2 fb.rt.pnp.ModelBA__Composite.transition_PnPVacuum_0()V: root-Branch
   * 3 fb.rt.pnp.ModelBA__Composite.transition_PnpXYCalculatorBA_6()V: root-Branch
   * 4 fb.rt.pnp.ModelBA__Composite.transition_MovementBlockType2_0()V: root-Branch
   * 5 fb.rt.pnp.ModelBA__Composite.transition_LinearMotionLoad_0()V: root-Branch
   * 6 fb.rt.pnp.ModelBA__Composite.transition_AND_2()V: root-Branch
   * 7 fb.rt.pnp.ModelBA__Composite.transition_my_sensor_0()V: root-Branch
   * 8 fb.rt.pnp.ModelBA__Composite.transition_PnPSensor_0()V: root-Branch
   * 9 fb.rt.pnp.ModelBA__Composite.transition_OR_0()V: root-Branch
   * 10 fb.rt.pnp.ModelBA__Composite.transition_MovementBlockType2_12()V: root-Branch
   * 11 fb.rt.pnp.ModelBA__Composite.transition_LinearMotionLoad_1()V: root-Branch
   * 12 fb.rt.pnp.ModelBA__Composite.transition_MovementBlockType2_2()V: root-Branch
   * 13 fb.rt.pnp.ModelBA__Composite.transition_OR_2()V: root-Branch
   * 14 fb.rt.pnp.ModelBA__Composite.transition_MovementBlockType2_11()V: root-Branch
   * 15 fb.rt.pnp.ModelBA__Composite.transition_PnpXYCalculatorBA_0()V: root-Branch
   * 16 fb.rt.pnp.ModelBA__Composite.transition_my_sensor_2()V: root-Branch
   * 17 fb.rt.pnp.ModelBA__Composite.transition_MovementBlockType1_0()V: root-Branch
   * 18 fb.rt.pnp.ModelBA__Composite.transition_AND_0()V: root-Branch
   */

  @Test
  public void test17()  throws Throwable  {
      ModelBA__Composite modelBA__Composite0 = new ModelBA__Composite();
      modelBA__Composite0.event_INIT(1306, 0);
      modelBA__Composite0.event_CYL_IND(false, false, false, false, false, true, true, false, false);
  }
}
