/*
 * This file was automatically generated by EvoSuite
 * Wed Jan 07 12:54:35 MSK 2015
 */

package fb.rt.pnp;

import static org.junit.Assert.*;
import org.junit.Test;
import fb.rt.pnp.MovementBlockType2__Basic;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.EvoSuiteFile;
import org.junit.runner.RunWith;


public class MovementBlockType2__Basic_Tr_ESTest {

  //Test case number: 0
  /*
   * 1 covered goal:
   * 1 fb.rt.pnp.MovementBlockType2__Basic.transition_MovementBlockType2_9()V: root-Branch
   */

  @Test
  public void test0()  throws Throwable  {
      MovementBlockType2__Basic movementBlockType2__Basic0 = new MovementBlockType2__Basic();
      movementBlockType2__Basic0.event_INIT(true);
      movementBlockType2__Basic0.event_CLK(true);
      movementBlockType2__Basic0.event_FAULT();
  }

  //Test case number: 1
  /*
   * 1 covered goal:
   * 1 fb.rt.pnp.MovementBlockType2__Basic.transition_MovementBlockType2_3()V: root-Branch
   */

  @Test
  public void test1()  throws Throwable  {
      MovementBlockType2__Basic movementBlockType2__Basic0 = new MovementBlockType2__Basic();
      movementBlockType2__Basic0.event_INIT(true);
      movementBlockType2__Basic0.event_FAULT();
      movementBlockType2__Basic0.event_RESUME();
      movementBlockType2__Basic0.event_CLK(true);
  }

  //Test case number: 2
  /*
   * 1 covered goal:
   * 1 fb.rt.pnp.MovementBlockType2__Basic.transition_MovementBlockType2_4()V: root-Branch
   */

  @Test
  public void test2()  throws Throwable  {
      MovementBlockType2__Basic movementBlockType2__Basic0 = new MovementBlockType2__Basic();
      movementBlockType2__Basic0.event_INIT(false);
      movementBlockType2__Basic0.event_FAULT();
      movementBlockType2__Basic0.event_RESUME();
      movementBlockType2__Basic0.event_CLK(false);
  }

  //Test case number: 3
  /*
   * 1 covered goal:
   * 1 fb.rt.pnp.MovementBlockType2__Basic.transition_MovementBlockType2_7()V: root-Branch
   */

  @Test
  public void test3()  throws Throwable  {
      MovementBlockType2__Basic movementBlockType2__Basic0 = new MovementBlockType2__Basic();
      movementBlockType2__Basic0.event_INIT(false);
      movementBlockType2__Basic0.event_CLK(true);
      movementBlockType2__Basic0.event_CLK(true);
  }

  //Test case number: 4
  /*
   * 1 covered goal:
   * 1 fb.rt.pnp.MovementBlockType2__Basic.transition_MovementBlockType2_6()V: root-Branch
   */

  @Test
  public void test4()  throws Throwable  {
      MovementBlockType2__Basic movementBlockType2__Basic0 = new MovementBlockType2__Basic();
      movementBlockType2__Basic0.event_INIT(false);
      movementBlockType2__Basic0.event_CLK(false);
      movementBlockType2__Basic0.event_CLK(true);
  }

  //Test case number: 5
  /*
   * 3 covered goals:
   * 1 fb.rt.pnp.MovementBlockType2__Basic.transition_MovementBlockType2_10()V: root-Branch
   * 2 fb.rt.pnp.MovementBlockType2__Basic.transition_MovementBlockType2_13()V: root-Branch
   * 3 fb.rt.pnp.MovementBlockType2__Basic.transition_MovementBlockType2_12()V: root-Branch
   */

  @Test
  public void test5()  throws Throwable  {
      MovementBlockType2__Basic movementBlockType2__Basic0 = new MovementBlockType2__Basic();
      movementBlockType2__Basic0.event_INIT(false);
      movementBlockType2__Basic0.event_FAULT();
      movementBlockType2__Basic0.event_RESUME();
      movementBlockType2__Basic0.event_FAULT();
  }

  //Test case number: 6
  /*
   * 1 covered goal:
   * 1 fb.rt.pnp.MovementBlockType2__Basic.transition_MovementBlockType2_8()V: root-Branch
   */

  @Test
  public void test6()  throws Throwable  {
      MovementBlockType2__Basic movementBlockType2__Basic0 = new MovementBlockType2__Basic();
      movementBlockType2__Basic0.event_INIT(false);
      movementBlockType2__Basic0.event_CLK(false);
      movementBlockType2__Basic0.event_CLK(false);
  }

  //Test case number: 7
  /*
   * 2 covered goals:
   * 1 fb.rt.pnp.MovementBlockType2__Basic.transition_MovementBlockType2_5()V: root-Branch
   * 2 fb.rt.pnp.MovementBlockType2__Basic.transition_MovementBlockType2_1()V: root-Branch
   */

  @Test
  public void test7()  throws Throwable  {
      MovementBlockType2__Basic movementBlockType2__Basic0 = new MovementBlockType2__Basic();
      movementBlockType2__Basic0.event_INIT(false);
      movementBlockType2__Basic0.event_CLK(true);
      movementBlockType2__Basic0.event_CLK(false);
  }

  //Test case number: 8
  /*
   * 3 covered goals:
   * 1 fb.rt.pnp.MovementBlockType2__Basic.transition_MovementBlockType2_11()V: root-Branch
   * 2 fb.rt.pnp.MovementBlockType2__Basic.transition_MovementBlockType2_2()V: root-Branch
   * 3 fb.rt.pnp.MovementBlockType2__Basic.transition_MovementBlockType2_0()V: root-Branch
   */

  @Test
  public void test8()  throws Throwable  {
      MovementBlockType2__Basic movementBlockType2__Basic0 = new MovementBlockType2__Basic();
      movementBlockType2__Basic0.event_INIT(false);
      movementBlockType2__Basic0.event_CLK(false);
      movementBlockType2__Basic0.event_FAULT();
  }
}
