/*
 * This file was automatically generated by EvoSuite
 * Wed Jan 07 13:24:56 MSK 2015
 */

package fb.rt.pnp;

import static org.junit.Assert.*;
import org.junit.Test;
import fb.rt.pnp.my_sensor2__Composite;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.EvoSuiteFile;
import org.junit.runner.RunWith;


public class my_sensor2__Composite_Tr_ESTest {

  //Test case number: 0
  /*
   * 4 covered goals:
   * 1 fb.rt.pnp.my_sensor2__Composite.transition_my_sensor_3()V: root-Branch
   * 2 fb.rt.pnp.my_sensor2__Composite.transition_my_sensor_1()V: root-Branch
   * 3 fb.rt.pnp.my_sensor2__Composite.transition_AND_3()V: root-Branch
   * 4 fb.rt.pnp.my_sensor2__Composite.transition_AND_1()V: root-Branch
   */

  @Test
  public void test0()  throws Throwable  {
      my_sensor2__Composite my_sensor2__Composite0 = new my_sensor2__Composite();
      my_sensor2__Composite0.event_REQ((-2936), (-2936), (-2936), (-2936), 72, (-2936));
  }

  //Test case number: 1
  /*
   * 4 covered goals:
   * 1 fb.rt.pnp.my_sensor2__Composite.transition_my_sensor_0()V: root-Branch
   * 2 fb.rt.pnp.my_sensor2__Composite.transition_my_sensor_2()V: root-Branch
   * 3 fb.rt.pnp.my_sensor2__Composite.transition_AND_2()V: root-Branch
   * 4 fb.rt.pnp.my_sensor2__Composite.transition_AND_0()V: root-Branch
   */

  @Test
  public void test1()  throws Throwable  {
      my_sensor2__Composite my_sensor2__Composite0 = new my_sensor2__Composite();
      my_sensor2__Composite0.event_INIT((-2936), (-2936), 72, (-2936), 72, (-2936));
  }
}
