/*
 * This file was automatically generated by EvoSuite
 * Tue Jan 06 23:26:20 MSK 2015
 */

package fb.rt.pnp;

import static org.junit.Assert.*;
import org.junit.Test;
import fb.rt.pnp.my_sensor2__Composite;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.EvoSuiteFile;
import org.junit.runner.RunWith;


public class my_sensor2__Composite_ESTest {

  //Test case number: 0
  /*
   * 20 covered goals:
   * 1 fb.rt.pnp.my_sensor2__Composite$my_sensor.state_REQ()V: root-Branch
   * 2 fb.rt.pnp.my_sensor2__Composite$my_sensor.alg_REQ()V: I12 Branch 8 IF_ICMPLT L257 - true
   * 3 fb.rt.pnp.my_sensor2__Composite$my_sensor.alg_REQ()V: I12 Branch 8 IF_ICMPLT L257 - false
   * 4 fb.rt.pnp.my_sensor2__Composite$my_sensor.alg_REQ()V: I28 Branch 9 IF_ICMPGT L257 - true
   * 5 fb.rt.pnp.my_sensor2__Composite$my_sensor.alg_REQ()V: I28 Branch 9 IF_ICMPGT L257 - false
   * 6 fb.rt.pnp.my_sensor2__Composite$my_sensor.alg_REQ()V: I35 Branch 10 IFEQ L257 - true
   * 7 fb.rt.pnp.my_sensor2__Composite$my_sensor.alg_REQ()V: I35 Branch 10 IFEQ L257 - false
   * 8 fb.rt.pnp.my_sensor2__Composite$my_sensor.service_REQ()V: I4 Branch 7 IFNE L244 - false
   * 9 fb.rt.pnp.my_sensor2__Composite$my_sensor.serviceEvent(Lfb/rt/EventServer;)V: I5 Branch 4 IF_ACMPNE L230 - true
   * 10 fb.rt.pnp.my_sensor2__Composite$my_sensor.serviceEvent(Lfb/rt/EventServer;)V: I14 Branch 5 IF_ACMPNE L231 - false
   * 11 fb.rt.pnp.my_sensor2__Composite$AND.alg_REQ()V: root-Branch
   * 12 fb.rt.pnp.my_sensor2__Composite$AND.state_REQ()V: root-Branch
   * 13 fb.rt.pnp.my_sensor2__Composite$AND.service_REQ()V: I4 Branch 17 IFNE L392 - false
   * 14 fb.rt.pnp.my_sensor2__Composite$AND.serviceEvent(Lfb/rt/EventServer;)V: I5 Branch 14 IF_ACMPNE L378 - true
   * 15 fb.rt.pnp.my_sensor2__Composite$AND.serviceEvent(Lfb/rt/EventServer;)V: I14 Branch 15 IF_ACMPNE L379 - false
   * 16 fb.rt.pnp.my_sensor2__Composite.transition_my_sensor_3()V: root-Branch
   * 17 fb.rt.pnp.my_sensor2__Composite.transition_my_sensor_1()V: root-Branch
   * 18 fb.rt.pnp.my_sensor2__Composite.event_REQ(IIIIII)V: root-Branch
   * 19 fb.rt.pnp.my_sensor2__Composite.transition_AND_3()V: root-Branch
   * 20 fb.rt.pnp.my_sensor2__Composite.transition_AND_1()V: root-Branch
   */

  @Test
  public void test0()  throws Throwable  {
      my_sensor2__Composite my_sensor2__Composite0 = new my_sensor2__Composite();
      my_sensor2__Composite0.event_REQ((-2823), (-2823), (-2823), 1462, (-2823), (-1026));
  }

  //Test case number: 1
  /*
   * 31 covered goals:
   * 1 fb.rt.pnp.my_sensor2__Composite$my_sensor.state_INIT()V: root-Branch
   * 2 fb.rt.pnp.my_sensor2__Composite$my_sensor.alg_INIT()V: root-Branch
   * 3 fb.rt.pnp.my_sensor2__Composite$my_sensor.connect_ZONE(Lfb/datatype/ARRAY;)V: root-Branch
   * 4 fb.rt.pnp.my_sensor2__Composite$my_sensor.connect_POS(Lfb/datatype/UINT;)V: root-Branch
   * 5 fb.rt.pnp.my_sensor2__Composite$my_sensor.<init>(Lfb/rt/pnp/my_sensor2__Composite;)V: root-Branch
   * 6 fb.rt.pnp.my_sensor2__Composite$my_sensor.state_START()V: root-Branch
   * 7 fb.rt.pnp.my_sensor2__Composite$my_sensor.ovNamed(Ljava/lang/String;)Lfb/datatype/ANY;: I5 Branch 1 IFLE L174 - false
   * 8 fb.rt.pnp.my_sensor2__Composite$my_sensor.service_INIT()V: I4 Branch 6 IFNE L236 - false
   * 9 fb.rt.pnp.my_sensor2__Composite$my_sensor.connectIV(Ljava/lang/String;Lfb/datatype/ANY;)V: I5 Branch 2 IFLE L183 - true
   * 10 fb.rt.pnp.my_sensor2__Composite$my_sensor.connectIV(Ljava/lang/String;Lfb/datatype/ANY;)V: I5 Branch 2 IFLE L183 - false
   * 11 fb.rt.pnp.my_sensor2__Composite$my_sensor.connectIV(Ljava/lang/String;Lfb/datatype/ANY;)V: I16 Branch 3 IFLE L184 - false
   * 12 fb.rt.pnp.my_sensor2__Composite$my_sensor.serviceEvent(Lfb/rt/EventServer;)V: I5 Branch 4 IF_ACMPNE L230 - false
   * 13 fb.rt.pnp.my_sensor2__Composite$AND.<init>(Lfb/rt/pnp/my_sensor2__Composite;)V: root-Branch
   * 14 fb.rt.pnp.my_sensor2__Composite$AND.alg_INIT()V: root-Branch
   * 15 fb.rt.pnp.my_sensor2__Composite$AND.connect_Q2(Lfb/datatype/BOOL;)V: root-Branch
   * 16 fb.rt.pnp.my_sensor2__Composite$AND.state_START()V: root-Branch
   * 17 fb.rt.pnp.my_sensor2__Composite$AND.connect_Q1(Lfb/datatype/BOOL;)V: root-Branch
   * 18 fb.rt.pnp.my_sensor2__Composite$AND.state_INIT()V: root-Branch
   * 19 fb.rt.pnp.my_sensor2__Composite$AND.ovNamed(Ljava/lang/String;)Lfb/datatype/ANY;: I5 Branch 11 IFLE L322 - false
   * 20 fb.rt.pnp.my_sensor2__Composite$AND.service_INIT()V: I4 Branch 16 IFNE L384 - false
   * 21 fb.rt.pnp.my_sensor2__Composite$AND.connectIV(Ljava/lang/String;Lfb/datatype/ANY;)V: I5 Branch 12 IFLE L331 - true
   * 22 fb.rt.pnp.my_sensor2__Composite$AND.connectIV(Ljava/lang/String;Lfb/datatype/ANY;)V: I5 Branch 12 IFLE L331 - false
   * 23 fb.rt.pnp.my_sensor2__Composite$AND.connectIV(Ljava/lang/String;Lfb/datatype/ANY;)V: I16 Branch 13 IFLE L332 - false
   * 24 fb.rt.pnp.my_sensor2__Composite$AND.serviceEvent(Lfb/rt/EventServer;)V: I5 Branch 14 IF_ACMPNE L378 - false
   * 25 fb.rt.pnp.my_sensor2__Composite.<init>()V: root-Branch
   * 26 fb.rt.pnp.my_sensor2__Composite.event_INIT(IIIIII)V: root-Branch
   * 27 fb.rt.pnp.my_sensor2__Composite.transition_my_sensor_0()V: root-Branch
   * 28 fb.rt.pnp.my_sensor2__Composite.transition_my_sensor_2()V: root-Branch
   * 29 fb.rt.pnp.my_sensor2__Composite.transition_AND_2()V: root-Branch
   * 30 fb.rt.pnp.my_sensor2__Composite.transition_AND_0()V: root-Branch
   * 31 fb.rt.pnp.my_sensor2__Composite$my_sensor2.<init>(Lfb/rt/pnp/my_sensor2__Composite;)V: root-Branch
   */

  @Test
  public void test1()  throws Throwable  {
      my_sensor2__Composite my_sensor2__Composite0 = new my_sensor2__Composite();
      my_sensor2__Composite0.event_INIT(1462, (-2823), (-2823), 1462, (-1026), (-2823));
  }
}
