/*
 * This file was automatically generated by EvoSuite
 * Wed Jan 07 13:04:41 MSK 2015
 */

package fb.rt.pnp;

import static org.junit.Assert.*;
import org.junit.Test;
import fb.rt.pnp.MyPnpXYCalculatorStep1__Basic;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.EvoSuiteFile;
import org.junit.runner.RunWith;


public class MyPnpXYCalculatorStep1__Basic_Tr_ESTest {

  //Test case number: 0
  /*
   * 2 covered goals:
   * 1 fb.rt.pnp.MyPnpXYCalculatorStep1__Basic.transition_MyPnpXYCalculatorStep1_3()V: root-Branch
   * 2 fb.rt.pnp.MyPnpXYCalculatorStep1__Basic.transition_MyPnpXYCalculatorStep1_1()V: root-Branch
   */

  @Test
  public void test0()  throws Throwable  {
      MyPnpXYCalculatorStep1__Basic myPnpXYCalculatorStep1__Basic0 = new MyPnpXYCalculatorStep1__Basic();
      myPnpXYCalculatorStep1__Basic0.event_CLK((-2), (-2), (-2), true, (-2));
  }

  //Test case number: 1
  /*
   * 2 covered goals:
   * 1 fb.rt.pnp.MyPnpXYCalculatorStep1__Basic.transition_MyPnpXYCalculatorStep1_0()V: root-Branch
   * 2 fb.rt.pnp.MyPnpXYCalculatorStep1__Basic.transition_MyPnpXYCalculatorStep1_2()V: root-Branch
   */

  @Test
  public void test1()  throws Throwable  {
      MyPnpXYCalculatorStep1__Basic myPnpXYCalculatorStep1__Basic0 = new MyPnpXYCalculatorStep1__Basic();
      myPnpXYCalculatorStep1__Basic0.event_INIT(0, 260);
  }
}
