/*
 * This file was automatically generated by EvoSuite
 * Tue Jan 06 23:56:48 MSK 2015
 */

package fb.rt.pnp;

import static org.junit.Assert.*;
import org.junit.Test;
import fb.rt.pnp.OR__Basic;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.EvoSuiteFile;
import org.junit.runner.RunWith;


public class OR__Basic_ESTest {

  //Test case number: 0
  /*
   * 8 covered goals:
   * 1 fb.rt.pnp.OR__Basic.transition_OR_1()V: root-Branch
   * 2 fb.rt.pnp.OR__Basic.transition_OR_3()V: root-Branch
   * 3 fb.rt.pnp.OR__Basic.event_REQ(ZZZ)V: root-Branch
   * 4 fb.rt.pnp.OR__Basic$OR.state_REQ()V: root-Branch
   * 5 fb.rt.pnp.OR__Basic$OR.alg_REQ()V: root-Branch
   * 6 fb.rt.pnp.OR__Basic$OR.service_REQ()V: I4 Branch 4 IFNE L125 - false
   * 7 fb.rt.pnp.OR__Basic$OR.serviceEvent(Lfb/rt/EventServer;)V: I5 Branch 1 IF_ACMPNE L111 - true
   * 8 fb.rt.pnp.OR__Basic$OR.serviceEvent(Lfb/rt/EventServer;)V: I14 Branch 2 IF_ACMPNE L112 - false
   */

  @Test
  public void test0()  throws Throwable  {
      OR__Basic oR__Basic0 = new OR__Basic();
      oR__Basic0.event_REQ(false, false, false);
  }

  //Test case number: 1
  /*
   * 10 covered goals:
   * 1 fb.rt.pnp.OR__Basic.transition_OR_2()V: root-Branch
   * 2 fb.rt.pnp.OR__Basic.event_INIT(ZZZ)V: root-Branch
   * 3 fb.rt.pnp.OR__Basic.transition_OR_0()V: root-Branch
   * 4 fb.rt.pnp.OR__Basic.<init>()V: root-Branch
   * 5 fb.rt.pnp.OR__Basic$OR.<init>(Lfb/rt/pnp/OR__Basic;)V: root-Branch
   * 6 fb.rt.pnp.OR__Basic$OR.state_START()V: root-Branch
   * 7 fb.rt.pnp.OR__Basic$OR.state_INIT()V: root-Branch
   * 8 fb.rt.pnp.OR__Basic$OR.alg_INIT()V: root-Branch
   * 9 fb.rt.pnp.OR__Basic$OR.service_INIT()V: I4 Branch 3 IFNE L117 - false
   * 10 fb.rt.pnp.OR__Basic$OR.serviceEvent(Lfb/rt/EventServer;)V: I5 Branch 1 IF_ACMPNE L111 - false
   */

  @Test
  public void test1()  throws Throwable  {
      OR__Basic oR__Basic0 = new OR__Basic();
      oR__Basic0.event_INIT(false, false, false);
  }
}
