/*
 * This file was automatically generated by EvoSuite
 * Wed Jan 07 01:17:52 MSK 2015
 */

package fb.rt.pnp;

import static org.junit.Assert.*;
import org.junit.Test;
import fb.rt.pnp.PnpCylinders__Composite;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.EvoSuiteFile;
import org.junit.runner.RunWith;


public class PnpCylinders__Composite_ESTest {

  //Test case number: 0
  /*
   * 1 covered goal:
   * 1 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType2.service_RESUME()V: I5 Branch 186 IF_ICMPNE L1875 - true
   */

  @Test
  public void test00()  throws Throwable  {
      PnpCylinders__Composite pnpCylinders__Composite0 = new PnpCylinders__Composite();
      pnpCylinders__Composite0.event_RESUME();
  }

  //Test case number: 1
  /*
   * 1 covered goal:
   * 1 fb.rt.pnp.PnpCylinders__Composite$LinearMotionLoad.alg_INCR()V: I44 Branch 138 IFLE L1360 - false
   */

  @Test
  public void test01()  throws Throwable  {
      PnpCylinders__Composite pnpCylinders__Composite0 = new PnpCylinders__Composite();
      pnpCylinders__Composite0.event_INIT(27, 27, true, true, 27, 27, 27, 27, 27, (float) 27, 27, true, 27, 27, 27, 27, true, true, 27, 27, false, 27);
      pnpCylinders__Composite0.event_CYL_IND(true, false, false, true, true);
      pnpCylinders__Composite0.event_INIT(6, 6, true, true, 6, 6, 6, 27, 27, (float) 27, 27, true, 6, 27, 27, 27, true, true, 6, 6, true, 27);
      pnpCylinders__Composite0.event_CLK(27, true);
  }

  //Test case number: 2
  /*
   * 1 covered goal:
   * 1 fb.rt.pnp.PnpCylinders__Composite$LinearMotionLoad.service_CLK()V: I282 Branch 133 IFEQ L1329 - true
   */

  @Test
  public void test02()  throws Throwable  {
      PnpCylinders__Composite pnpCylinders__Composite0 = new PnpCylinders__Composite();
      pnpCylinders__Composite0.event_INIT(27, 27, true, true, 27, 27, 27, 27, 27, (float) 27, 27, true, 27, 27, 27, 27, true, true, 27, 27, false, 27);
      pnpCylinders__Composite0.event_CLK(27, true);
  }

  //Test case number: 3
  /*
   * 2 covered goals:
   * 1 fb.rt.pnp.PnpCylinders__Composite$LinearMotionLoad.service_CLK()V: I129 Branch 119 IFEQ L1305 - true
   * 2 fb.rt.pnp.PnpCylinders__Composite$LinearMotionLoad.service_CLK()V: I300 Branch 134 IF_ICMPNE L1333 - true
   */

  @Test
  public void test03()  throws Throwable  {
      PnpCylinders__Composite pnpCylinders__Composite0 = new PnpCylinders__Composite();
      pnpCylinders__Composite0.event_INIT(1782, 0, true, true, 1782, 0, 1782, 1782, 1782, (float) 0, 0, true, 1782, 1782, 0, 1782, true, true, 1782, 1782, true, 1782);
      pnpCylinders__Composite0.event_CYL_IND(false, true, false, true, true);
      pnpCylinders__Composite0.event_CLK(1782, true);
      pnpCylinders__Composite0.event_CYL_IND(false, false, true, false, true);
      pnpCylinders__Composite0.event_CLK(0, false);
      pnpCylinders__Composite0.event_CLK(0, true);
  }

  //Test case number: 4
  /*
   * 4 covered goals:
   * 1 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType1.service_CLK()V: I371 Branch 76 IFEQ L955 - false
   * 2 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType1.service_FAULT()V: I41 Branch 91 IF_ICMPNE L987 - false
   * 3 fb.rt.pnp.PnpCylinders__Composite.transition_MovementBlockType1_19()V: root-Branch
   * 4 fb.rt.pnp.PnpCylinders__Composite.transition_MovementBlockType1_12()V: root-Branch
   */

  @Test
  public void test04()  throws Throwable  {
      PnpCylinders__Composite pnpCylinders__Composite0 = new PnpCylinders__Composite();
      pnpCylinders__Composite0.event_INIT(27, 27, true, true, 27, 27, 27, 27, 27, (float) 27, 27, true, 27, 27, 27, 27, true, true, 27, 27, false, 27);
      pnpCylinders__Composite0.event_CYL_IND(true, false, false, true, true);
      pnpCylinders__Composite0.event_CYL_IND(true, true, true, true, true);
  }

  //Test case number: 5
  /*
   * 7 covered goals:
   * 1 fb.rt.pnp.PnpCylinders__Composite$LinearMotionLoad.service_CLK()V: I221 Branch 127 IF_ICMPGE L1321 - true
   * 2 fb.rt.pnp.PnpCylinders__Composite$LinearMotionLoad.service_CLK()V: I228 Branch 128 IFEQ L1321 - true
   * 3 fb.rt.pnp.PnpCylinders__Composite$LinearMotionLoad.service_CLK()V: I278 Branch 132 IF_ICMPNE L1329 - true
   * 4 fb.rt.pnp.PnpCylinders__Composite$LinearMotionLoad.service_CLK()V: I300 Branch 134 IF_ICMPNE L1333 - false
   * 5 fb.rt.pnp.PnpCylinders__Composite$LinearMotionLoad.service_CLK()V: I305 Branch 135 IF_ICMPNE L1333 - false
   * 6 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType1.service_INIT()V: I4 Branch 40 IFNE L903 - true
   * 7 fb.rt.pnp.PnpCylinders__Composite.transition_LinearMotionLoad_13()V: root-Branch
   */

  @Test
  public void test05()  throws Throwable  {
      PnpCylinders__Composite pnpCylinders__Composite0 = new PnpCylinders__Composite();
      pnpCylinders__Composite0.event_INIT(0, 0, true, true, 0, 1708, 1708, 1708, 1708, (float) 1708, 1708, true, 0, 1708, 1708, 0, true, true, 0, 1708, true, 0);
      pnpCylinders__Composite0.event_INIT(0, 0, true, true, 0, 0, 0, 0, 0, (float) 0, 0, true, 0, 0, 0, 0, true, true, 1708, 0, true, 0);
      pnpCylinders__Composite0.event_CYL_IND(false, true, true, false, true);
      pnpCylinders__Composite0.event_CLK(0, true);
      pnpCylinders__Composite0.event_CLK(0, true);
  }

  //Test case number: 6
  /*
   * 2 covered goals:
   * 1 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType1.service_CLK()V: I165 Branch 58 IFEQ L927 - false
   * 2 fb.rt.pnp.PnpCylinders__Composite.transition_MovementBlockType1_5()V: root-Branch
   */

  @Test
  public void test06()  throws Throwable  {
      PnpCylinders__Composite pnpCylinders__Composite0 = new PnpCylinders__Composite();
      pnpCylinders__Composite0.event_INIT(0, 0, true, false, 0, 0, 0, 0, 0, (float) 0, 0, true, 0, 0, 0, 0, true, false, 0, 0, false, 0);
      pnpCylinders__Composite0.event_CYL_IND(false, true, true, true, true);
      pnpCylinders__Composite0.event_CYL_IND(false, false, false, false, false);
  }

  //Test case number: 7
  /*
   * 7 covered goals:
   * 1 fb.rt.pnp.PnpCylinders__Composite$LinearMotionLoad.service_CLK()V: I31 Branch 109 IFEQ L1293 - false
   * 2 fb.rt.pnp.PnpCylinders__Composite$LinearMotionLoad.service_CLK()V: I173 Branch 123 IFEQ L1313 - true
   * 3 fb.rt.pnp.PnpCylinders__Composite$LinearMotionLoad.service_CLK()V: I213 Branch 126 IF_ICMPNE L1321 - false
   * 4 fb.rt.pnp.PnpCylinders__Composite$LinearMotionLoad.service_CLK()V: I221 Branch 127 IF_ICMPGE L1321 - false
   * 5 fb.rt.pnp.PnpCylinders__Composite$LinearMotionLoad.service_CLK()V: I228 Branch 128 IFEQ L1321 - false
   * 6 fb.rt.pnp.PnpCylinders__Composite$LinearMotionLoad.alg_DECR()V: I41 Branch 142 IFGE L1387 - true
   * 7 fb.rt.pnp.PnpCylinders__Composite.transition_LinearMotionLoad_10()V: root-Branch
   */

  @Test
  public void test07()  throws Throwable  {
      PnpCylinders__Composite pnpCylinders__Composite0 = new PnpCylinders__Composite();
      pnpCylinders__Composite0.event_INIT(1782, 0, true, true, 1782, 0, 1782, 1782, 1782, (float) 0, 0, true, 1782, 1782, 0, 1782, true, true, 1782, 1782, true, 1782);
      pnpCylinders__Composite0.event_CYL_IND(false, true, false, true, true);
      pnpCylinders__Composite0.event_CLK(1782, true);
      pnpCylinders__Composite0.event_CLK(0, false);
  }

  //Test case number: 8
  /*
   * 30 covered goals:
   * 1 fb.rt.pnp.PnpCylinders__Composite$LinearMotionLoad.state_STOP()V: root-Branch
   * 2 fb.rt.pnp.PnpCylinders__Composite$LinearMotionLoad.service_CLK()V: I40 Branch 110 IFEQ L1293 - true
   * 3 fb.rt.pnp.PnpCylinders__Composite$LinearMotionLoad.service_CLK()V: I47 Branch 111 IFEQ L1293 - false
   * 4 fb.rt.pnp.PnpCylinders__Composite$LinearMotionLoad.service_CLK()V: I85 Branch 115 IFEQ L1297 - false
   * 5 fb.rt.pnp.PnpCylinders__Composite$LinearMotionLoad.service_CLK()V: I103 Branch 116 IF_ICMPNE L1301 - false
   * 6 fb.rt.pnp.PnpCylinders__Composite$LinearMotionLoad.service_CLK()V: I107 Branch 117 IFEQ L1301 - true
   * 7 fb.rt.pnp.PnpCylinders__Composite$LinearMotionLoad.service_CLK()V: I107 Branch 117 IFEQ L1301 - false
   * 8 fb.rt.pnp.PnpCylinders__Composite$LinearMotionLoad.service_CLK()V: I125 Branch 118 IF_ICMPNE L1305 - false
   * 9 fb.rt.pnp.PnpCylinders__Composite$LinearMotionLoad.service_CLK()V: I129 Branch 119 IFEQ L1305 - false
   * 10 fb.rt.pnp.PnpCylinders__Composite$LinearMotionLoad.service_CLK()V: I151 Branch 121 IFNE L1309 - false
   * 11 fb.rt.pnp.PnpCylinders__Composite$LinearMotionLoad.alg_DECR()V: I9 Branch 140 IFEQ L1384 - true
   * 12 fb.rt.pnp.PnpCylinders__Composite$LinearMotionLoad.alg_DECR()V: I13 Branch 141 IFLE L1384 - false
   * 13 fb.rt.pnp.PnpCylinders__Composite$LinearMotionLoad.alg_DECR()V: I41 Branch 142 IFGE L1387 - false
   * 14 fb.rt.pnp.PnpCylinders__Composite$LinearMotionLoad.alg_INCR()V: I9 Branch 136 IFEQ L1357 - true
   * 15 fb.rt.pnp.PnpCylinders__Composite$LinearMotionLoad.alg_INCR()V: I13 Branch 137 IFLE L1357 - false
   * 16 fb.rt.pnp.PnpCylinders__Composite$LinearMotionLoad.alg_INCR()V: I44 Branch 138 IFLE L1360 - true
   * 17 fb.rt.pnp.PnpCylinders__Composite$LinearMotionLoad.alg_INCR()V: I93 Branch 139 IFLE L1366 - true
   * 18 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType1.service_CLK()V: I120 Branch 53 IFEQ L923 - false
   * 19 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType1.service_CLK()V: I254 Branch 66 IFEQ L939 - true
   * 20 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType1.service_CLK()V: I261 Branch 67 IFEQ L939 - false
   * 21 fb.rt.pnp.PnpCylinders__Composite.transition_LinearMotionLoad_4()V: root-Branch
   * 22 fb.rt.pnp.PnpCylinders__Composite.transition_LinearMotionLoad_7()V: root-Branch
   * 23 fb.rt.pnp.PnpCylinders__Composite.transition_LinearMotionLoad_3()V: root-Branch
   * 24 fb.rt.pnp.PnpCylinders__Composite.transition_MovementBlockType2_9()V: root-Branch
   * 25 fb.rt.pnp.PnpCylinders__Composite.transition_MovementBlockType1_8()V: root-Branch
   * 26 fb.rt.pnp.PnpCylinders__Composite.transition_LinearMotionLoad_6()V: root-Branch
   * 27 fb.rt.pnp.PnpCylinders__Composite.transition_LinearMotionLoad_5()V: root-Branch
   * 28 fb.rt.pnp.PnpCylinders__Composite.transition_MovementBlockType2_3()V: root-Branch
   * 29 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType2.service_CLK()V: I53 Branch 171 IFEQ L1827 - false
   * 30 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType2.service_FAULT()V: I5 Branch 182 IF_ICMPNE L1855 - false
   */

  @Test
  public void test08()  throws Throwable  {
      PnpCylinders__Composite pnpCylinders__Composite0 = new PnpCylinders__Composite();
      pnpCylinders__Composite0.event_INIT((-7), (-7), true, true, (-7), (-7), (-7), (-7), (-7), (float) (-7), (-7), true, (-7), (-7), (-7), (-7), true, true, (-7), (-7), true, (-7));
      pnpCylinders__Composite0.event_CYL_IND(false, true, false, true, true);
      pnpCylinders__Composite0.event_CLK((-7), true);
      pnpCylinders__Composite0.event_CYL_IND(true, false, true, true, false);
      pnpCylinders__Composite0.event_CLK((-7), true);
      pnpCylinders__Composite0.event_RESUME();
      pnpCylinders__Composite0.event_CYL_IND(false, true, false, true, true);
      pnpCylinders__Composite0.event_CLK((-7), false);
  }

  //Test case number: 9
  /*
   * 7 covered goals:
   * 1 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType1.service_CLK()V: I111 Branch 52 IFEQ L923 - true
   * 2 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType1.service_CLK()V: I127 Branch 54 IFEQ L923 - false
   * 3 fb.rt.pnp.PnpCylinders__Composite.transition_MovementBlockType1_4()V: root-Branch
   * 4 fb.rt.pnp.PnpCylinders__Composite.transition_MovementBlockType2_8()V: root-Branch
   * 5 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType2.service_CLK()V: I119 Branch 177 IFEQ L1839 - true
   * 6 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType2.service_CLK()V: I159 Branch 180 IF_ICMPNE L1847 - false
   * 7 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType2.service_CLK()V: I163 Branch 181 IFNE L1847 - false
   */

  @Test
  public void test09()  throws Throwable  {
      PnpCylinders__Composite pnpCylinders__Composite0 = new PnpCylinders__Composite();
      pnpCylinders__Composite0.event_INIT((-14), (-14), false, false, (-14), (-14), (-14), (-14), (-14), (float) (-14), (-14), false, (-14), (-14), (-14), (-14), false, false, (-14), (-14), false, (-14));
      pnpCylinders__Composite0.event_CYL_IND(true, false, true, false, false);
      pnpCylinders__Composite0.event_CYL_IND(false, false, false, false, false);
  }

  //Test case number: 10
  /*
   * 5 covered goals:
   * 1 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType1.service_CLK()V: I397 Branch 78 IFEQ L959 - false
   * 2 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType1.service_RESUME()V: I5 Branch 92 IF_ICMPNE L995 - true
   * 3 fb.rt.pnp.PnpCylinders__Composite.transition_MovementBlockType1_13()V: root-Branch
   * 4 fb.rt.pnp.PnpCylinders__Composite.transition_MovementBlockType2_10()V: root-Branch
   * 5 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType2.service_FAULT()V: I23 Branch 183 IF_ICMPNE L1859 - false
   */

  @Test
  public void test10()  throws Throwable  {
      PnpCylinders__Composite pnpCylinders__Composite0 = new PnpCylinders__Composite();
      pnpCylinders__Composite0.event_INIT(27, 27, true, true, 27, 27, 27, 27, 27, (float) 27, 27, true, 27, 27, 27, 27, true, true, 27, 27, false, 27);
      pnpCylinders__Composite0.event_CYL_IND(false, true, true, true, true);
      pnpCylinders__Composite0.event_RESUME();
      pnpCylinders__Composite0.event_CYL_IND(true, true, true, true, true);
  }

  //Test case number: 11
  /*
   * 4 covered goals:
   * 1 fb.rt.pnp.PnpCylinders__Composite.transition_MovementBlockType2_7()V: root-Branch
   * 2 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType2.service_CLK()V: I97 Branch 175 IFNE L1835 - true
   * 3 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType2.service_CLK()V: I137 Branch 178 IF_ICMPNE L1843 - false
   * 4 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType2.service_CLK()V: I141 Branch 179 IFEQ L1843 - false
   */

  @Test
  public void test11()  throws Throwable  {
      PnpCylinders__Composite pnpCylinders__Composite0 = new PnpCylinders__Composite();
      pnpCylinders__Composite0.event_INIT(0, 0, true, true, 0, 1708, 1708, 1708, 1708, (float) 1708, 1708, true, 0, 1708, 1708, 0, true, true, 0, 1708, true, 0);
      pnpCylinders__Composite0.event_CYL_IND(false, true, false, true, true);
      pnpCylinders__Composite0.event_CYL_IND(false, true, true, false, true);
  }

  //Test case number: 12
  /*
   * 11 covered goals:
   * 1 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType1.service_CLK()V: I222 Branch 63 IFEQ L935 - false
   * 2 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType1.service_CLK()V: I229 Branch 64 IFEQ L935 - true
   * 3 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType1.service_CLK()V: I311 Branch 71 IF_ICMPNE L947 - false
   * 4 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType1.service_CLK()V: I319 Branch 72 IFEQ L947 - true
   * 5 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType1.service_CLK()V: I319 Branch 72 IFEQ L947 - false
   * 6 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType1.service_CLK()V: I479 Branch 85 IF_ICMPNE L971 - false
   * 7 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType1.service_CLK()V: I483 Branch 86 IFEQ L971 - true
   * 8 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType1.service_CLK()V: I492 Branch 87 IFEQ L971 - true
   * 9 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType1.service_CLK()V: I499 Branch 88 IFEQ L971 - false
   * 10 fb.rt.pnp.PnpCylinders__Composite.transition_MovementBlockType1_10()V: root-Branch
   * 11 fb.rt.pnp.PnpCylinders__Composite.transition_MovementBlockType1_16()V: root-Branch
   */

  @Test
  public void test12()  throws Throwable  {
      PnpCylinders__Composite pnpCylinders__Composite0 = new PnpCylinders__Composite();
      pnpCylinders__Composite0.event_INIT(1747, 1747, false, false, 1747, 1747, 1747, 1747, 1747, (float) 1747, 1747, false, 1747, 1747, 1747, 1747, false, true, 1747, 1747, false, 1747);
      pnpCylinders__Composite0.event_CYL_IND(false, false, false, false, false);
      pnpCylinders__Composite0.event_CYL_IND(false, false, true, true, false);
  }

  //Test case number: 13
  /*
   * 19 covered goals:
   * 1 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType1.service_CLK()V: I107 Branch 51 IF_ICMPNE L923 - false
   * 2 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType1.service_CLK()V: I111 Branch 52 IFEQ L923 - false
   * 3 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType1.service_CLK()V: I120 Branch 53 IFEQ L923 - true
   * 4 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType1.service_CLK()V: I127 Branch 54 IFEQ L923 - true
   * 5 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType1.service_CLK()V: I247 Branch 65 IF_ICMPNE L939 - false
   * 6 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType1.service_CLK()V: I254 Branch 66 IFEQ L939 - false
   * 7 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType1.service_CLK()V: I261 Branch 67 IFEQ L939 - true
   * 8 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType1.service_CLK()V: I363 Branch 75 IF_ICMPNE L955 - false
   * 9 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType1.service_CLK()V: I371 Branch 76 IFEQ L955 - true
   * 10 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType1.service_CLK()V: I389 Branch 77 IF_ICMPNE L959 - true
   * 11 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType1.service_CLK()V: I415 Branch 79 IF_ICMPNE L963 - false
   * 12 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType1.service_CLK()V: I422 Branch 80 IFEQ L963 - true
   * 13 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType1.service_CLK()V: I429 Branch 81 IFEQ L963 - false
   * 14 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType1.service_CLK()V: I447 Branch 82 IF_ICMPNE L967 - true
   * 15 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType1.service_CLK()V: I479 Branch 85 IF_ICMPNE L971 - true
   * 16 fb.rt.pnp.PnpCylinders__Composite.transition_MovementBlockType2_6()V: root-Branch
   * 17 fb.rt.pnp.PnpCylinders__Composite.transition_MovementBlockType1_14()V: root-Branch
   * 18 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType2.service_CLK()V: I115 Branch 176 IF_ICMPNE L1839 - false
   * 19 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType2.service_CLK()V: I119 Branch 177 IFEQ L1839 - false
   */

  @Test
  public void test13()  throws Throwable  {
      PnpCylinders__Composite pnpCylinders__Composite0 = new PnpCylinders__Composite();
      pnpCylinders__Composite0.event_INIT((-16), (-16), true, true, (-16), (-16), (-16), (-16), (-16), (float) (-16), (-16), false, (-16), (-16), (-16), (-16), false, true, (-16), (-16), true, (-16));
      pnpCylinders__Composite0.event_CYL_IND(true, true, true, false, false);
      pnpCylinders__Composite0.event_CYL_IND(false, false, true, false, true);
  }

  //Test case number: 14
  /*
   * 107 covered goals:
   * 1 fb.rt.pnp.PnpCylinders__Composite$LinearMotionLoad.state_MOVE_BWD()V: root-Branch
   * 2 fb.rt.pnp.PnpCylinders__Composite$LinearMotionLoad.state_MOVE_FWD()V: root-Branch
   * 3 fb.rt.pnp.PnpCylinders__Composite$LinearMotionLoad.service_CLK()V: I5 Branch 106 IF_ICMPNE L1289 - true
   * 4 fb.rt.pnp.PnpCylinders__Composite$LinearMotionLoad.service_CLK()V: I5 Branch 106 IF_ICMPNE L1289 - false
   * 5 fb.rt.pnp.PnpCylinders__Composite$LinearMotionLoad.service_CLK()V: I9 Branch 107 IFEQ L1289 - true
   * 6 fb.rt.pnp.PnpCylinders__Composite$LinearMotionLoad.service_CLK()V: I9 Branch 107 IFEQ L1289 - false
   * 7 fb.rt.pnp.PnpCylinders__Composite$LinearMotionLoad.service_CLK()V: I27 Branch 108 IF_ICMPNE L1293 - true
   * 8 fb.rt.pnp.PnpCylinders__Composite$LinearMotionLoad.service_CLK()V: I27 Branch 108 IF_ICMPNE L1293 - false
   * 9 fb.rt.pnp.PnpCylinders__Composite$LinearMotionLoad.service_CLK()V: I31 Branch 109 IFEQ L1293 - true
   * 10 fb.rt.pnp.PnpCylinders__Composite$LinearMotionLoad.service_CLK()V: I40 Branch 110 IFEQ L1293 - false
   * 11 fb.rt.pnp.PnpCylinders__Composite$LinearMotionLoad.service_CLK()V: I47 Branch 111 IFEQ L1293 - true
   * 12 fb.rt.pnp.PnpCylinders__Composite$LinearMotionLoad.service_CLK()V: I65 Branch 112 IF_ICMPNE L1297 - true
   * 13 fb.rt.pnp.PnpCylinders__Composite$LinearMotionLoad.service_CLK()V: I65 Branch 112 IF_ICMPNE L1297 - false
   * 14 fb.rt.pnp.PnpCylinders__Composite$LinearMotionLoad.service_CLK()V: I69 Branch 113 IFEQ L1297 - true
   * 15 fb.rt.pnp.PnpCylinders__Composite$LinearMotionLoad.service_CLK()V: I69 Branch 113 IFEQ L1297 - false
   * 16 fb.rt.pnp.PnpCylinders__Composite$LinearMotionLoad.service_CLK()V: I78 Branch 114 IFEQ L1297 - true
   * 17 fb.rt.pnp.PnpCylinders__Composite$LinearMotionLoad.service_CLK()V: I78 Branch 114 IFEQ L1297 - false
   * 18 fb.rt.pnp.PnpCylinders__Composite$LinearMotionLoad.service_CLK()V: I85 Branch 115 IFEQ L1297 - true
   * 19 fb.rt.pnp.PnpCylinders__Composite$LinearMotionLoad.service_CLK()V: I103 Branch 116 IF_ICMPNE L1301 - true
   * 20 fb.rt.pnp.PnpCylinders__Composite$LinearMotionLoad.service_CLK()V: I125 Branch 118 IF_ICMPNE L1305 - true
   * 21 fb.rt.pnp.PnpCylinders__Composite$LinearMotionLoad.service_CLK()V: I147 Branch 120 IF_ICMPNE L1309 - true
   * 22 fb.rt.pnp.PnpCylinders__Composite$LinearMotionLoad.service_CLK()V: I147 Branch 120 IF_ICMPNE L1309 - false
   * 23 fb.rt.pnp.PnpCylinders__Composite$LinearMotionLoad.service_CLK()V: I151 Branch 121 IFNE L1309 - true
   * 24 fb.rt.pnp.PnpCylinders__Composite$LinearMotionLoad.service_CLK()V: I169 Branch 122 IF_ICMPNE L1313 - true
   * 25 fb.rt.pnp.PnpCylinders__Composite$LinearMotionLoad.service_CLK()V: I169 Branch 122 IF_ICMPNE L1313 - false
   * 26 fb.rt.pnp.PnpCylinders__Composite$LinearMotionLoad.service_CLK()V: I173 Branch 123 IFEQ L1313 - false
   * 27 fb.rt.pnp.PnpCylinders__Composite$LinearMotionLoad.service_CLK()V: I191 Branch 124 IF_ICMPNE L1317 - true
   * 28 fb.rt.pnp.PnpCylinders__Composite$LinearMotionLoad.service_CLK()V: I191 Branch 124 IF_ICMPNE L1317 - false
   * 29 fb.rt.pnp.PnpCylinders__Composite$LinearMotionLoad.service_CLK()V: I195 Branch 125 IFEQ L1317 - true
   * 30 fb.rt.pnp.PnpCylinders__Composite$LinearMotionLoad.service_CLK()V: I195 Branch 125 IFEQ L1317 - false
   * 31 fb.rt.pnp.PnpCylinders__Composite$LinearMotionLoad.service_CLK()V: I213 Branch 126 IF_ICMPNE L1321 - true
   * 32 fb.rt.pnp.PnpCylinders__Composite$LinearMotionLoad.service_CLK()V: I246 Branch 129 IF_ICMPNE L1325 - true
   * 33 fb.rt.pnp.PnpCylinders__Composite$LinearMotionLoad.service_CLK()V: I246 Branch 129 IF_ICMPNE L1325 - false
   * 34 fb.rt.pnp.PnpCylinders__Composite$LinearMotionLoad.service_CLK()V: I253 Branch 130 IFLE L1325 - false
   * 35 fb.rt.pnp.PnpCylinders__Composite$LinearMotionLoad.service_CLK()V: I260 Branch 131 IFEQ L1325 - false
   * 36 fb.rt.pnp.PnpCylinders__Composite$LinearMotionLoad.service_CLK()V: I278 Branch 132 IF_ICMPNE L1329 - false
   * 37 fb.rt.pnp.PnpCylinders__Composite$LinearMotionLoad.service_CLK()V: I282 Branch 133 IFEQ L1329 - false
   * 38 fb.rt.pnp.PnpCylinders__Composite$LinearMotionLoad.alg_DECR()V: I9 Branch 140 IFEQ L1384 - false
   * 39 fb.rt.pnp.PnpCylinders__Composite$LinearMotionLoad.alg_DECR()V: I13 Branch 141 IFLE L1384 - true
   * 40 fb.rt.pnp.PnpCylinders__Composite$LinearMotionLoad.alg_DECR()V: I84 Branch 143 IFGE L1393 - true
   * 41 fb.rt.pnp.PnpCylinders__Composite$LinearMotionLoad.alg_DECR()V: I84 Branch 143 IFGE L1393 - false
   * 42 fb.rt.pnp.PnpCylinders__Composite$LinearMotionLoad.alg_INCR()V: I9 Branch 136 IFEQ L1357 - false
   * 43 fb.rt.pnp.PnpCylinders__Composite$LinearMotionLoad.alg_INCR()V: I13 Branch 137 IFLE L1357 - true
   * 44 fb.rt.pnp.PnpCylinders__Composite$LinearMotionLoad.alg_INCR()V: I93 Branch 139 IFLE L1366 - false
   * 45 fb.rt.pnp.PnpCylinders__Composite$LinearMotionLoad.serviceEvent(Lfb/rt/EventServer;)V: I5 Branch 103 IF_ACMPNE L1275 - true
   * 46 fb.rt.pnp.PnpCylinders__Composite$LinearMotionLoad.serviceEvent(Lfb/rt/EventServer;)V: I14 Branch 104 IF_ACMPNE L1276 - false
   * 47 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType1.service_CLK()V: I82 Branch 49 IFEQ L919 - true
   * 48 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType1.service_CLK()V: I89 Branch 50 IFEQ L919 - false
   * 49 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType1.service_CLK()V: I145 Branch 55 IF_ICMPNE L927 - false
   * 50 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType1.service_CLK()V: I149 Branch 56 IFEQ L927 - true
   * 51 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType1.service_CLK()V: I149 Branch 56 IFEQ L927 - false
   * 52 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType1.service_CLK()V: I158 Branch 57 IFEQ L927 - true
   * 53 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType1.service_CLK()V: I158 Branch 57 IFEQ L927 - false
   * 54 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType1.service_CLK()V: I165 Branch 58 IFEQ L927 - true
   * 55 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType1.service_CLK()V: I279 Branch 68 IF_ICMPNE L943 - false
   * 56 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType1.service_CLK()V: I286 Branch 69 IFEQ L943 - true
   * 57 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType1.service_CLK()V: I286 Branch 69 IFEQ L943 - false
   * 58 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType1.service_CLK()V: I293 Branch 70 IFEQ L943 - true
   * 59 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType1.service_CLK()V: I293 Branch 70 IFEQ L943 - false
   * 60 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType1.service_CLK()V: I337 Branch 73 IF_ICMPNE L951 - true
   * 61 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType1.service_CLK()V: I363 Branch 75 IF_ICMPNE L955 - true
   * 62 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType1.service_CLK()V: I389 Branch 77 IF_ICMPNE L959 - false
   * 63 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType1.service_CLK()V: I397 Branch 78 IFEQ L959 - true
   * 64 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType1.service_CLK()V: I415 Branch 79 IF_ICMPNE L963 - true
   * 65 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType1.service_CLK()V: I447 Branch 82 IF_ICMPNE L967 - false
   * 66 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType1.service_CLK()V: I454 Branch 83 IFEQ L967 - true
   * 67 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType1.service_CLK()V: I461 Branch 84 IFEQ L967 - false
   * 68 fb.rt.pnp.PnpCylinders__Composite.transition_LinearMotionLoad_8()V: root-Branch
   * 69 fb.rt.pnp.PnpCylinders__Composite.transition_LinearMotionLoad_12()V: root-Branch
   * 70 fb.rt.pnp.PnpCylinders__Composite.transition_PnPSensor_3()V: root-Branch
   * 71 fb.rt.pnp.PnpCylinders__Composite.event_CLK(IZ)V: root-Branch
   * 72 fb.rt.pnp.PnpCylinders__Composite.transition_MovementBlockType1_3()V: root-Branch
   * 73 fb.rt.pnp.PnpCylinders__Composite.transition_LinearMotionLoad_11()V: root-Branch
   * 74 fb.rt.pnp.PnpCylinders__Composite.transition_MovementBlockType2_1()V: root-Branch
   * 75 fb.rt.pnp.PnpCylinders__Composite.transition_MovementBlockType2_5()V: root-Branch
   * 76 fb.rt.pnp.PnpCylinders__Composite.transition_MovementBlockType1_15()V: root-Branch
   * 77 fb.rt.pnp.PnpCylinders__Composite.transition_PnPSensor_1()V: root-Branch
   * 78 fb.rt.pnp.PnpCylinders__Composite.transition_LinearMotionLoad_2()V: root-Branch
   * 79 fb.rt.pnp.PnpCylinders__Composite.transition_MovementBlockType1_9()V: root-Branch
   * 80 fb.rt.pnp.PnpCylinders__Composite.transition_LinearMotionLoad_9()V: root-Branch
   * 81 fb.rt.pnp.PnpCylinders__Composite.transition_PnPSensor_2()V: root-Branch
   * 82 fb.rt.pnp.PnpCylinders__Composite$PnPSensor.alg_EMITCHG()V: root-Branch
   * 83 fb.rt.pnp.PnpCylinders__Composite$PnPSensor.state_EMITCHG()V: root-Branch
   * 84 fb.rt.pnp.PnpCylinders__Composite$PnPSensor.service_CLK()V: I5 Branch 23 IF_ICMPNE L713 - true
   * 85 fb.rt.pnp.PnpCylinders__Composite$PnPSensor.service_CLK()V: I5 Branch 23 IF_ICMPNE L713 - false
   * 86 fb.rt.pnp.PnpCylinders__Composite$PnPSensor.service_CLK()V: I23 Branch 24 IF_ICMPNE L717 - true
   * 87 fb.rt.pnp.PnpCylinders__Composite$PnPSensor.service_CLK()V: I23 Branch 24 IF_ICMPNE L717 - false
   * 88 fb.rt.pnp.PnpCylinders__Composite$PnPSensor.service_CLK()V: I41 Branch 25 IF_ICMPNE L721 - false
   * 89 fb.rt.pnp.PnpCylinders__Composite$PnPSensor.alg_DETECT()V: I12 Branch 28 IF_ICMPLT L741 - true
   * 90 fb.rt.pnp.PnpCylinders__Composite$PnPSensor.alg_DETECT()V: I12 Branch 28 IF_ICMPLT L741 - false
   * 91 fb.rt.pnp.PnpCylinders__Composite$PnPSensor.alg_DETECT()V: I23 Branch 29 IF_ICMPGT L741 - true
   * 92 fb.rt.pnp.PnpCylinders__Composite$PnPSensor.alg_DETECT()V: I23 Branch 29 IF_ICMPGT L741 - false
   * 93 fb.rt.pnp.PnpCylinders__Composite$PnPSensor.alg_DETECT()V: I29 Branch 30 IFNE L742 - true
   * 94 fb.rt.pnp.PnpCylinders__Composite$PnPSensor.alg_DETECT()V: I29 Branch 30 IFNE L742 - false
   * 95 fb.rt.pnp.PnpCylinders__Composite$PnPSensor.alg_DETECT()V: I50 Branch 31 IFEQ L748 - true
   * 96 fb.rt.pnp.PnpCylinders__Composite$PnPSensor.alg_DETECT()V: I50 Branch 31 IFEQ L748 - false
   * 97 fb.rt.pnp.PnpCylinders__Composite$PnPSensor.alg_INIT()V: I12 Branch 26 IF_ICMPLT L729 - false
   * 98 fb.rt.pnp.PnpCylinders__Composite$PnPSensor.alg_INIT()V: I23 Branch 27 IF_ICMPGT L729 - false
   * 99 fb.rt.pnp.PnpCylinders__Composite$PnPSensor.state_DETECT()V: I14 Branch 19 IFEQ L682 - true
   * 100 fb.rt.pnp.PnpCylinders__Composite$PnPSensor.state_DETECT()V: I14 Branch 19 IFEQ L682 - false
   * 101 fb.rt.pnp.PnpCylinders__Composite$PnPSensor.serviceEvent(Lfb/rt/EventServer;)V: I5 Branch 20 IF_ACMPNE L699 - true
   * 102 fb.rt.pnp.PnpCylinders__Composite$PnPSensor.serviceEvent(Lfb/rt/EventServer;)V: I14 Branch 21 IF_ACMPNE L700 - false
   * 103 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType2.state_MOVE_FWD()V: root-Branch
   * 104 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType2.alg_FWD()V: root-Branch
   * 105 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType2.service_CLK()V: I9 Branch 167 IFEQ L1819 - false
   * 106 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType2.service_CLK()V: I93 Branch 174 IF_ICMPNE L1835 - false
   * 107 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType2.service_CLK()V: I97 Branch 175 IFNE L1835 - false
   */

  @Test
  public void test14()  throws Throwable  {
      PnpCylinders__Composite pnpCylinders__Composite0 = new PnpCylinders__Composite();
      pnpCylinders__Composite0.event_INIT(0, 0, true, true, 0, 1708, 1708, 1708, 1708, (float) 1708, 1708, true, 0, 1708, 1708, 0, true, true, 0, 1708, true, 0);
      pnpCylinders__Composite0.event_CYL_IND(false, true, false, true, true);
      pnpCylinders__Composite0.event_CLK(0, true);
      pnpCylinders__Composite0.event_CYL_IND(false, true, true, false, false);
      pnpCylinders__Composite0.event_CLK(0, true);
  }

  //Test case number: 15
  /*
   * 60 covered goals:
   * 1 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType1.alg_BWD()V: root-Branch
   * 2 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType1.state_MOVE_BWD()V: root-Branch
   * 3 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType1.service_CLK()V: I5 Branch 41 IF_ICMPNE L911 - true
   * 4 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType1.service_CLK()V: I12 Branch 42 IFEQ L911 - false
   * 5 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType1.service_CLK()V: I37 Branch 44 IF_ICMPNE L915 - true
   * 6 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType1.service_CLK()V: I41 Branch 45 IFEQ L915 - false
   * 7 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType1.service_CLK()V: I50 Branch 46 IFEQ L915 - false
   * 8 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType1.service_CLK()V: I57 Branch 47 IFEQ L915 - true
   * 9 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType1.service_CLK()V: I75 Branch 48 IF_ICMPNE L919 - true
   * 10 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType1.service_CLK()V: I75 Branch 48 IF_ICMPNE L919 - false
   * 11 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType1.service_CLK()V: I82 Branch 49 IFEQ L919 - false
   * 12 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType1.service_CLK()V: I89 Branch 50 IFEQ L919 - true
   * 13 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType1.service_CLK()V: I107 Branch 51 IF_ICMPNE L923 - true
   * 14 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType1.service_CLK()V: I145 Branch 55 IF_ICMPNE L927 - true
   * 15 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType1.service_CLK()V: I183 Branch 59 IF_ICMPNE L931 - true
   * 16 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType1.service_CLK()V: I183 Branch 59 IF_ICMPNE L931 - false
   * 17 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType1.service_CLK()V: I190 Branch 60 IFEQ L931 - true
   * 18 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType1.service_CLK()V: I190 Branch 60 IFEQ L931 - false
   * 19 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType1.service_CLK()V: I197 Branch 61 IFEQ L931 - true
   * 20 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType1.service_CLK()V: I197 Branch 61 IFEQ L931 - false
   * 21 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType1.service_CLK()V: I215 Branch 62 IF_ICMPNE L935 - true
   * 22 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType1.service_CLK()V: I215 Branch 62 IF_ICMPNE L935 - false
   * 23 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType1.service_CLK()V: I222 Branch 63 IFEQ L935 - true
   * 24 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType1.service_CLK()V: I229 Branch 64 IFEQ L935 - false
   * 25 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType1.service_CLK()V: I247 Branch 65 IF_ICMPNE L939 - true
   * 26 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType1.service_CLK()V: I279 Branch 68 IF_ICMPNE L943 - true
   * 27 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType1.service_CLK()V: I311 Branch 71 IF_ICMPNE L947 - true
   * 28 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType1.service_CLK()V: I337 Branch 73 IF_ICMPNE L951 - false
   * 29 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType1.service_CLK()V: I345 Branch 74 IFEQ L951 - false
   * 30 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType1.service_FAULT()V: I23 Branch 90 IF_ICMPNE L983 - true
   * 31 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType1.service_FAULT()V: I41 Branch 91 IF_ICMPNE L987 - true
   * 32 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType1.service_RESUME()V: I5 Branch 92 IF_ICMPNE L995 - false
   * 33 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType1.serviceEvent(Lfb/rt/EventServer;)V: I23 Branch 38 IF_ACMPNE L897 - true
   * 34 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType1.serviceEvent(Lfb/rt/EventServer;)V: I32 Branch 39 IF_ACMPNE L898 - false
   * 35 fb.rt.pnp.PnpCylinders__Composite.transition_MovementBlockType2_12()V: root-Branch
   * 36 fb.rt.pnp.PnpCylinders__Composite.event_RESUME()V: root-Branch
   * 37 fb.rt.pnp.PnpCylinders__Composite.transition_MovementBlockType1_6()V: root-Branch
   * 38 fb.rt.pnp.PnpCylinders__Composite.transition_MovementBlockType1_7()V: root-Branch
   * 39 fb.rt.pnp.PnpCylinders__Composite.transition_MovementBlockType1_20()V: root-Branch
   * 40 fb.rt.pnp.PnpCylinders__Composite.transition_MovementBlockType1_11()V: root-Branch
   * 41 fb.rt.pnp.PnpCylinders__Composite.transition_MovementBlockType2_4()V: root-Branch
   * 42 fb.rt.pnp.PnpCylinders__Composite.transition_MovementBlockType2_13()V: root-Branch
   * 43 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType2.state_STOP()V: root-Branch
   * 44 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType2.service_CLK()V: I5 Branch 166 IF_ICMPNE L1819 - true
   * 45 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType2.service_CLK()V: I27 Branch 168 IF_ICMPNE L1823 - true
   * 46 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType2.service_CLK()V: I49 Branch 170 IF_ICMPNE L1827 - true
   * 47 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType2.service_CLK()V: I49 Branch 170 IF_ICMPNE L1827 - false
   * 48 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType2.service_CLK()V: I53 Branch 171 IFEQ L1827 - true
   * 49 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType2.service_CLK()V: I71 Branch 172 IF_ICMPNE L1831 - true
   * 50 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType2.service_CLK()V: I71 Branch 172 IF_ICMPNE L1831 - false
   * 51 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType2.service_CLK()V: I75 Branch 173 IFNE L1831 - false
   * 52 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType2.service_CLK()V: I93 Branch 174 IF_ICMPNE L1835 - true
   * 53 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType2.service_CLK()V: I115 Branch 176 IF_ICMPNE L1839 - true
   * 54 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType2.service_CLK()V: I137 Branch 178 IF_ICMPNE L1843 - true
   * 55 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType2.service_CLK()V: I159 Branch 180 IF_ICMPNE L1847 - true
   * 56 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType2.service_FAULT()V: I41 Branch 184 IF_ICMPNE L1863 - true
   * 57 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType2.service_FAULT()V: I59 Branch 185 IF_ICMPNE L1867 - false
   * 58 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType2.service_RESUME()V: I5 Branch 186 IF_ICMPNE L1875 - false
   * 59 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType2.serviceEvent(Lfb/rt/EventServer;)V: I23 Branch 163 IF_ACMPNE L1805 - true
   * 60 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType2.serviceEvent(Lfb/rt/EventServer;)V: I32 Branch 164 IF_ACMPNE L1806 - false
   */

  @Test
  public void test15()  throws Throwable  {
      PnpCylinders__Composite pnpCylinders__Composite0 = new PnpCylinders__Composite();
      pnpCylinders__Composite0.event_INIT((-13), (-13), true, true, (-13), (-13), (-13), (-13), (-13), (float) (-13), (-13), true, (-13), (-13), (-13), (-13), true, true, (-13), (-13), true, (-13));
      pnpCylinders__Composite0.event_CYL_IND(true, true, true, true, true);
      pnpCylinders__Composite0.event_RESUME();
      pnpCylinders__Composite0.event_CYL_IND(false, true, true, false, false);
  }

  //Test case number: 16
  /*
   * 194 covered goals:
   * 1 fb.rt.pnp.PnpCylinders__Composite$LinearMotionLoad.connect_InitialPosition(Lfb/datatype/REAL;)V: root-Branch
   * 2 fb.rt.pnp.PnpCylinders__Composite$LinearMotionLoad.connect_LoadType(Lfb/datatype/UINT;)V: root-Branch
   * 3 fb.rt.pnp.PnpCylinders__Composite$LinearMotionLoad.<init>(Lfb/rt/pnp/PnpCylinders__Composite;)V: root-Branch
   * 4 fb.rt.pnp.PnpCylinders__Composite$LinearMotionLoad.state_HOME()V: root-Branch
   * 5 fb.rt.pnp.PnpCylinders__Composite$LinearMotionLoad.connect_ForwardSpeed(Lfb/datatype/UINT;)V: root-Branch
   * 6 fb.rt.pnp.PnpCylinders__Composite$LinearMotionLoad.connect_MoveBackwards(Lfb/datatype/BOOL;)V: root-Branch
   * 7 fb.rt.pnp.PnpCylinders__Composite$LinearMotionLoad.connect_MovingDistance(Lfb/datatype/UINT;)V: root-Branch
   * 8 fb.rt.pnp.PnpCylinders__Composite$LinearMotionLoad.connect_BackwardSpeed(Lfb/datatype/UINT;)V: root-Branch
   * 9 fb.rt.pnp.PnpCylinders__Composite$LinearMotionLoad.connect_Loaded(Lfb/datatype/BOOL;)V: root-Branch
   * 10 fb.rt.pnp.PnpCylinders__Composite$LinearMotionLoad.state_INIT()V: root-Branch
   * 11 fb.rt.pnp.PnpCylinders__Composite$LinearMotionLoad.alg_INIT()V: root-Branch
   * 12 fb.rt.pnp.PnpCylinders__Composite$LinearMotionLoad.connect_MoveForwards(Lfb/datatype/BOOL;)V: root-Branch
   * 13 fb.rt.pnp.PnpCylinders__Composite$LinearMotionLoad.ovNamed(Ljava/lang/String;)Lfb/datatype/ANY;: I5 Branch 93 IFLE L1157 - true
   * 14 fb.rt.pnp.PnpCylinders__Composite$LinearMotionLoad.ovNamed(Ljava/lang/String;)Lfb/datatype/ANY;: I5 Branch 93 IFLE L1157 - false
   * 15 fb.rt.pnp.PnpCylinders__Composite$LinearMotionLoad.ovNamed(Ljava/lang/String;)Lfb/datatype/ANY;: I14 Branch 94 IFLE L1158 - false
   * 16 fb.rt.pnp.PnpCylinders__Composite$LinearMotionLoad.service_INIT()V: I4 Branch 105 IFNE L1281 - false
   * 17 fb.rt.pnp.PnpCylinders__Composite$LinearMotionLoad.connectIV(Ljava/lang/String;Lfb/datatype/ANY;)V: I5 Branch 95 IFLE L1167 - true
   * 18 fb.rt.pnp.PnpCylinders__Composite$LinearMotionLoad.connectIV(Ljava/lang/String;Lfb/datatype/ANY;)V: I5 Branch 95 IFLE L1167 - false
   * 19 fb.rt.pnp.PnpCylinders__Composite$LinearMotionLoad.connectIV(Ljava/lang/String;Lfb/datatype/ANY;)V: I16 Branch 96 IFLE L1168 - true
   * 20 fb.rt.pnp.PnpCylinders__Composite$LinearMotionLoad.connectIV(Ljava/lang/String;Lfb/datatype/ANY;)V: I16 Branch 96 IFLE L1168 - false
   * 21 fb.rt.pnp.PnpCylinders__Composite$LinearMotionLoad.connectIV(Ljava/lang/String;Lfb/datatype/ANY;)V: I27 Branch 97 IFLE L1169 - true
   * 22 fb.rt.pnp.PnpCylinders__Composite$LinearMotionLoad.connectIV(Ljava/lang/String;Lfb/datatype/ANY;)V: I27 Branch 97 IFLE L1169 - false
   * 23 fb.rt.pnp.PnpCylinders__Composite$LinearMotionLoad.connectIV(Ljava/lang/String;Lfb/datatype/ANY;)V: I38 Branch 98 IFLE L1170 - true
   * 24 fb.rt.pnp.PnpCylinders__Composite$LinearMotionLoad.connectIV(Ljava/lang/String;Lfb/datatype/ANY;)V: I38 Branch 98 IFLE L1170 - false
   * 25 fb.rt.pnp.PnpCylinders__Composite$LinearMotionLoad.connectIV(Ljava/lang/String;Lfb/datatype/ANY;)V: I49 Branch 99 IFLE L1171 - true
   * 26 fb.rt.pnp.PnpCylinders__Composite$LinearMotionLoad.connectIV(Ljava/lang/String;Lfb/datatype/ANY;)V: I49 Branch 99 IFLE L1171 - false
   * 27 fb.rt.pnp.PnpCylinders__Composite$LinearMotionLoad.connectIV(Ljava/lang/String;Lfb/datatype/ANY;)V: I60 Branch 100 IFLE L1172 - true
   * 28 fb.rt.pnp.PnpCylinders__Composite$LinearMotionLoad.connectIV(Ljava/lang/String;Lfb/datatype/ANY;)V: I60 Branch 100 IFLE L1172 - false
   * 29 fb.rt.pnp.PnpCylinders__Composite$LinearMotionLoad.connectIV(Ljava/lang/String;Lfb/datatype/ANY;)V: I71 Branch 101 IFLE L1173 - true
   * 30 fb.rt.pnp.PnpCylinders__Composite$LinearMotionLoad.connectIV(Ljava/lang/String;Lfb/datatype/ANY;)V: I71 Branch 101 IFLE L1173 - false
   * 31 fb.rt.pnp.PnpCylinders__Composite$LinearMotionLoad.connectIV(Ljava/lang/String;Lfb/datatype/ANY;)V: I82 Branch 102 IFLE L1174 - false
   * 32 fb.rt.pnp.PnpCylinders__Composite$LinearMotionLoad.serviceEvent(Lfb/rt/EventServer;)V: I5 Branch 103 IF_ACMPNE L1275 - false
   * 33 fb.rt.pnp.PnpCylinders__Composite$GenericCylinderModelType2.connect_EndSensorRange(Lfb/datatype/ARRAY;)V: root-Branch
   * 34 fb.rt.pnp.PnpCylinders__Composite$GenericCylinderModelType2.connect_Loaded(Lfb/datatype/BOOL;)V: root-Branch
   * 35 fb.rt.pnp.PnpCylinders__Composite$GenericCylinderModelType2.<init>(Lfb/rt/pnp/PnpCylinders__Composite;)V: root-Branch
   * 36 fb.rt.pnp.PnpCylinders__Composite$GenericCylinderModelType2.connect_ForwardSpeed(Lfb/datatype/UINT;)V: root-Branch
   * 37 fb.rt.pnp.PnpCylinders__Composite$GenericCylinderModelType2.connect_InitialPosition(Lfb/datatype/REAL;)V: root-Branch
   * 38 fb.rt.pnp.PnpCylinders__Composite$GenericCylinderModelType2.connect_MovingtDistance(Lfb/datatype/UINT;)V: root-Branch
   * 39 fb.rt.pnp.PnpCylinders__Composite$GenericCylinderModelType2.connect_BackwardSpeed(Lfb/datatype/UINT;)V: root-Branch
   * 40 fb.rt.pnp.PnpCylinders__Composite$GenericCylinderModelType2.connect_HomeSensorRange(Lfb/datatype/ARRAY;)V: root-Branch
   * 41 fb.rt.pnp.PnpCylinders__Composite$GenericCylinderModelType2.connect_MidSensorRange(Lfb/datatype/ARRAY;)V: root-Branch
   * 42 fb.rt.pnp.PnpCylinders__Composite$GenericCylinderModelType2.connect_Extend(Lfb/datatype/BOOL;)V: root-Branch
   * 43 fb.rt.pnp.PnpCylinders__Composite$GenericCylinderModelType2.connect_LoadType(Lfb/datatype/UINT;)V: root-Branch
   * 44 fb.rt.pnp.PnpCylinders__Composite$GenericCylinderModelType2.ovNamed(Ljava/lang/String;)Lfb/datatype/ANY;: I5 Branch 144 IFLE L1519 - true
   * 45 fb.rt.pnp.PnpCylinders__Composite$GenericCylinderModelType2.ovNamed(Ljava/lang/String;)Lfb/datatype/ANY;: I5 Branch 144 IFLE L1519 - false
   * 46 fb.rt.pnp.PnpCylinders__Composite$GenericCylinderModelType2.ovNamed(Ljava/lang/String;)Lfb/datatype/ANY;: I14 Branch 145 IFLE L1520 - true
   * 47 fb.rt.pnp.PnpCylinders__Composite$GenericCylinderModelType2.ovNamed(Ljava/lang/String;)Lfb/datatype/ANY;: I14 Branch 145 IFLE L1520 - false
   * 48 fb.rt.pnp.PnpCylinders__Composite$GenericCylinderModelType2.ovNamed(Ljava/lang/String;)Lfb/datatype/ANY;: I23 Branch 146 IFLE L1521 - true
   * 49 fb.rt.pnp.PnpCylinders__Composite$GenericCylinderModelType2.ovNamed(Ljava/lang/String;)Lfb/datatype/ANY;: I23 Branch 146 IFLE L1521 - false
   * 50 fb.rt.pnp.PnpCylinders__Composite$GenericCylinderModelType2.ovNamed(Ljava/lang/String;)Lfb/datatype/ANY;: I32 Branch 147 IFLE L1522 - false
   * 51 fb.rt.pnp.PnpCylinders__Composite$GenericCylinderModelType2.connectIV(Ljava/lang/String;Lfb/datatype/ANY;)V: I5 Branch 148 IFLE L1531 - true
   * 52 fb.rt.pnp.PnpCylinders__Composite$GenericCylinderModelType2.connectIV(Ljava/lang/String;Lfb/datatype/ANY;)V: I5 Branch 148 IFLE L1531 - false
   * 53 fb.rt.pnp.PnpCylinders__Composite$GenericCylinderModelType2.connectIV(Ljava/lang/String;Lfb/datatype/ANY;)V: I16 Branch 149 IFLE L1532 - true
   * 54 fb.rt.pnp.PnpCylinders__Composite$GenericCylinderModelType2.connectIV(Ljava/lang/String;Lfb/datatype/ANY;)V: I16 Branch 149 IFLE L1532 - false
   * 55 fb.rt.pnp.PnpCylinders__Composite$GenericCylinderModelType2.connectIV(Ljava/lang/String;Lfb/datatype/ANY;)V: I27 Branch 150 IFLE L1533 - true
   * 56 fb.rt.pnp.PnpCylinders__Composite$GenericCylinderModelType2.connectIV(Ljava/lang/String;Lfb/datatype/ANY;)V: I27 Branch 150 IFLE L1533 - false
   * 57 fb.rt.pnp.PnpCylinders__Composite$GenericCylinderModelType2.connectIV(Ljava/lang/String;Lfb/datatype/ANY;)V: I38 Branch 151 IFLE L1534 - true
   * 58 fb.rt.pnp.PnpCylinders__Composite$GenericCylinderModelType2.connectIV(Ljava/lang/String;Lfb/datatype/ANY;)V: I38 Branch 151 IFLE L1534 - false
   * 59 fb.rt.pnp.PnpCylinders__Composite$GenericCylinderModelType2.connectIV(Ljava/lang/String;Lfb/datatype/ANY;)V: I49 Branch 152 IFLE L1535 - true
   * 60 fb.rt.pnp.PnpCylinders__Composite$GenericCylinderModelType2.connectIV(Ljava/lang/String;Lfb/datatype/ANY;)V: I49 Branch 152 IFLE L1535 - false
   * 61 fb.rt.pnp.PnpCylinders__Composite$GenericCylinderModelType2.connectIV(Ljava/lang/String;Lfb/datatype/ANY;)V: I60 Branch 153 IFLE L1536 - true
   * 62 fb.rt.pnp.PnpCylinders__Composite$GenericCylinderModelType2.connectIV(Ljava/lang/String;Lfb/datatype/ANY;)V: I60 Branch 153 IFLE L1536 - false
   * 63 fb.rt.pnp.PnpCylinders__Composite$GenericCylinderModelType2.connectIV(Ljava/lang/String;Lfb/datatype/ANY;)V: I71 Branch 154 IFLE L1537 - true
   * 64 fb.rt.pnp.PnpCylinders__Composite$GenericCylinderModelType2.connectIV(Ljava/lang/String;Lfb/datatype/ANY;)V: I71 Branch 154 IFLE L1537 - false
   * 65 fb.rt.pnp.PnpCylinders__Composite$GenericCylinderModelType2.connectIV(Ljava/lang/String;Lfb/datatype/ANY;)V: I82 Branch 155 IFLE L1538 - true
   * 66 fb.rt.pnp.PnpCylinders__Composite$GenericCylinderModelType2.connectIV(Ljava/lang/String;Lfb/datatype/ANY;)V: I82 Branch 155 IFLE L1538 - false
   * 67 fb.rt.pnp.PnpCylinders__Composite$GenericCylinderModelType2.connectIV(Ljava/lang/String;Lfb/datatype/ANY;)V: I93 Branch 156 IFLE L1539 - true
   * 68 fb.rt.pnp.PnpCylinders__Composite$GenericCylinderModelType2.connectIV(Ljava/lang/String;Lfb/datatype/ANY;)V: I93 Branch 156 IFLE L1539 - false
   * 69 fb.rt.pnp.PnpCylinders__Composite$GenericCylinderModelType2.connectIV(Ljava/lang/String;Lfb/datatype/ANY;)V: I104 Branch 157 IFLE L1540 - false
   * 70 fb.rt.pnp.PnpCylinders__Composite$GenericCylinderModelType1.connect_HomeSensorRange(Lfb/datatype/ARRAY;)V: root-Branch
   * 71 fb.rt.pnp.PnpCylinders__Composite$GenericCylinderModelType1.connect_MidSensorRange(Lfb/datatype/ARRAY;)V: root-Branch
   * 72 fb.rt.pnp.PnpCylinders__Composite$GenericCylinderModelType1.connect_Loaded(Lfb/datatype/BOOL;)V: root-Branch
   * 73 fb.rt.pnp.PnpCylinders__Composite$GenericCylinderModelType1.connect_ForwardSpeed(Lfb/datatype/UINT;)V: root-Branch
   * 74 fb.rt.pnp.PnpCylinders__Composite$GenericCylinderModelType1.connect_Extend(Lfb/datatype/BOOL;)V: root-Branch
   * 75 fb.rt.pnp.PnpCylinders__Composite$GenericCylinderModelType1.<init>(Lfb/rt/pnp/PnpCylinders__Composite;)V: root-Branch
   * 76 fb.rt.pnp.PnpCylinders__Composite$GenericCylinderModelType1.connect_EndSensorRange(Lfb/datatype/ARRAY;)V: root-Branch
   * 77 fb.rt.pnp.PnpCylinders__Composite$GenericCylinderModelType1.connect_BackwardSpeed(Lfb/datatype/UINT;)V: root-Branch
   * 78 fb.rt.pnp.PnpCylinders__Composite$GenericCylinderModelType1.connect_MovingtDistance(Lfb/datatype/UINT;)V: root-Branch
   * 79 fb.rt.pnp.PnpCylinders__Composite$GenericCylinderModelType1.connect_InitialPosition(Lfb/datatype/REAL;)V: root-Branch
   * 80 fb.rt.pnp.PnpCylinders__Composite$GenericCylinderModelType1.connect_LoadType(Lfb/datatype/UINT;)V: root-Branch
   * 81 fb.rt.pnp.PnpCylinders__Composite$GenericCylinderModelType1.connect_Retract(Lfb/datatype/BOOL;)V: root-Branch
   * 82 fb.rt.pnp.PnpCylinders__Composite$GenericCylinderModelType1.ovNamed(Ljava/lang/String;)Lfb/datatype/ANY;: I5 Branch 1 IFLE L412 - true
   * 83 fb.rt.pnp.PnpCylinders__Composite$GenericCylinderModelType1.ovNamed(Ljava/lang/String;)Lfb/datatype/ANY;: I5 Branch 1 IFLE L412 - false
   * 84 fb.rt.pnp.PnpCylinders__Composite$GenericCylinderModelType1.ovNamed(Ljava/lang/String;)Lfb/datatype/ANY;: I14 Branch 2 IFLE L413 - true
   * 85 fb.rt.pnp.PnpCylinders__Composite$GenericCylinderModelType1.ovNamed(Ljava/lang/String;)Lfb/datatype/ANY;: I14 Branch 2 IFLE L413 - false
   * 86 fb.rt.pnp.PnpCylinders__Composite$GenericCylinderModelType1.ovNamed(Ljava/lang/String;)Lfb/datatype/ANY;: I23 Branch 3 IFLE L414 - true
   * 87 fb.rt.pnp.PnpCylinders__Composite$GenericCylinderModelType1.ovNamed(Ljava/lang/String;)Lfb/datatype/ANY;: I23 Branch 3 IFLE L414 - false
   * 88 fb.rt.pnp.PnpCylinders__Composite$GenericCylinderModelType1.ovNamed(Ljava/lang/String;)Lfb/datatype/ANY;: I32 Branch 4 IFLE L415 - false
   * 89 fb.rt.pnp.PnpCylinders__Composite$GenericCylinderModelType1.connectIV(Ljava/lang/String;Lfb/datatype/ANY;)V: I5 Branch 5 IFLE L424 - true
   * 90 fb.rt.pnp.PnpCylinders__Composite$GenericCylinderModelType1.connectIV(Ljava/lang/String;Lfb/datatype/ANY;)V: I5 Branch 5 IFLE L424 - false
   * 91 fb.rt.pnp.PnpCylinders__Composite$GenericCylinderModelType1.connectIV(Ljava/lang/String;Lfb/datatype/ANY;)V: I16 Branch 6 IFLE L425 - true
   * 92 fb.rt.pnp.PnpCylinders__Composite$GenericCylinderModelType1.connectIV(Ljava/lang/String;Lfb/datatype/ANY;)V: I16 Branch 6 IFLE L425 - false
   * 93 fb.rt.pnp.PnpCylinders__Composite$GenericCylinderModelType1.connectIV(Ljava/lang/String;Lfb/datatype/ANY;)V: I27 Branch 7 IFLE L426 - true
   * 94 fb.rt.pnp.PnpCylinders__Composite$GenericCylinderModelType1.connectIV(Ljava/lang/String;Lfb/datatype/ANY;)V: I27 Branch 7 IFLE L426 - false
   * 95 fb.rt.pnp.PnpCylinders__Composite$GenericCylinderModelType1.connectIV(Ljava/lang/String;Lfb/datatype/ANY;)V: I38 Branch 8 IFLE L427 - true
   * 96 fb.rt.pnp.PnpCylinders__Composite$GenericCylinderModelType1.connectIV(Ljava/lang/String;Lfb/datatype/ANY;)V: I38 Branch 8 IFLE L427 - false
   * 97 fb.rt.pnp.PnpCylinders__Composite$GenericCylinderModelType1.connectIV(Ljava/lang/String;Lfb/datatype/ANY;)V: I49 Branch 9 IFLE L428 - true
   * 98 fb.rt.pnp.PnpCylinders__Composite$GenericCylinderModelType1.connectIV(Ljava/lang/String;Lfb/datatype/ANY;)V: I49 Branch 9 IFLE L428 - false
   * 99 fb.rt.pnp.PnpCylinders__Composite$GenericCylinderModelType1.connectIV(Ljava/lang/String;Lfb/datatype/ANY;)V: I60 Branch 10 IFLE L429 - true
   * 100 fb.rt.pnp.PnpCylinders__Composite$GenericCylinderModelType1.connectIV(Ljava/lang/String;Lfb/datatype/ANY;)V: I60 Branch 10 IFLE L429 - false
   * 101 fb.rt.pnp.PnpCylinders__Composite$GenericCylinderModelType1.connectIV(Ljava/lang/String;Lfb/datatype/ANY;)V: I71 Branch 11 IFLE L430 - true
   * 102 fb.rt.pnp.PnpCylinders__Composite$GenericCylinderModelType1.connectIV(Ljava/lang/String;Lfb/datatype/ANY;)V: I71 Branch 11 IFLE L430 - false
   * 103 fb.rt.pnp.PnpCylinders__Composite$GenericCylinderModelType1.connectIV(Ljava/lang/String;Lfb/datatype/ANY;)V: I82 Branch 12 IFLE L431 - true
   * 104 fb.rt.pnp.PnpCylinders__Composite$GenericCylinderModelType1.connectIV(Ljava/lang/String;Lfb/datatype/ANY;)V: I82 Branch 12 IFLE L431 - false
   * 105 fb.rt.pnp.PnpCylinders__Composite$GenericCylinderModelType1.connectIV(Ljava/lang/String;Lfb/datatype/ANY;)V: I93 Branch 13 IFLE L432 - true
   * 106 fb.rt.pnp.PnpCylinders__Composite$GenericCylinderModelType1.connectIV(Ljava/lang/String;Lfb/datatype/ANY;)V: I93 Branch 13 IFLE L432 - false
   * 107 fb.rt.pnp.PnpCylinders__Composite$GenericCylinderModelType1.connectIV(Ljava/lang/String;Lfb/datatype/ANY;)V: I104 Branch 14 IFLE L433 - true
   * 108 fb.rt.pnp.PnpCylinders__Composite$GenericCylinderModelType1.connectIV(Ljava/lang/String;Lfb/datatype/ANY;)V: I104 Branch 14 IFLE L433 - false
   * 109 fb.rt.pnp.PnpCylinders__Composite$GenericCylinderModelType1.connectIV(Ljava/lang/String;Lfb/datatype/ANY;)V: I115 Branch 15 IFLE L434 - false
   * 110 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType1.state_INIT()V: root-Branch
   * 111 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType1.state_FAILURE()V: root-Branch
   * 112 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType1.alg_FWD()V: root-Branch
   * 113 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType1.connect_Retract(Lfb/datatype/BOOL;)V: root-Branch
   * 114 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType1.alg_INIT()V: root-Branch
   * 115 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType1.alg_STOP()V: root-Branch
   * 116 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType1.<init>(Lfb/rt/pnp/PnpCylinders__Composite;)V: root-Branch
   * 117 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType1.state_STOP()V: root-Branch
   * 118 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType1.connect_Extend(Lfb/datatype/BOOL;)V: root-Branch
   * 119 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType1.state_MOVE_FWD()V: root-Branch
   * 120 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType1.ovNamed(Ljava/lang/String;)Lfb/datatype/ANY;: I5 Branch 32 IFLE L824 - true
   * 121 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType1.ovNamed(Ljava/lang/String;)Lfb/datatype/ANY;: I5 Branch 32 IFLE L824 - false
   * 122 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType1.ovNamed(Ljava/lang/String;)Lfb/datatype/ANY;: I14 Branch 33 IFLE L825 - false
   * 123 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType1.service_CLK()V: I5 Branch 41 IF_ICMPNE L911 - false
   * 124 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType1.service_CLK()V: I12 Branch 42 IFEQ L911 - true
   * 125 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType1.service_CLK()V: I19 Branch 43 IFEQ L911 - true
   * 126 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType1.service_CLK()V: I19 Branch 43 IFEQ L911 - false
   * 127 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType1.service_CLK()V: I37 Branch 44 IF_ICMPNE L915 - false
   * 128 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType1.service_CLK()V: I41 Branch 45 IFEQ L915 - true
   * 129 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType1.service_CLK()V: I50 Branch 46 IFEQ L915 - true
   * 130 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType1.service_CLK()V: I57 Branch 47 IFEQ L915 - false
   * 131 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType1.service_INIT()V: I4 Branch 40 IFNE L903 - false
   * 132 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType1.connectIV(Ljava/lang/String;Lfb/datatype/ANY;)V: I5 Branch 34 IFLE L834 - true
   * 133 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType1.connectIV(Ljava/lang/String;Lfb/datatype/ANY;)V: I5 Branch 34 IFLE L834 - false
   * 134 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType1.connectIV(Ljava/lang/String;Lfb/datatype/ANY;)V: I16 Branch 35 IFLE L835 - false
   * 135 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType1.service_FAULT()V: I5 Branch 89 IF_ICMPNE L979 - true
   * 136 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType1.service_FAULT()V: I5 Branch 89 IF_ICMPNE L979 - false
   * 137 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType1.service_FAULT()V: I23 Branch 90 IF_ICMPNE L983 - false
   * 138 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType1.serviceEvent(Lfb/rt/EventServer;)V: I5 Branch 36 IF_ACMPNE L895 - true
   * 139 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType1.serviceEvent(Lfb/rt/EventServer;)V: I5 Branch 36 IF_ACMPNE L895 - false
   * 140 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType1.serviceEvent(Lfb/rt/EventServer;)V: I14 Branch 37 IF_ACMPNE L896 - true
   * 141 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType1.serviceEvent(Lfb/rt/EventServer;)V: I14 Branch 37 IF_ACMPNE L896 - false
   * 142 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType1.serviceEvent(Lfb/rt/EventServer;)V: I23 Branch 38 IF_ACMPNE L897 - false
   * 143 fb.rt.pnp.PnpCylinders__Composite.event_CYL_IND(ZZZZZ)V: root-Branch
   * 144 fb.rt.pnp.PnpCylinders__Composite.transition_MovementBlockType1_17()V: root-Branch
   * 145 fb.rt.pnp.PnpCylinders__Composite.transition_LinearMotionLoad_1()V: root-Branch
   * 146 fb.rt.pnp.PnpCylinders__Composite.transition_MovementBlockType1_2()V: root-Branch
   * 147 fb.rt.pnp.PnpCylinders__Composite.transition_MovementBlockType2_2()V: root-Branch
   * 148 fb.rt.pnp.PnpCylinders__Composite.transition_MovementBlockType2_11()V: root-Branch
   * 149 fb.rt.pnp.PnpCylinders__Composite.transition_MovementBlockType1_18()V: root-Branch
   * 150 fb.rt.pnp.PnpCylinders__Composite.transition_LinearMotionLoad_0()V: root-Branch
   * 151 fb.rt.pnp.PnpCylinders__Composite.transition_PnPSensor_0()V: root-Branch
   * 152 fb.rt.pnp.PnpCylinders__Composite.transition_MovementBlockType1_0()V: root-Branch
   * 153 fb.rt.pnp.PnpCylinders__Composite.transition_MovementBlockType2_0()V: root-Branch
   * 154 fb.rt.pnp.PnpCylinders__Composite.event_INIT(IIZZIIIIIFIZIIIIZZIIZI)V: root-Branch
   * 155 fb.rt.pnp.PnpCylinders__Composite.transition_MovementBlockType1_1()V: root-Branch
   * 156 fb.rt.pnp.PnpCylinders__Composite.<init>()V: root-Branch
   * 157 fb.rt.pnp.PnpCylinders__Composite.event_FAULT()V: root-Branch
   * 158 fb.rt.pnp.PnpCylinders__Composite$PnpCylinders.<init>(Lfb/rt/pnp/PnpCylinders__Composite;)V: root-Branch
   * 159 fb.rt.pnp.PnpCylinders__Composite$PnPSensor.connect_Position(Lfb/datatype/UINT;)V: root-Branch
   * 160 fb.rt.pnp.PnpCylinders__Composite$PnPSensor.connect_Zone(Lfb/datatype/ARRAY;)V: root-Branch
   * 161 fb.rt.pnp.PnpCylinders__Composite$PnPSensor.state_INIT()V: root-Branch
   * 162 fb.rt.pnp.PnpCylinders__Composite$PnPSensor.<init>(Lfb/rt/pnp/PnpCylinders__Composite;)V: root-Branch
   * 163 fb.rt.pnp.PnpCylinders__Composite$PnPSensor.ovNamed(Ljava/lang/String;)Lfb/datatype/ANY;: I5 Branch 16 IFLE L641 - false
   * 164 fb.rt.pnp.PnpCylinders__Composite$PnPSensor.service_INIT()V: I4 Branch 22 IFNE L705 - false
   * 165 fb.rt.pnp.PnpCylinders__Composite$PnPSensor.alg_INIT()V: I12 Branch 26 IF_ICMPLT L729 - true
   * 166 fb.rt.pnp.PnpCylinders__Composite$PnPSensor.connectIV(Ljava/lang/String;Lfb/datatype/ANY;)V: I5 Branch 17 IFLE L650 - true
   * 167 fb.rt.pnp.PnpCylinders__Composite$PnPSensor.connectIV(Ljava/lang/String;Lfb/datatype/ANY;)V: I5 Branch 17 IFLE L650 - false
   * 168 fb.rt.pnp.PnpCylinders__Composite$PnPSensor.connectIV(Ljava/lang/String;Lfb/datatype/ANY;)V: I16 Branch 18 IFLE L651 - false
   * 169 fb.rt.pnp.PnpCylinders__Composite$PnPSensor.serviceEvent(Lfb/rt/EventServer;)V: I5 Branch 20 IF_ACMPNE L699 - false
   * 170 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType2.alg_STOP()V: root-Branch
   * 171 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType2.<init>(Lfb/rt/pnp/PnpCylinders__Composite;)V: root-Branch
   * 172 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType2.alg_INIT()V: root-Branch
   * 173 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType2.alg_BWD()V: root-Branch
   * 174 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType2.connect_Extend(Lfb/datatype/BOOL;)V: root-Branch
   * 175 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType2.state_FAILURE()V: root-Branch
   * 176 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType2.state_MOVE_BWD()V: root-Branch
   * 177 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType2.state_INIT()V: root-Branch
   * 178 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType2.ovNamed(Ljava/lang/String;)Lfb/datatype/ANY;: I5 Branch 158 IFLE L1740 - true
   * 179 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType2.ovNamed(Ljava/lang/String;)Lfb/datatype/ANY;: I5 Branch 158 IFLE L1740 - false
   * 180 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType2.ovNamed(Ljava/lang/String;)Lfb/datatype/ANY;: I14 Branch 159 IFLE L1741 - false
   * 181 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType2.service_CLK()V: I5 Branch 166 IF_ICMPNE L1819 - false
   * 182 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType2.service_CLK()V: I9 Branch 167 IFEQ L1819 - true
   * 183 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType2.service_CLK()V: I27 Branch 168 IF_ICMPNE L1823 - false
   * 184 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType2.service_CLK()V: I31 Branch 169 IFNE L1823 - false
   * 185 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType2.service_INIT()V: I4 Branch 165 IFNE L1811 - false
   * 186 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType2.connectIV(Ljava/lang/String;Lfb/datatype/ANY;)V: I5 Branch 160 IFLE L1750 - false
   * 187 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType2.service_FAULT()V: I5 Branch 182 IF_ICMPNE L1855 - true
   * 188 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType2.service_FAULT()V: I23 Branch 183 IF_ICMPNE L1859 - true
   * 189 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType2.service_FAULT()V: I41 Branch 184 IF_ICMPNE L1863 - false
   * 190 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType2.serviceEvent(Lfb/rt/EventServer;)V: I5 Branch 161 IF_ACMPNE L1803 - true
   * 191 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType2.serviceEvent(Lfb/rt/EventServer;)V: I5 Branch 161 IF_ACMPNE L1803 - false
   * 192 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType2.serviceEvent(Lfb/rt/EventServer;)V: I14 Branch 162 IF_ACMPNE L1804 - true
   * 193 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType2.serviceEvent(Lfb/rt/EventServer;)V: I14 Branch 162 IF_ACMPNE L1804 - false
   * 194 fb.rt.pnp.PnpCylinders__Composite$MovementBlockType2.serviceEvent(Lfb/rt/EventServer;)V: I23 Branch 163 IF_ACMPNE L1805 - false
   */

  @Test
  public void test16()  throws Throwable  {
      PnpCylinders__Composite pnpCylinders__Composite0 = new PnpCylinders__Composite();
      pnpCylinders__Composite0.event_INIT(1016, 1016, false, false, 1016, 1016, 1016, 1016, 1016, (float) 1016, 1016, false, 1016, 1016, 1016, 1016, false, false, 1016, 1016, false, 1016);
      pnpCylinders__Composite0.event_CYL_IND(false, false, true, false, false);
      pnpCylinders__Composite0.event_FAULT();
  }
}
