/*
 * This file was automatically generated by EvoSuite
 * Wed Jan 07 15:46:36 MSK 2015
 */

package fb.rt.pnp;

import static org.junit.Assert.*;
import org.junit.Test;
import fb.rt.pnp.PnPSensor__Basic;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.EvoSuiteFile;
import org.junit.runner.RunWith;


public class PnPSensor__Basic_Tr_ESTest {

  //Test case number: 0
  /*
   * 1 covered goal:
   * 1 fb.rt.pnp.PnPSensor__Basic.transition_PnPSensor_3()V: root-Branch
   */

  @Test
  public void test0()  throws Throwable  {
      PnPSensor__Basic pnPSensor__Basic0 = new PnPSensor__Basic();
      pnPSensor__Basic0.event_INIT(419, 419, 419);
      pnPSensor__Basic0.event_CLK((-1));
      pnPSensor__Basic0.event_CLK(419);
  }

  //Test case number: 1
  /*
   * 3 covered goals:
   * 1 fb.rt.pnp.PnPSensor__Basic.transition_PnPSensor_2()V: root-Branch
   * 2 fb.rt.pnp.PnPSensor__Basic.transition_PnPSensor_1()V: root-Branch
   * 3 fb.rt.pnp.PnPSensor__Basic.transition_PnPSensor_0()V: root-Branch
   */

  @Test
  public void test1()  throws Throwable  {
      PnPSensor__Basic pnPSensor__Basic0 = new PnPSensor__Basic();
      pnPSensor__Basic0.event_INIT(419, 419, 419);
      pnPSensor__Basic0.event_CLK(419);
      pnPSensor__Basic0.event_CLK((-1));
  }
}
