/*
 * This file was automatically generated by EvoSuite
 * Wed Jan 07 01:58:25 MSK 2015
 */

package fb.rt.pnp;

import static org.junit.Assert.*;
import org.junit.Test;
import fb.rt.pnp.PnPVacuum__Basic;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.EvoSuiteFile;
import org.junit.runner.RunWith;


public class PnPVacuum__Basic_ESTest {

  //Test case number: 0
  /*
   * 1 covered goal:
   * 1 fb.rt.pnp.PnPVacuum__Basic$PnPVacuum.alg_INIT()V: I20 Branch 13 IFEQ L144 - false
   */

  @Test
  public void test0()  throws Throwable  {
      PnPVacuum__Basic pnPVacuum__Basic0 = new PnPVacuum__Basic();
      pnPVacuum__Basic0.event_INIT(false, true);
  }

  //Test case number: 1
  /*
   * 3 covered goals:
   * 1 fb.rt.pnp.PnPVacuum__Basic$PnPVacuum.service_CLK()V: I75 Branch 11 IFEQ L132 - true
   * 2 fb.rt.pnp.PnPVacuum__Basic$PnPVacuum.alg_INIT()V: I5 Branch 12 IFEQ L141 - true
   * 3 fb.rt.pnp.PnPVacuum__Basic$PnPVacuum.alg_INIT()V: I20 Branch 13 IFEQ L144 - true
   */

  @Test
  public void test1()  throws Throwable  {
      PnPVacuum__Basic pnPVacuum__Basic0 = new PnPVacuum__Basic();
      pnPVacuum__Basic0.event_INIT(false, false);
      pnPVacuum__Basic0.event_CLK(false, false);
  }

  //Test case number: 2
  /*
   * 3 covered goals:
   * 1 fb.rt.pnp.PnPVacuum__Basic.transition_PnPVacuum_2()V: root-Branch
   * 2 fb.rt.pnp.PnPVacuum__Basic$PnPVacuum.service_CLK()V: I31 Branch 7 IFEQ L124 - false
   * 3 fb.rt.pnp.PnPVacuum__Basic$PnPVacuum.service_CLK()V: I53 Branch 9 IFEQ L128 - true
   */

  @Test
  public void test2()  throws Throwable  {
      PnPVacuum__Basic pnPVacuum__Basic0 = new PnPVacuum__Basic();
      pnPVacuum__Basic0.event_INIT(true, true);
      pnPVacuum__Basic0.event_CLK(true, true);
      pnPVacuum__Basic0.event_CLK(true, true);
      pnPVacuum__Basic0.event_CLK(true, false);
  }

  //Test case number: 3
  /*
   * 5 covered goals:
   * 1 fb.rt.pnp.PnPVacuum__Basic.transition_PnPVacuum_1()V: root-Branch
   * 2 fb.rt.pnp.PnPVacuum__Basic$PnPVacuum.service_CLK()V: I9 Branch 5 IFEQ L120 - false
   * 3 fb.rt.pnp.PnPVacuum__Basic$PnPVacuum.service_CLK()V: I27 Branch 6 IF_ICMPNE L124 - false
   * 4 fb.rt.pnp.PnPVacuum__Basic$PnPVacuum.service_CLK()V: I31 Branch 7 IFEQ L124 - true
   * 5 fb.rt.pnp.PnPVacuum__Basic$PnPVacuum.service_CLK()V: I71 Branch 10 IF_ICMPNE L132 - true
   */

  @Test
  public void test3()  throws Throwable  {
      PnPVacuum__Basic pnPVacuum__Basic0 = new PnPVacuum__Basic();
      pnPVacuum__Basic0.event_INIT(true, true);
      pnPVacuum__Basic0.event_CLK(false, true);
      pnPVacuum__Basic0.event_CLK(false, false);
  }

  //Test case number: 4
  /*
   * 1 covered goal:
   * 1 fb.rt.pnp.PnPVacuum__Basic$PnPVacuum.service_INIT()V: I4 Branch 3 IFNE L112 - true
   */

  @Test
  public void test4()  throws Throwable  {
      PnPVacuum__Basic pnPVacuum__Basic0 = new PnPVacuum__Basic();
      pnPVacuum__Basic0.event_INIT(true, true);
      pnPVacuum__Basic0.event_INIT(true, true);
  }

  //Test case number: 5
  /*
   * 26 covered goals:
   * 1 fb.rt.pnp.PnPVacuum__Basic.transition_PnPVacuum_4()V: root-Branch
   * 2 fb.rt.pnp.PnPVacuum__Basic.transition_PnPVacuum_3()V: root-Branch
   * 3 fb.rt.pnp.PnPVacuum__Basic.event_CLK(ZZ)V: root-Branch
   * 4 fb.rt.pnp.PnPVacuum__Basic.transition_PnPVacuum_0()V: root-Branch
   * 5 fb.rt.pnp.PnPVacuum__Basic.event_INIT(ZZ)V: root-Branch
   * 6 fb.rt.pnp.PnPVacuum__Basic.<init>()V: root-Branch
   * 7 fb.rt.pnp.PnPVacuum__Basic$PnPVacuum.state_ON()V: root-Branch
   * 8 fb.rt.pnp.PnPVacuum__Basic$PnPVacuum.alg_SWITCH_OFF()V: root-Branch
   * 9 fb.rt.pnp.PnPVacuum__Basic$PnPVacuum.state_INIT()V: root-Branch
   * 10 fb.rt.pnp.PnPVacuum__Basic$PnPVacuum.state_OFF()V: root-Branch
   * 11 fb.rt.pnp.PnPVacuum__Basic$PnPVacuum.<init>(Lfb/rt/pnp/PnPVacuum__Basic;)V: root-Branch
   * 12 fb.rt.pnp.PnPVacuum__Basic$PnPVacuum.alg_SWITCH_ON()V: root-Branch
   * 13 fb.rt.pnp.PnPVacuum__Basic$PnPVacuum.service_CLK()V: I5 Branch 4 IF_ICMPNE L120 - true
   * 14 fb.rt.pnp.PnPVacuum__Basic$PnPVacuum.service_CLK()V: I5 Branch 4 IF_ICMPNE L120 - false
   * 15 fb.rt.pnp.PnPVacuum__Basic$PnPVacuum.service_CLK()V: I9 Branch 5 IFEQ L120 - true
   * 16 fb.rt.pnp.PnPVacuum__Basic$PnPVacuum.service_CLK()V: I27 Branch 6 IF_ICMPNE L124 - true
   * 17 fb.rt.pnp.PnPVacuum__Basic$PnPVacuum.service_CLK()V: I49 Branch 8 IF_ICMPNE L128 - true
   * 18 fb.rt.pnp.PnPVacuum__Basic$PnPVacuum.service_CLK()V: I49 Branch 8 IF_ICMPNE L128 - false
   * 19 fb.rt.pnp.PnPVacuum__Basic$PnPVacuum.service_CLK()V: I53 Branch 9 IFEQ L128 - false
   * 20 fb.rt.pnp.PnPVacuum__Basic$PnPVacuum.service_CLK()V: I71 Branch 10 IF_ICMPNE L132 - false
   * 21 fb.rt.pnp.PnPVacuum__Basic$PnPVacuum.service_CLK()V: I75 Branch 11 IFEQ L132 - false
   * 22 fb.rt.pnp.PnPVacuum__Basic$PnPVacuum.service_INIT()V: I4 Branch 3 IFNE L112 - false
   * 23 fb.rt.pnp.PnPVacuum__Basic$PnPVacuum.alg_INIT()V: I5 Branch 12 IFEQ L141 - false
   * 24 fb.rt.pnp.PnPVacuum__Basic$PnPVacuum.serviceEvent(Lfb/rt/EventServer;)V: I5 Branch 1 IF_ACMPNE L106 - true
   * 25 fb.rt.pnp.PnPVacuum__Basic$PnPVacuum.serviceEvent(Lfb/rt/EventServer;)V: I5 Branch 1 IF_ACMPNE L106 - false
   * 26 fb.rt.pnp.PnPVacuum__Basic$PnPVacuum.serviceEvent(Lfb/rt/EventServer;)V: I14 Branch 2 IF_ACMPNE L107 - false
   */

  @Test
  public void test5()  throws Throwable  {
      PnPVacuum__Basic pnPVacuum__Basic0 = new PnPVacuum__Basic();
      pnPVacuum__Basic0.event_INIT(true, true);
      pnPVacuum__Basic0.event_CLK(true, false);
      pnPVacuum__Basic0.event_CLK(true, true);
  }
}
