/*
 * This file was automatically generated by EvoSuite
 * Wed Jan 07 16:06:50 MSK 2015
 */

package fb.rt.pnp;

import static org.junit.Assert.*;
import org.junit.Test;
import fb.rt.pnp.PnpXYCalculatorBA__Basic;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.EvoSuiteFile;
import org.junit.runner.RunWith;


public class PnpXYCalculatorBA__Basic_Tr_ESTest {

  //Test case number: 0
  /*
   * 2 covered goals:
   * 1 fb.rt.pnp.PnpXYCalculatorBA__Basic.transition_PnpXYCalculatorBA_4()V: root-Branch
   * 2 fb.rt.pnp.PnpXYCalculatorBA__Basic.transition_PnpXYCalculatorBA_11()V: root-Branch
   */

  @Test
  public void test0()  throws Throwable  {
      PnpXYCalculatorBA__Basic pnpXYCalculatorBA__Basic0 = new PnpXYCalculatorBA__Basic();
      pnpXYCalculatorBA__Basic0.event_REMOVE_WP();
  }

  //Test case number: 1
  /*
   * 2 covered goals:
   * 1 fb.rt.pnp.PnpXYCalculatorBA__Basic.transition_PnpXYCalculatorBA_9()V: root-Branch
   * 2 fb.rt.pnp.PnpXYCalculatorBA__Basic.transition_PnpXYCalculatorBA_3()V: root-Branch
   */

  @Test
  public void test1()  throws Throwable  {
      PnpXYCalculatorBA__Basic pnpXYCalculatorBA__Basic0 = new PnpXYCalculatorBA__Basic();
      pnpXYCalculatorBA__Basic0.event_ADD_WP(96, 96);
  }

  //Test case number: 2
  /*
   * 2 covered goals:
   * 1 fb.rt.pnp.PnpXYCalculatorBA__Basic.transition_PnpXYCalculatorBA_8()V: root-Branch
   * 2 fb.rt.pnp.PnpXYCalculatorBA__Basic.transition_PnpXYCalculatorBA_1()V: root-Branch
   */

  @Test
  public void test2()  throws Throwable  {
      PnpXYCalculatorBA__Basic pnpXYCalculatorBA__Basic0 = new PnpXYCalculatorBA__Basic();
      pnpXYCalculatorBA__Basic0.event_REQ(true, true, true, true, true, true);
  }

  //Test case number: 3
  /*
   * 2 covered goals:
   * 1 fb.rt.pnp.PnpXYCalculatorBA__Basic.transition_PnpXYCalculatorBA_7()V: root-Branch
   * 2 fb.rt.pnp.PnpXYCalculatorBA__Basic.transition_PnpXYCalculatorBA_2()V: root-Branch
   */

  @Test
  public void test3()  throws Throwable  {
      PnpXYCalculatorBA__Basic pnpXYCalculatorBA__Basic0 = new PnpXYCalculatorBA__Basic();
      pnpXYCalculatorBA__Basic0.event_CLK(false, 96, (-4), 73, 73, 96, 6);
  }

  //Test case number: 4
  /*
   * 2 covered goals:
   * 1 fb.rt.pnp.PnpXYCalculatorBA__Basic.transition_PnpXYCalculatorBA_5()V: root-Branch
   * 2 fb.rt.pnp.PnpXYCalculatorBA__Basic.transition_PnpXYCalculatorBA_10()V: root-Branch
   */

  @Test
  public void test4()  throws Throwable  {
      PnpXYCalculatorBA__Basic pnpXYCalculatorBA__Basic0 = new PnpXYCalculatorBA__Basic();
      pnpXYCalculatorBA__Basic0.event_ADD_WP00();
  }

  //Test case number: 5
  /*
   * 2 covered goals:
   * 1 fb.rt.pnp.PnpXYCalculatorBA__Basic.transition_PnpXYCalculatorBA_6()V: root-Branch
   * 2 fb.rt.pnp.PnpXYCalculatorBA__Basic.transition_PnpXYCalculatorBA_0()V: root-Branch
   */

  @Test
  public void test5()  throws Throwable  {
      PnpXYCalculatorBA__Basic pnpXYCalculatorBA__Basic0 = new PnpXYCalculatorBA__Basic();
      pnpXYCalculatorBA__Basic0.event_INIT(73, 73);
  }
}
