/*
 * This file was automatically generated by EvoSuite
 * Wed Jan 07 02:38:56 MSK 2015
 */

package fb.rt.pnp;

import static org.junit.Assert.*;
import org.junit.Test;
import fb.rt.pnp.SFC1__Basic;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.EvoSuiteFile;
import org.junit.runner.RunWith;


public class SFC1__Basic_ESTest {

  //Test case number: 0
  /*
   * 1 covered goal:
   * 1 fb.rt.pnp.SFC1__Basic$SFC1.service_REQ()V: I146 Branch 18 IFNE L163 - true
   */

  @Test
  public void test0()  throws Throwable  {
      SFC1__Basic sFC1__Basic0 = new SFC1__Basic();
      sFC1__Basic0.event_REQ(false, false, true);
      sFC1__Basic0.event_REQ(true, false, true);
  }

  //Test case number: 1
  /*
   * 1 covered goal:
   * 1 fb.rt.pnp.SFC1__Basic$SFC1.service_REQ()V: I124 Branch 16 IFNE L159 - true
   */

  @Test
  public void test1()  throws Throwable  {
      SFC1__Basic sFC1__Basic0 = new SFC1__Basic();
      sFC1__Basic0.event_REQ(false, true, false);
      sFC1__Basic0.event_REQ(true, true, false);
  }

  //Test case number: 2
  /*
   * 1 covered goal:
   * 1 fb.rt.pnp.SFC1__Basic$SFC1.service_REQ()V: I102 Branch 14 IFNE L155 - true
   */

  @Test
  public void test2()  throws Throwable  {
      SFC1__Basic sFC1__Basic0 = new SFC1__Basic();
      sFC1__Basic0.event_REQ(true, true, true);
      sFC1__Basic0.event_REQ(true, true, true);
  }

  //Test case number: 3
  /*
   * 2 covered goals:
   * 1 fb.rt.pnp.SFC1__Basic$SFC1.service_REQ()V: I80 Branch 12 IFEQ L151 - true
   * 2 fb.rt.pnp.SFC1__Basic$SFC1.service_REQ()V: I142 Branch 17 IF_ICMPNE L163 - true
   */

  @Test
  public void test3()  throws Throwable  {
      SFC1__Basic sFC1__Basic0 = new SFC1__Basic();
      sFC1__Basic0.event_REQ(false, false, false);
  }

  //Test case number: 4
  /*
   * 1 covered goal:
   * 1 fb.rt.pnp.SFC1__Basic$SFC1.service_INIT()V: I4 Branch 3 IFNE L135 - true
   */

  @Test
  public void test4()  throws Throwable  {
      SFC1__Basic sFC1__Basic0 = new SFC1__Basic();
      sFC1__Basic0.event_REQ(false, true, false);
      sFC1__Basic0.event_INIT(true, false, true);
  }

  //Test case number: 5
  /*
   * 13 covered goals:
   * 1 fb.rt.pnp.SFC1__Basic$SFC1.state_X3()V: root-Branch
   * 2 fb.rt.pnp.SFC1__Basic$SFC1.alg_X3()V: root-Branch
   * 3 fb.rt.pnp.SFC1__Basic$SFC1.service_REQ()V: I39 Branch 8 IFEQ L147 - true
   * 4 fb.rt.pnp.SFC1__Basic$SFC1.service_REQ()V: I56 Branch 9 IFNE L151 - false
   * 5 fb.rt.pnp.SFC1__Basic$SFC1.service_REQ()V: I63 Branch 10 IFEQ L151 - true
   * 6 fb.rt.pnp.SFC1__Basic$SFC1.service_REQ()V: I73 Branch 11 IFEQ L151 - true
   * 7 fb.rt.pnp.SFC1__Basic$SFC1.service_REQ()V: I80 Branch 12 IFEQ L151 - false
   * 8 fb.rt.pnp.SFC1__Basic$SFC1.service_REQ()V: I120 Branch 15 IF_ICMPNE L159 - true
   * 9 fb.rt.pnp.SFC1__Basic$SFC1.service_REQ()V: I142 Branch 17 IF_ICMPNE L163 - false
   * 10 fb.rt.pnp.SFC1__Basic$SFC1.service_REQ()V: I146 Branch 18 IFNE L163 - false
   * 11 fb.rt.pnp.SFC1__Basic$SFC1.alg_X4()V: I11 Branch 19 IFNE L185 - true
   * 12 fb.rt.pnp.SFC1__Basic.transition_SFC1_7()V: root-Branch
   * 13 fb.rt.pnp.SFC1__Basic.transition_SFC1_4()V: root-Branch
   */

  @Test
  public void test5()  throws Throwable  {
      SFC1__Basic sFC1__Basic0 = new SFC1__Basic();
      sFC1__Basic0.event_REQ(false, false, true);
      sFC1__Basic0.event_REQ(true, true, false);
  }

  //Test case number: 6
  /*
   * 7 covered goals:
   * 1 fb.rt.pnp.SFC1__Basic$SFC1.alg_X1()V: root-Branch
   * 2 fb.rt.pnp.SFC1__Basic$SFC1.state_X1()V: root-Branch
   * 3 fb.rt.pnp.SFC1__Basic$SFC1.service_REQ()V: I8 Branch 5 IFEQ L143 - false
   * 4 fb.rt.pnp.SFC1__Basic$SFC1.service_REQ()V: I98 Branch 13 IF_ICMPNE L155 - false
   * 5 fb.rt.pnp.SFC1__Basic$SFC1.service_REQ()V: I102 Branch 14 IFNE L155 - false
   * 6 fb.rt.pnp.SFC1__Basic.transition_SFC1_5()V: root-Branch
   * 7 fb.rt.pnp.SFC1__Basic.transition_SFC1_2()V: root-Branch
   */

  @Test
  public void test6()  throws Throwable  {
      SFC1__Basic sFC1__Basic0 = new SFC1__Basic();
      sFC1__Basic0.event_REQ(true, true, true);
      sFC1__Basic0.event_REQ(false, false, false);
  }

  //Test case number: 7
  /*
   * 9 covered goals:
   * 1 fb.rt.pnp.SFC1__Basic$SFC1.alg_INIT()V: root-Branch
   * 2 fb.rt.pnp.SFC1__Basic$SFC1.state_INIT()V: root-Branch
   * 3 fb.rt.pnp.SFC1__Basic$SFC1.service_INIT()V: I4 Branch 3 IFNE L135 - false
   * 4 fb.rt.pnp.SFC1__Basic$SFC1.alg_X4()V: I23 Branch 20 IFNE L188 - true
   * 5 fb.rt.pnp.SFC1__Basic$SFC1.alg_X4()V: I35 Branch 21 IFNE L191 - true
   * 6 fb.rt.pnp.SFC1__Basic$SFC1.serviceEvent(Lfb/rt/EventServer;)V: I5 Branch 1 IF_ACMPNE L129 - false
   * 7 fb.rt.pnp.SFC1__Basic.transition_SFC1_1()V: root-Branch
   * 8 fb.rt.pnp.SFC1__Basic.event_INIT(ZZZ)V: root-Branch
   * 9 fb.rt.pnp.SFC1__Basic.transition_SFC1_0()V: root-Branch
   */

  @Test
  public void test7()  throws Throwable  {
      SFC1__Basic sFC1__Basic0 = new SFC1__Basic();
      sFC1__Basic0.event_INIT(false, true, true);
  }

  //Test case number: 8
  /*
   * 24 covered goals:
   * 1 fb.rt.pnp.SFC1__Basic$SFC1.alg_X2()V: root-Branch
   * 2 fb.rt.pnp.SFC1__Basic$SFC1.state_X4()V: root-Branch
   * 3 fb.rt.pnp.SFC1__Basic$SFC1.<init>(Lfb/rt/pnp/SFC1__Basic;)V: root-Branch
   * 4 fb.rt.pnp.SFC1__Basic$SFC1.state_X2()V: root-Branch
   * 5 fb.rt.pnp.SFC1__Basic$SFC1.service_REQ()V: I4 Branch 4 IFNE L143 - true
   * 6 fb.rt.pnp.SFC1__Basic$SFC1.service_REQ()V: I4 Branch 4 IFNE L143 - false
   * 7 fb.rt.pnp.SFC1__Basic$SFC1.service_REQ()V: I8 Branch 5 IFEQ L143 - true
   * 8 fb.rt.pnp.SFC1__Basic$SFC1.service_REQ()V: I25 Branch 6 IFNE L147 - true
   * 9 fb.rt.pnp.SFC1__Basic$SFC1.service_REQ()V: I25 Branch 6 IFNE L147 - false
   * 10 fb.rt.pnp.SFC1__Basic$SFC1.service_REQ()V: I32 Branch 7 IFEQ L147 - true
   * 11 fb.rt.pnp.SFC1__Basic$SFC1.service_REQ()V: I39 Branch 8 IFEQ L147 - false
   * 12 fb.rt.pnp.SFC1__Basic$SFC1.service_REQ()V: I56 Branch 9 IFNE L151 - true
   * 13 fb.rt.pnp.SFC1__Basic$SFC1.service_REQ()V: I98 Branch 13 IF_ICMPNE L155 - true
   * 14 fb.rt.pnp.SFC1__Basic$SFC1.service_REQ()V: I120 Branch 15 IF_ICMPNE L159 - false
   * 15 fb.rt.pnp.SFC1__Basic$SFC1.service_REQ()V: I124 Branch 16 IFNE L159 - false
   * 16 fb.rt.pnp.SFC1__Basic$SFC1.alg_X4()V: I11 Branch 19 IFNE L185 - false
   * 17 fb.rt.pnp.SFC1__Basic$SFC1.alg_X4()V: I23 Branch 20 IFNE L188 - false
   * 18 fb.rt.pnp.SFC1__Basic$SFC1.alg_X4()V: I35 Branch 21 IFNE L191 - false
   * 19 fb.rt.pnp.SFC1__Basic$SFC1.serviceEvent(Lfb/rt/EventServer;)V: I5 Branch 1 IF_ACMPNE L129 - true
   * 20 fb.rt.pnp.SFC1__Basic$SFC1.serviceEvent(Lfb/rt/EventServer;)V: I14 Branch 2 IF_ACMPNE L130 - false
   * 21 fb.rt.pnp.SFC1__Basic.event_REQ(ZZZ)V: root-Branch
   * 22 fb.rt.pnp.SFC1__Basic.transition_SFC1_6()V: root-Branch
   * 23 fb.rt.pnp.SFC1__Basic.transition_SFC1_3()V: root-Branch
   * 24 fb.rt.pnp.SFC1__Basic.<init>()V: root-Branch
   */

  @Test
  public void test8()  throws Throwable  {
      SFC1__Basic sFC1__Basic0 = new SFC1__Basic();
      sFC1__Basic0.event_REQ(false, true, false);
      sFC1__Basic0.event_REQ(false, false, false);
  }
}
