/*
 * This file was automatically generated by EvoSuite
 * Wed Jan 07 16:37:11 MSK 2015
 */

package fb.rt.pnp;

import static org.junit.Assert.*;
import org.junit.Test;
import fb.rt.pnp.SFC1__Basic;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.EvoSuiteFile;
import org.junit.runner.RunWith;


public class SFC1__Basic_Tr_ESTest {

  //Test case number: 0
  /*
   * 2 covered goals:
   * 1 fb.rt.pnp.SFC1__Basic.transition_SFC1_6()V: root-Branch
   * 2 fb.rt.pnp.SFC1__Basic.transition_SFC1_3()V: root-Branch
   */

  @Test
  public void test0()  throws Throwable  {
      SFC1__Basic sFC1__Basic0 = new SFC1__Basic();
      sFC1__Basic0.event_REQ(false, true, false);
      sFC1__Basic0.event_REQ(true, false, false);
  }

  //Test case number: 1
  /*
   * 2 covered goals:
   * 1 fb.rt.pnp.SFC1__Basic.transition_SFC1_1()V: root-Branch
   * 2 fb.rt.pnp.SFC1__Basic.transition_SFC1_0()V: root-Branch
   */

  @Test
  public void test1()  throws Throwable  {
      SFC1__Basic sFC1__Basic0 = new SFC1__Basic();
      sFC1__Basic0.event_INIT(false, false, true);
  }

  //Test case number: 2
  /*
   * 4 covered goals:
   * 1 fb.rt.pnp.SFC1__Basic.transition_SFC1_5()V: root-Branch
   * 2 fb.rt.pnp.SFC1__Basic.transition_SFC1_2()V: root-Branch
   * 3 fb.rt.pnp.SFC1__Basic.transition_SFC1_7()V: root-Branch
   * 4 fb.rt.pnp.SFC1__Basic.transition_SFC1_4()V: root-Branch
   */

  @Test
  public void test2()  throws Throwable  {
      SFC1__Basic sFC1__Basic0 = new SFC1__Basic();
      sFC1__Basic0.event_REQ(true, true, true);
      sFC1__Basic0.event_REQ(false, true, true);
      sFC1__Basic0.event_REQ(false, false, true);
      sFC1__Basic0.event_REQ(true, true, false);
  }
}
