/*
 * This file was automatically generated by EvoSuite
 * Wed Jan 07 16:57:24 MSK 2015
 */

package fb.rt.pnp;

import static org.junit.Assert.*;
import org.junit.Test;
import fb.rt.pnp.SFC4__Basic;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.EvoSuiteFile;
import org.junit.runner.RunWith;


public class SFC4__Basic_Tr_ESTest {

  //Test case number: 0
  /*
   * 7 covered goals:
   * 1 fb.rt.pnp.SFC4__Basic.transition_SFC4_6()V: root-Branch
   * 2 fb.rt.pnp.SFC4__Basic.transition_SFC4_5()V: root-Branch
   * 3 fb.rt.pnp.SFC4__Basic.transition_SFC4_7()V: root-Branch
   * 4 fb.rt.pnp.SFC4__Basic.transition_SFC4_8()V: root-Branch
   * 5 fb.rt.pnp.SFC4__Basic.transition_SFC4_3()V: root-Branch
   * 6 fb.rt.pnp.SFC4__Basic.transition_SFC4_4()V: root-Branch
   * 7 fb.rt.pnp.SFC4__Basic.transition_SFC4_9()V: root-Branch
   */

  @Test
  public void test0()  throws Throwable  {
      SFC4__Basic sFC4__Basic0 = new SFC4__Basic();
      sFC4__Basic0.event_INIT(false, true, true, false, true, true, true, true, true, true, true, true, true);
      sFC4__Basic0.event_REQ(true, true, true, true, true, true, true, true, true, true, false, true, false);
      sFC4__Basic0.event_REQ(true, true, true, true, true, true, true, true, false, false, false, true, true);
      sFC4__Basic0.event_REQ(true, true, true, true, true, true, true, true, true, true, true, true, true);
      sFC4__Basic0.event_REQ(true, false, true, false, false, false, false, false, false, false, false, true, true);
      sFC4__Basic0.event_REQ(true, false, true, true, false, true, true, false, false, false, true, true, true);
      sFC4__Basic0.event_REQ(false, false, false, true, false, false, false, false, false, false, false, false, false);
      sFC4__Basic0.event_REQ(true, true, true, true, true, true, false, false, true, true, true, true, false);
  }

  //Test case number: 1
  /*
   * 4 covered goals:
   * 1 fb.rt.pnp.SFC4__Basic.transition_SFC4_2()V: root-Branch
   * 2 fb.rt.pnp.SFC4__Basic.transition_SFC4_1()V: root-Branch
   * 3 fb.rt.pnp.SFC4__Basic.transition_SFC4_10()V: root-Branch
   * 4 fb.rt.pnp.SFC4__Basic.transition_SFC4_0()V: root-Branch
   */

  @Test
  public void test1()  throws Throwable  {
      SFC4__Basic sFC4__Basic0 = new SFC4__Basic();
      sFC4__Basic0.event_INIT(false, false, false, false, false, false, false, false, false, false, false, false, false);
      sFC4__Basic0.event_REQ(false, false, false, false, false, false, false, false, false, false, false, false, false);
  }
}
