/*
 * This file was automatically generated by EvoSuite
 * Wed Jan 07 03:09:19 MSK 2015
 */

package fb.rt.pnp;

import static org.junit.Assert.*;
import org.junit.Test;
import fb.rt.pnp.SFC_COORD__Basic;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.EvoSuiteFile;
import org.junit.runner.RunWith;


public class SFC_COORD__Basic_ESTest {

  //Test case number: 0
  /*
   * 1 covered goal:
   * 1 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I1162 Branch 80 IF_ACMPNE L731 - true
   */

  @Test
  public void test0()  throws Throwable  {
      SFC_COORD__Basic sFC_COORD__Basic0 = new SFC_COORD__Basic();
      sFC_COORD__Basic0.event_REQ(false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false);
  }

  //Test case number: 1
  /*
   * 4 covered goals:
   * 1 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I811 Branch 58 IF_ACMPNE L634 - false
   * 2 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I833 Branch 59 IF_ACMPNE L640 - false
   * 3 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I880 Branch 62 IF_ACMPNE L653 - false
   * 4 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I1409 Branch 95 IF_ACMPNE L796 - false
   */

  @Test
  public void test1()  throws Throwable  {
      SFC_COORD__Basic sFC_COORD__Basic0 = new SFC_COORD__Basic();
      sFC_COORD__Basic0.event_INIT(true, true, true, true, true, true, true, true, false, false, true, false, false, true, true, false, false, true, true, true, false, false, true, false, true, false, true, true, true);
      sFC_COORD__Basic0.event_REQ(true, true, true, true, true, false, false, true, true, true, true, true, true, true, true, true, true, true, false, true, true, false, true, true, true, true, true, true, true);
      sFC_COORD__Basic0.event_REQ(true, true, true, true, true, true, true, true, true, true, true, true, false, true, false, true, true, true, true, false, true, true, true, false, false, true, false, false, true);
  }

  //Test case number: 2
  /*
   * 9 covered goals:
   * 1 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I388 Branch 31 IF_ACMPNE L517 - true
   * 2 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I717 Branch 52 IF_ACMPNE L608 - true
   * 3 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I804 Branch 57 IFEQ L633 - false
   * 4 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I811 Branch 58 IF_ACMPNE L634 - true
   * 5 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I905 Branch 64 IF_ACMPNE L660 - true
   * 6 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I952 Branch 67 IF_ACMPNE L673 - true
   * 7 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I1336 Branch 91 IF_ACMPNE L777 - true
   * 8 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I1387 Branch 94 IF_ACMPNE L790 - true
   * 9 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I1438 Branch 97 IF_ACMPNE L803 - true
   */

  @Test
  public void test2()  throws Throwable  {
      SFC_COORD__Basic sFC_COORD__Basic0 = new SFC_COORD__Basic();
      sFC_COORD__Basic0.event_REQ(true, true, true, true, true, false, false, true, true, true, true, true, true, true, true, true, true, true, false, true, true, false, true, true, true, true, true, true, true);
  }

  //Test case number: 3
  /*
   * 23 covered goals:
   * 1 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I363 Branch 29 IF_ACMPNE L510 - false
   * 2 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I381 Branch 30 IFEQ L516 - false
   * 3 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I388 Branch 31 IF_ACMPNE L517 - false
   * 4 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I410 Branch 32 IF_ACMPNE L523 - false
   * 5 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I457 Branch 35 IF_ACMPNE L536 - false
   * 6 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I504 Branch 38 IF_ACMPNE L549 - false
   * 7 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I710 Branch 51 IFEQ L607 - false
   * 8 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I717 Branch 52 IF_ACMPNE L608 - false
   * 9 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I739 Branch 53 IF_ACMPNE L614 - false
   * 10 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I898 Branch 63 IFEQ L659 - false
   * 11 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I905 Branch 64 IF_ACMPNE L660 - false
   * 12 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I927 Branch 65 IF_ACMPNE L666 - false
   * 13 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I945 Branch 66 IFEQ L672 - false
   * 14 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I952 Branch 67 IF_ACMPNE L673 - false
   * 15 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I974 Branch 68 IF_ACMPNE L679 - false
   * 16 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I1329 Branch 90 IFEQ L776 - false
   * 17 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I1336 Branch 91 IF_ACMPNE L777 - false
   * 18 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I1358 Branch 92 IF_ACMPNE L783 - false
   * 19 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I1380 Branch 93 IFEQ L789 - false
   * 20 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I1387 Branch 94 IF_ACMPNE L790 - false
   * 21 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I1431 Branch 96 IFEQ L802 - false
   * 22 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I1438 Branch 97 IF_ACMPNE L803 - false
   * 23 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I1460 Branch 98 IF_ACMPNE L809 - false
   */

  @Test
  public void test3()  throws Throwable  {
      SFC_COORD__Basic sFC_COORD__Basic0 = new SFC_COORD__Basic();
      sFC_COORD__Basic0.event_INIT(true, true, true, true, true, false, true, false, true, true, true, false, true, false, false, true, true, true, true, true, false, true, false, false, false, true, true, true, false);
      sFC_COORD__Basic0.event_REQ(false, true, false, false, true, true, true, true, false, true, true, true, true, true, true, true, true, true, false, true, true, false, true, true, true, true, false, true, true);
      sFC_COORD__Basic0.event_REQ(true, true, true, false, false, false, false, false, true, true, false, true, false, false, false, true, true, true, false, false, false, false, false, true, false, false, false, true, false);
  }

  //Test case number: 4
  /*
   * 25 covered goals:
   * 1 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I106 Branch 13 IF_ACMPNE L439 - false
   * 2 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I128 Branch 14 IF_ACMPNE L445 - false
   * 3 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I153 Branch 16 IF_ACMPNE L452 - false
   * 4 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I175 Branch 17 IF_ACMPNE L458 - false
   * 5 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I222 Branch 20 IF_ACMPNE L471 - false
   * 6 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I247 Branch 22 IF_ACMPNE L478 - false
   * 7 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I269 Branch 23 IF_ACMPNE L484 - false
   * 8 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I598 Branch 44 IF_ACMPNE L575 - false
   * 9 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I623 Branch 46 IF_ACMPNE L582 - false
   * 10 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I645 Branch 47 IF_ACMPNE L588 - false
   * 11 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I670 Branch 49 IF_ACMPNE L595 - false
   * 12 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I692 Branch 50 IF_ACMPNE L601 - false
   * 13 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I786 Branch 56 IF_ACMPNE L627 - false
   * 14 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I999 Branch 70 IF_ACMPNE L686 - false
   * 15 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I1021 Branch 71 IF_ACMPNE L692 - false
   * 16 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I1115 Branch 77 IF_ACMPNE L718 - false
   * 17 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I1133 Branch 78 IFEQ L724 - true
   * 18 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I1162 Branch 80 IF_ACMPNE L731 - false
   * 19 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I1187 Branch 82 IF_ACMPNE L738 - false
   * 20 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I1209 Branch 83 IF_ACMPNE L744 - false
   * 21 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I1234 Branch 85 IF_ACMPNE L751 - false
   * 22 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I1256 Branch 86 IF_ACMPNE L757 - false
   * 23 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I1285 Branch 88 IF_ACMPNE L764 - false
   * 24 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I1307 Branch 89 IF_ACMPNE L770 - false
   * 25 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_INIT()V: I197 Branch 5 IFEQ L407 - false
   */

  @Test
  public void test4()  throws Throwable  {
      SFC_COORD__Basic sFC_COORD__Basic0 = new SFC_COORD__Basic();
      sFC_COORD__Basic0.event_INIT(false, false, false, false, false, false, false, true, true, true, false, true, false, false, false, false, false, false, false, false, false, false, false, true, false, false, false, false, false);
      sFC_COORD__Basic0.event_REQ(false, false, true, true, false, false, false, false, true, true, true, true, false, false, false, true, true, true, true, false, true, false, true, true, true, true, false, false, false);
      sFC_COORD__Basic0.event_REQ(false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false);
  }

  //Test case number: 5
  /*
   * 18 covered goals:
   * 1 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I99 Branch 12 IFEQ L438 - false
   * 2 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I106 Branch 13 IF_ACMPNE L439 - true
   * 3 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I146 Branch 15 IFEQ L451 - false
   * 4 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I153 Branch 16 IF_ACMPNE L452 - true
   * 5 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I240 Branch 21 IFEQ L477 - false
   * 6 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I247 Branch 22 IF_ACMPNE L478 - true
   * 7 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I616 Branch 45 IFEQ L581 - false
   * 8 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I623 Branch 46 IF_ACMPNE L582 - true
   * 9 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I663 Branch 48 IFEQ L594 - false
   * 10 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I670 Branch 49 IF_ACMPNE L595 - true
   * 11 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I992 Branch 69 IFEQ L685 - false
   * 12 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I999 Branch 70 IF_ACMPNE L686 - true
   * 13 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I1180 Branch 81 IFEQ L737 - false
   * 14 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I1187 Branch 82 IF_ACMPNE L738 - true
   * 15 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I1227 Branch 84 IFEQ L750 - false
   * 16 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I1234 Branch 85 IF_ACMPNE L751 - true
   * 17 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I1278 Branch 87 IFEQ L763 - false
   * 18 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I1285 Branch 88 IF_ACMPNE L764 - true
   */

  @Test
  public void test5()  throws Throwable  {
      SFC_COORD__Basic sFC_COORD__Basic0 = new SFC_COORD__Basic();
      sFC_COORD__Basic0.event_REQ(false, false, true, true, false, false, false, false, true, true, true, true, false, false, false, true, true, true, true, false, true, false, true, true, true, true, false, false, false);
  }

  //Test case number: 6
  /*
   * 26 covered goals:
   * 1 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.state_INIT()V: root-Branch
   * 2 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I12 Branch 7 IF_ACMPNE L413 - false
   * 3 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I34 Branch 8 IF_ACMPNE L419 - false
   * 4 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I59 Branch 10 IF_ACMPNE L426 - false
   * 5 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I81 Branch 11 IF_ACMPNE L432 - false
   * 6 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I200 Branch 19 IF_ACMPNE L465 - false
   * 7 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I294 Branch 25 IF_ACMPNE L491 - false
   * 8 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I316 Branch 26 IF_ACMPNE L497 - false
   * 9 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I341 Branch 28 IF_ACMPNE L504 - false
   * 10 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I435 Branch 34 IF_ACMPNE L530 - false
   * 11 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I482 Branch 37 IF_ACMPNE L543 - false
   * 12 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I529 Branch 40 IF_ACMPNE L556 - false
   * 13 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I551 Branch 41 IF_ACMPNE L562 - false
   * 14 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I576 Branch 43 IF_ACMPNE L569 - false
   * 15 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I764 Branch 55 IF_ACMPNE L621 - false
   * 16 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I858 Branch 61 IF_ACMPNE L647 - false
   * 17 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I1046 Branch 73 IF_ACMPNE L699 - false
   * 18 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I1068 Branch 74 IF_ACMPNE L705 - false
   * 19 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I1093 Branch 76 IF_ACMPNE L712 - false
   * 20 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I1140 Branch 79 IF_ACMPNE L725 - false
   * 21 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.service_INIT()V: I4 Branch 3 IFNE L360 - false
   * 22 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_INIT()V: I197 Branch 5 IFEQ L407 - true
   * 23 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.serviceEvent(Lfb/rt/EventServer;)V: I5 Branch 1 IF_ACMPNE L354 - false
   * 24 fb.rt.pnp.SFC_COORD__Basic.transition_SFC_COORD_0()V: root-Branch
   * 25 fb.rt.pnp.SFC_COORD__Basic.event_INIT(ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ)V: root-Branch
   * 26 fb.rt.pnp.SFC_COORD__Basic.transition_SFC_COORD_2()V: root-Branch
   */

  @Test
  public void test6()  throws Throwable  {
      SFC_COORD__Basic sFC_COORD__Basic0 = new SFC_COORD__Basic();
      sFC_COORD__Basic0.event_INIT(false, false, false, false, false, false, false, false, false, false, false, false, false, false, true, true, true, false, false, false, true, false, false, true, true, true, false, true, true);
      sFC_COORD__Basic0.event_REQ(true, true, false, false, false, false, false, false, false, false, false, false, true, false, true, true, false, false, false, false, false, true, false, true, false, false, false, false, false);
      sFC_COORD__Basic0.event_REQ(false, false, false, false, false, true, true, false, false, false, true, false, false, true, false, false, true, false, false, false, true, false, true, true, false, false, false, true, false);
  }

  //Test case number: 7
  /*
   * 27 covered goals:
   * 1 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I5 Branch 6 IFEQ L412 - true
   * 2 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I34 Branch 8 IF_ACMPNE L419 - true
   * 3 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I52 Branch 9 IFEQ L425 - true
   * 4 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I81 Branch 11 IF_ACMPNE L432 - true
   * 5 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I193 Branch 18 IFEQ L464 - false
   * 6 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I200 Branch 19 IF_ACMPNE L465 - true
   * 7 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I287 Branch 24 IFEQ L490 - true
   * 8 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I316 Branch 26 IF_ACMPNE L497 - true
   * 9 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I334 Branch 27 IFEQ L503 - false
   * 10 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I341 Branch 28 IF_ACMPNE L504 - true
   * 11 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I428 Branch 33 IFEQ L529 - false
   * 12 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I435 Branch 34 IF_ACMPNE L530 - true
   * 13 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I475 Branch 36 IFEQ L542 - false
   * 14 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I482 Branch 37 IF_ACMPNE L543 - true
   * 15 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I522 Branch 39 IFEQ L555 - true
   * 16 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I551 Branch 41 IF_ACMPNE L562 - true
   * 17 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I569 Branch 42 IFEQ L568 - false
   * 18 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I576 Branch 43 IF_ACMPNE L569 - true
   * 19 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I757 Branch 54 IFEQ L620 - false
   * 20 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I764 Branch 55 IF_ACMPNE L621 - true
   * 21 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I851 Branch 60 IFEQ L646 - false
   * 22 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I858 Branch 61 IF_ACMPNE L647 - true
   * 23 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I1039 Branch 72 IFEQ L698 - true
   * 24 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I1068 Branch 74 IF_ACMPNE L705 - true
   * 25 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I1086 Branch 75 IFEQ L711 - false
   * 26 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I1093 Branch 76 IF_ACMPNE L712 - true
   * 27 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I1484 Branch 99 IFEQ L815 - false
   */

  @Test
  public void test7()  throws Throwable  {
      SFC_COORD__Basic sFC_COORD__Basic0 = new SFC_COORD__Basic();
      sFC_COORD__Basic0.event_REQ(false, false, false, false, false, true, true, false, false, false, true, false, false, true, false, false, true, false, false, false, true, false, true, true, false, false, false, true, false);
  }

  //Test case number: 8
  /*
   * 73 covered goals:
   * 1 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.<init>(Lfb/rt/pnp/SFC_COORD__Basic;)V: root-Branch
   * 2 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.state_START()V: root-Branch
   * 3 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.state_REQ()V: root-Branch
   * 4 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I5 Branch 6 IFEQ L412 - false
   * 5 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I12 Branch 7 IF_ACMPNE L413 - true
   * 6 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I52 Branch 9 IFEQ L425 - false
   * 7 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I59 Branch 10 IF_ACMPNE L426 - true
   * 8 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I99 Branch 12 IFEQ L438 - true
   * 9 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I128 Branch 14 IF_ACMPNE L445 - true
   * 10 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I146 Branch 15 IFEQ L451 - true
   * 11 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I175 Branch 17 IF_ACMPNE L458 - true
   * 12 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I193 Branch 18 IFEQ L464 - true
   * 13 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I222 Branch 20 IF_ACMPNE L471 - true
   * 14 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I240 Branch 21 IFEQ L477 - true
   * 15 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I269 Branch 23 IF_ACMPNE L484 - true
   * 16 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I287 Branch 24 IFEQ L490 - false
   * 17 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I294 Branch 25 IF_ACMPNE L491 - true
   * 18 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I334 Branch 27 IFEQ L503 - true
   * 19 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I363 Branch 29 IF_ACMPNE L510 - true
   * 20 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I381 Branch 30 IFEQ L516 - true
   * 21 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I410 Branch 32 IF_ACMPNE L523 - true
   * 22 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I428 Branch 33 IFEQ L529 - true
   * 23 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I457 Branch 35 IF_ACMPNE L536 - true
   * 24 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I475 Branch 36 IFEQ L542 - true
   * 25 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I504 Branch 38 IF_ACMPNE L549 - true
   * 26 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I522 Branch 39 IFEQ L555 - false
   * 27 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I529 Branch 40 IF_ACMPNE L556 - true
   * 28 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I569 Branch 42 IFEQ L568 - true
   * 29 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I598 Branch 44 IF_ACMPNE L575 - true
   * 30 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I616 Branch 45 IFEQ L581 - true
   * 31 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I645 Branch 47 IF_ACMPNE L588 - true
   * 32 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I663 Branch 48 IFEQ L594 - true
   * 33 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I692 Branch 50 IF_ACMPNE L601 - true
   * 34 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I710 Branch 51 IFEQ L607 - true
   * 35 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I739 Branch 53 IF_ACMPNE L614 - true
   * 36 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I757 Branch 54 IFEQ L620 - true
   * 37 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I786 Branch 56 IF_ACMPNE L627 - true
   * 38 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I804 Branch 57 IFEQ L633 - true
   * 39 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I833 Branch 59 IF_ACMPNE L640 - true
   * 40 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I851 Branch 60 IFEQ L646 - true
   * 41 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I880 Branch 62 IF_ACMPNE L653 - true
   * 42 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I898 Branch 63 IFEQ L659 - true
   * 43 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I927 Branch 65 IF_ACMPNE L666 - true
   * 44 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I945 Branch 66 IFEQ L672 - true
   * 45 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I974 Branch 68 IF_ACMPNE L679 - true
   * 46 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I992 Branch 69 IFEQ L685 - true
   * 47 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I1021 Branch 71 IF_ACMPNE L692 - true
   * 48 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I1039 Branch 72 IFEQ L698 - false
   * 49 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I1046 Branch 73 IF_ACMPNE L699 - true
   * 50 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I1086 Branch 75 IFEQ L711 - true
   * 51 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I1115 Branch 77 IF_ACMPNE L718 - true
   * 52 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I1133 Branch 78 IFEQ L724 - false
   * 53 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I1140 Branch 79 IF_ACMPNE L725 - true
   * 54 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I1180 Branch 81 IFEQ L737 - true
   * 55 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I1209 Branch 83 IF_ACMPNE L744 - true
   * 56 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I1227 Branch 84 IFEQ L750 - true
   * 57 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I1256 Branch 86 IF_ACMPNE L757 - true
   * 58 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I1278 Branch 87 IFEQ L763 - true
   * 59 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I1307 Branch 89 IF_ACMPNE L770 - true
   * 60 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I1329 Branch 90 IFEQ L776 - true
   * 61 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I1358 Branch 92 IF_ACMPNE L783 - true
   * 62 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I1380 Branch 93 IFEQ L789 - true
   * 63 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I1409 Branch 95 IF_ACMPNE L796 - true
   * 64 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I1431 Branch 96 IFEQ L802 - true
   * 65 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I1460 Branch 98 IF_ACMPNE L809 - true
   * 66 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.alg_REQ()V: I1484 Branch 99 IFEQ L815 - true
   * 67 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.service_REQ()V: I4 Branch 4 IFNE L368 - false
   * 68 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.serviceEvent(Lfb/rt/EventServer;)V: I5 Branch 1 IF_ACMPNE L354 - true
   * 69 fb.rt.pnp.SFC_COORD__Basic$SFC_COORD.serviceEvent(Lfb/rt/EventServer;)V: I14 Branch 2 IF_ACMPNE L355 - false
   * 70 fb.rt.pnp.SFC_COORD__Basic.<init>()V: root-Branch
   * 71 fb.rt.pnp.SFC_COORD__Basic.transition_SFC_COORD_1()V: root-Branch
   * 72 fb.rt.pnp.SFC_COORD__Basic.event_REQ(ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ)V: root-Branch
   * 73 fb.rt.pnp.SFC_COORD__Basic.transition_SFC_COORD_3()V: root-Branch
   */

  @Test
  public void test8()  throws Throwable  {
      SFC_COORD__Basic sFC_COORD__Basic0 = new SFC_COORD__Basic();
      sFC_COORD__Basic0.event_REQ(true, true, false, false, false, false, false, false, false, false, false, false, true, false, true, true, false, false, false, false, false, true, false, true, false, false, false, false, false);
  }
}
