/*
 * This file was automatically generated by EvoSuite
 * Wed Jan 07 17:47:50 MSK 2015
 */

package fb.rt.pnp;

import static org.junit.Assert.*;
import org.junit.Test;
import fb.rt.pnp.SlaveCylinder_TEST__Basic;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.EvoSuiteFile;
import org.junit.runner.RunWith;


public class SlaveCylinder_TEST__Basic_Tr_ESTest {

  //Test case number: 0
  /*
   * 2 covered goals:
   * 1 fb.rt.pnp.SlaveCylinder_TEST__Basic.transition_SlaveCylinder_TEST_2()V: root-Branch
   * 2 fb.rt.pnp.SlaveCylinder_TEST__Basic.transition_SlaveCylinder_TEST_3()V: root-Branch
   */

  @Test
  public void test0()  throws Throwable  {
      SlaveCylinder_TEST__Basic slaveCylinder_TEST__Basic0 = new SlaveCylinder_TEST__Basic();
      slaveCylinder_TEST__Basic0.event_INIT(2.0F);
  }

  //Test case number: 1
  /*
   * 2 covered goals:
   * 1 fb.rt.pnp.SlaveCylinder_TEST__Basic.transition_SlaveCylinder_TEST_1()V: root-Branch
   * 2 fb.rt.pnp.SlaveCylinder_TEST__Basic.transition_SlaveCylinder_TEST_5()V: root-Branch
   */

  @Test
  public void test1()  throws Throwable  {
      SlaveCylinder_TEST__Basic slaveCylinder_TEST__Basic0 = new SlaveCylinder_TEST__Basic();
      slaveCylinder_TEST__Basic0.event_REQ(true, true, true, true);
  }

  //Test case number: 2
  /*
   * 2 covered goals:
   * 1 fb.rt.pnp.SlaveCylinder_TEST__Basic.transition_SlaveCylinder_TEST_4()V: root-Branch
   * 2 fb.rt.pnp.SlaveCylinder_TEST__Basic.transition_SlaveCylinder_TEST_0()V: root-Branch
   */

  @Test
  public void test2()  throws Throwable  {
      SlaveCylinder_TEST__Basic slaveCylinder_TEST__Basic0 = new SlaveCylinder_TEST__Basic();
      slaveCylinder_TEST__Basic0.event_Order(1.0F);
  }
}
