/*
 * This file was automatically generated by EvoSuite
 * Wed Jan 07 04:09:52 MSK 2015
 */

package fb.rt.pnp;

import static org.junit.Assert.*;
import org.junit.Test;
import fb.rt.pnp.TRAY_HMI__Basic;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.EvoSuiteFile;
import org.junit.runner.RunWith;


public class TRAY_HMI__Basic_ESTest {

  //Test case number: 0
  /*
   * 3 covered goals:
   * 1 fb.rt.pnp.TRAY_HMI__Basic$TRAY_HMI.alg_INIT()V: I5 Branch 3 IFEQ L104 - true
   * 2 fb.rt.pnp.TRAY_HMI__Basic$TRAY_HMI.alg_INIT()V: I17 Branch 4 IFEQ L108 - true
   * 3 fb.rt.pnp.TRAY_HMI__Basic$TRAY_HMI.alg_INIT()V: I29 Branch 5 IFEQ L112 - true
   */

  @Test
  public void test0()  throws Throwable  {
      TRAY_HMI__Basic tRAY_HMI__Basic0 = new TRAY_HMI__Basic();
      tRAY_HMI__Basic0.event_INIT(false, false, false);
  }

  //Test case number: 1
  /*
   * 12 covered goals:
   * 1 fb.rt.pnp.TRAY_HMI__Basic$TRAY_HMI.state_INIT()V: root-Branch
   * 2 fb.rt.pnp.TRAY_HMI__Basic$TRAY_HMI.state_START()V: root-Branch
   * 3 fb.rt.pnp.TRAY_HMI__Basic$TRAY_HMI.<init>(Lfb/rt/pnp/TRAY_HMI__Basic;)V: root-Branch
   * 4 fb.rt.pnp.TRAY_HMI__Basic$TRAY_HMI.service_INIT()V: I4 Branch 2 IFNE L96 - false
   * 5 fb.rt.pnp.TRAY_HMI__Basic$TRAY_HMI.alg_INIT()V: I5 Branch 3 IFEQ L104 - false
   * 6 fb.rt.pnp.TRAY_HMI__Basic$TRAY_HMI.alg_INIT()V: I17 Branch 4 IFEQ L108 - false
   * 7 fb.rt.pnp.TRAY_HMI__Basic$TRAY_HMI.alg_INIT()V: I29 Branch 5 IFEQ L112 - false
   * 8 fb.rt.pnp.TRAY_HMI__Basic$TRAY_HMI.serviceEvent(Lfb/rt/EventServer;)V: I5 Branch 1 IF_ACMPNE L91 - false
   * 9 fb.rt.pnp.TRAY_HMI__Basic.transition_TRAY_HMI_1()V: root-Branch
   * 10 fb.rt.pnp.TRAY_HMI__Basic.<init>()V: root-Branch
   * 11 fb.rt.pnp.TRAY_HMI__Basic.event_INIT(ZZZ)V: root-Branch
   * 12 fb.rt.pnp.TRAY_HMI__Basic.transition_TRAY_HMI_0()V: root-Branch
   */

  @Test
  public void test1()  throws Throwable  {
      TRAY_HMI__Basic tRAY_HMI__Basic0 = new TRAY_HMI__Basic();
      tRAY_HMI__Basic0.event_INIT(true, true, true);
  }
}
