/*
 * This file was automatically generated by EvoSuite
 * Wed Jan 07 18:08:03 MSK 2015
 */

package fb.rt.pnp;

import static org.junit.Assert.*;
import org.junit.Test;
import fb.rt.pnp.TRAY_HMI__Basic;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.EvoSuiteFile;
import org.junit.runner.RunWith;


public class TRAY_HMI__Basic_Tr_ESTest {

  //Test case number: 0
  /*
   * 2 covered goals:
   * 1 fb.rt.pnp.TRAY_HMI__Basic.transition_TRAY_HMI_1()V: root-Branch
   * 2 fb.rt.pnp.TRAY_HMI__Basic.transition_TRAY_HMI_0()V: root-Branch
   */

  @Test
  public void test0()  throws Throwable  {
      TRAY_HMI__Basic tRAY_HMI__Basic0 = new TRAY_HMI__Basic();
      tRAY_HMI__Basic0.event_INIT(true, true, true);
  }
}
