/*
 * This file was automatically generated by EvoSuite
 * Wed Jan 07 04:19:59 MSK 2015
 */

package fb.rt.pnp;

import static org.junit.Assert.*;
import org.junit.Test;
import fb.rt.pnp.vaccum3__Basic;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.EvoSuiteFile;
import org.junit.runner.RunWith;


public class vaccum3__Basic_ESTest {

  //Test case number: 0
  /*
   * 1 covered goal:
   * 1 fb.rt.pnp.vaccum3__Basic$vaccum3.service_IN_CMD()V: I31 Branch 12 IFEQ L166 - true
   */

  @Test
  public void test0()  throws Throwable  {
      vaccum3__Basic vaccum3__Basic0 = new vaccum3__Basic();
      vaccum3__Basic0.event_INIT(true, true, true);
      vaccum3__Basic0.event_IN_CMD(true, true);
      vaccum3__Basic0.event_Req(true);
      vaccum3__Basic0.event_IN_CMD(true, false);
  }

  //Test case number: 1
  /*
   * 2 covered goals:
   * 1 fb.rt.pnp.vaccum3__Basic$vaccum3.service_IN_CMD()V: I9 Branch 10 IFEQ L162 - true
   * 2 fb.rt.pnp.vaccum3__Basic$vaccum3.service_IN_CMD()V: I27 Branch 11 IF_ICMPNE L166 - true
   */

  @Test
  public void test1()  throws Throwable  {
      vaccum3__Basic vaccum3__Basic0 = new vaccum3__Basic();
      vaccum3__Basic0.event_INIT(false, true, false);
      vaccum3__Basic0.event_IN_CMD(false, false);
  }

  //Test case number: 2
  /*
   * 1 covered goal:
   * 1 fb.rt.pnp.vaccum3__Basic$vaccum3.service_Req()V: I31 Branch 8 IFEQ L154 - true
   */

  @Test
  public void test2()  throws Throwable  {
      vaccum3__Basic vaccum3__Basic0 = new vaccum3__Basic();
      vaccum3__Basic0.event_INIT(true, true, true);
      vaccum3__Basic0.event_IN_CMD(true, true);
      vaccum3__Basic0.event_Req(false);
  }

  //Test case number: 3
  /*
   * 2 covered goals:
   * 1 fb.rt.pnp.vaccum3__Basic$vaccum3.service_Req()V: I9 Branch 6 IFNE L150 - true
   * 2 fb.rt.pnp.vaccum3__Basic$vaccum3.service_Req()V: I27 Branch 7 IF_ICMPNE L154 - true
   */

  @Test
  public void test3()  throws Throwable  {
      vaccum3__Basic vaccum3__Basic0 = new vaccum3__Basic();
      vaccum3__Basic0.event_INIT(false, true, false);
      vaccum3__Basic0.event_IN_CMD(true, true);
      vaccum3__Basic0.event_Req(true);
      vaccum3__Basic0.event_IN_CMD(true, true);
      vaccum3__Basic0.event_Req(true);
  }

  //Test case number: 4
  /*
   * 1 covered goal:
   * 1 fb.rt.pnp.vaccum3__Basic$vaccum3.service_INIT()V: I4 Branch 4 IFNE L142 - true
   */

  @Test
  public void test4()  throws Throwable  {
      vaccum3__Basic vaccum3__Basic0 = new vaccum3__Basic();
      vaccum3__Basic0.event_INIT(false, true, false);
      vaccum3__Basic0.event_INIT(true, true, true);
  }

  //Test case number: 5
  /*
   * 35 covered goals:
   * 1 fb.rt.pnp.vaccum3__Basic.event_IN_CMD(ZZ)V: root-Branch
   * 2 fb.rt.pnp.vaccum3__Basic.transition_vaccum3_0()V: root-Branch
   * 3 fb.rt.pnp.vaccum3__Basic.<init>()V: root-Branch
   * 4 fb.rt.pnp.vaccum3__Basic.event_INIT(ZZZ)V: root-Branch
   * 5 fb.rt.pnp.vaccum3__Basic.event_Req(Z)V: root-Branch
   * 6 fb.rt.pnp.vaccum3__Basic.transition_vaccum3_1()V: root-Branch
   * 7 fb.rt.pnp.vaccum3__Basic.transition_vaccum3_2()V: root-Branch
   * 8 fb.rt.pnp.vaccum3__Basic.transition_vaccum3_3()V: root-Branch
   * 9 fb.rt.pnp.vaccum3__Basic.transition_vaccum3_5()V: root-Branch
   * 10 fb.rt.pnp.vaccum3__Basic.transition_vaccum3_4()V: root-Branch
   * 11 fb.rt.pnp.vaccum3__Basic$vaccum3.state_INIT()V: root-Branch
   * 12 fb.rt.pnp.vaccum3__Basic$vaccum3.alg_Drop()V: root-Branch
   * 13 fb.rt.pnp.vaccum3__Basic$vaccum3.<init>(Lfb/rt/pnp/vaccum3__Basic;)V: root-Branch
   * 14 fb.rt.pnp.vaccum3__Basic$vaccum3.state_Drop()V: root-Branch
   * 15 fb.rt.pnp.vaccum3__Basic$vaccum3.alg_suction()V: root-Branch
   * 16 fb.rt.pnp.vaccum3__Basic$vaccum3.alg_INIT()V: root-Branch
   * 17 fb.rt.pnp.vaccum3__Basic$vaccum3.state_VaccumOn()V: root-Branch
   * 18 fb.rt.pnp.vaccum3__Basic$vaccum3.state_VaccumOff()V: root-Branch
   * 19 fb.rt.pnp.vaccum3__Basic$vaccum3.state_suction()V: root-Branch
   * 20 fb.rt.pnp.vaccum3__Basic$vaccum3.service_IN_CMD()V: I5 Branch 9 IF_ICMPNE L162 - true
   * 21 fb.rt.pnp.vaccum3__Basic$vaccum3.service_IN_CMD()V: I5 Branch 9 IF_ICMPNE L162 - false
   * 22 fb.rt.pnp.vaccum3__Basic$vaccum3.service_IN_CMD()V: I9 Branch 10 IFEQ L162 - false
   * 23 fb.rt.pnp.vaccum3__Basic$vaccum3.service_IN_CMD()V: I27 Branch 11 IF_ICMPNE L166 - false
   * 24 fb.rt.pnp.vaccum3__Basic$vaccum3.service_IN_CMD()V: I31 Branch 12 IFEQ L166 - false
   * 25 fb.rt.pnp.vaccum3__Basic$vaccum3.service_INIT()V: I4 Branch 4 IFNE L142 - false
   * 26 fb.rt.pnp.vaccum3__Basic$vaccum3.service_Req()V: I5 Branch 5 IF_ICMPNE L150 - true
   * 27 fb.rt.pnp.vaccum3__Basic$vaccum3.service_Req()V: I5 Branch 5 IF_ICMPNE L150 - false
   * 28 fb.rt.pnp.vaccum3__Basic$vaccum3.service_Req()V: I9 Branch 6 IFNE L150 - false
   * 29 fb.rt.pnp.vaccum3__Basic$vaccum3.service_Req()V: I27 Branch 7 IF_ICMPNE L154 - false
   * 30 fb.rt.pnp.vaccum3__Basic$vaccum3.service_Req()V: I31 Branch 8 IFEQ L154 - false
   * 31 fb.rt.pnp.vaccum3__Basic$vaccum3.serviceEvent(Lfb/rt/EventServer;)V: I5 Branch 1 IF_ACMPNE L135 - true
   * 32 fb.rt.pnp.vaccum3__Basic$vaccum3.serviceEvent(Lfb/rt/EventServer;)V: I5 Branch 1 IF_ACMPNE L135 - false
   * 33 fb.rt.pnp.vaccum3__Basic$vaccum3.serviceEvent(Lfb/rt/EventServer;)V: I14 Branch 2 IF_ACMPNE L136 - true
   * 34 fb.rt.pnp.vaccum3__Basic$vaccum3.serviceEvent(Lfb/rt/EventServer;)V: I14 Branch 2 IF_ACMPNE L136 - false
   * 35 fb.rt.pnp.vaccum3__Basic$vaccum3.serviceEvent(Lfb/rt/EventServer;)V: I23 Branch 3 IF_ACMPNE L137 - false
   */

  @Test
  public void test5()  throws Throwable  {
      vaccum3__Basic vaccum3__Basic0 = new vaccum3__Basic();
      vaccum3__Basic0.event_INIT(false, true, false);
      vaccum3__Basic0.event_IN_CMD(true, true);
      vaccum3__Basic0.event_Req(true);
      vaccum3__Basic0.event_IN_CMD(true, true);
      vaccum3__Basic0.event_Req(false);
  }
}
