/*
 * This file was automatically generated by EvoSuite
 * Wed Jan 07 18:48:30 MSK 2015
 */

package fb.rt.pnp;

import static org.junit.Assert.*;
import org.junit.Test;
import fb.rt.pnp.WPMaster__Basic;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.EvoSuiteFile;
import org.junit.runner.RunWith;


public class WPMaster__Basic_Tr_ESTest {

  //Test case number: 0
  /*
   * 2 covered goals:
   * 1 fb.rt.pnp.WPMaster__Basic.transition_WPMaster_11()V: root-Branch
   * 2 fb.rt.pnp.WPMaster__Basic.transition_WPMaster_7()V: root-Branch
   */

  @Test
  public void test0()  throws Throwable  {
      WPMaster__Basic wPMaster__Basic0 = new WPMaster__Basic();
      wPMaster__Basic0.event_REQ(false, false, false, true);
      wPMaster__Basic0.event_RC_CONF(true);
      wPMaster__Basic0.event_LC_CONF(true);
  }

  //Test case number: 1
  /*
   * 5 covered goals:
   * 1 fb.rt.pnp.WPMaster__Basic.transition_WPMaster_13()V: root-Branch
   * 2 fb.rt.pnp.WPMaster__Basic.transition_WPMaster_17()V: root-Branch
   * 3 fb.rt.pnp.WPMaster__Basic.transition_WPMaster_9()V: root-Branch
   * 4 fb.rt.pnp.WPMaster__Basic.transition_WPMaster_5()V: root-Branch
   * 5 fb.rt.pnp.WPMaster__Basic.transition_WPMaster_2()V: root-Branch
   */

  @Test
  public void test1()  throws Throwable  {
      WPMaster__Basic wPMaster__Basic0 = new WPMaster__Basic();
      wPMaster__Basic0.event_REQ(true, true, true, true);
      wPMaster__Basic0.event_LC_CONF(true);
      wPMaster__Basic0.event_VC_CONF(true);
      wPMaster__Basic0.event_VC_CONF(true);
      wPMaster__Basic0.event_RC_CONF(true);
      wPMaster__Basic0.event_LC_CONF(true);
      wPMaster__Basic0.event_VC_CONF(true);
      wPMaster__Basic0.event_VC_CONF(true);
  }

  //Test case number: 2
  /*
   * 6 covered goals:
   * 1 fb.rt.pnp.WPMaster__Basic.transition_WPMaster_10()V: root-Branch
   * 2 fb.rt.pnp.WPMaster__Basic.transition_WPMaster_15()V: root-Branch
   * 3 fb.rt.pnp.WPMaster__Basic.transition_WPMaster_14()V: root-Branch
   * 4 fb.rt.pnp.WPMaster__Basic.transition_WPMaster_16()V: root-Branch
   * 5 fb.rt.pnp.WPMaster__Basic.transition_WPMaster_8()V: root-Branch
   * 6 fb.rt.pnp.WPMaster__Basic.transition_WPMaster_3()V: root-Branch
   */

  @Test
  public void test2()  throws Throwable  {
      WPMaster__Basic wPMaster__Basic0 = new WPMaster__Basic();
      wPMaster__Basic0.event_REQ(true, false, true, false);
      wPMaster__Basic0.event_RC_CONF(true);
      wPMaster__Basic0.event_VC_CONF(true);
      wPMaster__Basic0.event_VC_CONF(true);
      wPMaster__Basic0.event_LC_CONF(true);
      wPMaster__Basic0.event_RC_CONF(true);
  }

  //Test case number: 3
  /*
   * 3 covered goals:
   * 1 fb.rt.pnp.WPMaster__Basic.transition_WPMaster_12()V: root-Branch
   * 2 fb.rt.pnp.WPMaster__Basic.transition_WPMaster_6()V: root-Branch
   * 3 fb.rt.pnp.WPMaster__Basic.transition_WPMaster_4()V: root-Branch
   */

  @Test
  public void test3()  throws Throwable  {
      WPMaster__Basic wPMaster__Basic0 = new WPMaster__Basic();
      wPMaster__Basic0.event_REQ(false, false, false, true);
      wPMaster__Basic0.event_LC_CONF(true);
      wPMaster__Basic0.event_RC_CONF(true);
  }

  //Test case number: 4
  /*
   * 2 covered goals:
   * 1 fb.rt.pnp.WPMaster__Basic.transition_WPMaster_0()V: root-Branch
   * 2 fb.rt.pnp.WPMaster__Basic.transition_WPMaster_1()V: root-Branch
   */

  @Test
  public void test4()  throws Throwable  {
      WPMaster__Basic wPMaster__Basic0 = new WPMaster__Basic();
      wPMaster__Basic0.event_INIT(false, false, false, true);
  }
}
